### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by katutz** [felangel/bloc#10]
Very nice package!

I would like to know if this package will be compatible with Dart for Web, like AngularDart.

Thanks in advance.

**Comment by felangel** [comment]
Thanks!

Yes, this is something that we are discussing and should be coming soon.

**Comment by katutz** [comment]
> Thanks!
> 
> Yes, this is something that we are discussing and should be coming soon.

Thanks for the response. Good to know!

**Comment by bohrmeista** [comment]
Hello, I find your package very helpful when developing AngularDart and Flutter apps on the same codebase.

However I recently found that using `webdev serve --release`or `webdev build` (both producing release builds) makes the plugin unusable as in 'compiles fine, no runtime errors - but no functionality'.

For reference on what I tried check out these gists:
- BLoC: https://gist.github.com/bohrmeista/27119d184e7bedb5ee9ea468672b8f93
- Component Dart: https://gist.github.com/bohrmeista/70575b0948eba332a8d7c37303811670
- Component HTML: https://gist.github.com/bohrmeista/fb8c38c8613575071b9ccfffd249d8f0

When running in development mode (without `--release`or with `--no-release`) it works fine though.
Just using rxDart in an AngularDart app works just fine on the contrary, so I really think the problem lies within this plugin.

For now, I'd propose reopening this issue or opening a new one if you'd like to make it more specific.

**Comment by bohrmeista** [comment]
@felangel I implemented a mock version of the app again to make sure the error is really there and also wrote a test for the BLoC stuff so you might want to use it to test after you've made changes.
https://github.com/bohrmeista/dart_experiments
See the README.md for info on running the test.

I will also create a new issue tomorrow.

**Comment by felangel** [comment]
@bohrmeista I took a look and it looks like runtimeType is the problem in the release build.
If you replace your `mapEventToState` implementation with:
```dart
@override
  Stream<TestState> mapEventToState(TestState state, TestEvent event) async* {
    yield TestState.loading();
    if (event is UpdateEvent) {
      await _getTest();
      yield TestState.result(_response);
    }
    if (event is ClearEvent) {
      yield TestState.result('');
    }
  }
```
it will work.

**Comment by bohrmeista** [comment]
@felangel I tested this in my actual app and now it works just fine. Thanks a lot and sorry for causing you work with this. This actually helped me a lot and I learned something again so big 👍

**Comment by felangel** [comment]
@bohrmeista no problem! Glad I could help 👍

**Comment by katutz** [comment]
> I'm just going to keep this issue closed since it sounds like more of a bug than an enhancement. It would be great if you can just open a bug for this and I will investigate :)
> 
> @katutz have you had a chance to test the package in AngularDart? Just wondering if you're running into the same issue or not.

I haven't tested in AngularDart yet. But I'm glad to see that the problem is solved. Very good work @felangel !
