### ISSUE TITLE
How to get User info on BlocDelegate

### ISSUE THREAD

**Issue by rodrigobastosv** [felangel/bloc#1001]
Hi @felangel , let's say i log events to analytics on BlocDelegate methods.

My question is: is it possible to get for example the logged user info on the delegate to send for example for analytics?

In the end what i want is to know which user push which events?

As always thanks for the great work!

**Comment by RollyPeres** [comment]
@rodrigobastosv are you using firebase auth or how do you authenticate users in your app ?

**Comment by rodrigobastosv** [comment]
Hi @RollyPeres , i'm using Firebase Auth.

**Comment by RollyPeres** [comment]
In this case you could grab your user's details right from the `FirebaseAuth` since it exposes a `Stream` with this data through `onAuthStateChanged`. What I personally do is have a user data provider where I manipulate this stream and then I can inject this provider wherever I need to get the currently logged in user as a stream or synchronously as a user model.
I also pipe this user through a `BehaviorSubject` since I just don't want to re-execute the whole stream chain every single time I'm reading the user. This is basically mirroring the `shareReplay(1)` from rxjs :) rxdart is quite different when it comes to sharing operators so this approach works great in my oppinion. The downside is that you have to dispose the subject, so you can't really inject this user provider in a repository to strictly follow the recommended architecture guideline of bloc. So you kinda have to treat this data provider more like some sort of service that does it's own thing. There might be a better architecture approach to this, so I'd be curious to hear opinions.
My current approach for this is slightly more complex since I'm using monads, but this should be more closer to what you're after. Feel free to adjust to your own needs.

```
part of 'user_provider.dart';

@singleton
@RegisterAs(UserProvider)
class FirebaseUserProvider implements UserProvider {
  FirebaseUserProvider({
    @required FirebaseAuth firebaseAuth,
    @required Firestore firestore,
  })  : assert(firebaseAuth != null),
        assert(firestore != null),
        _firebaseAuth = firebaseAuth,
        _firestore = firestore {
    printCtor();
    // * we pipe it so we can easily share the current user throught the app without reading the firebase user every single time.
    _user.pipe(_currentUser);
  }

  final FirebaseAuth _firebaseAuth;
  final Firestore _firestore;

  final BehaviorSubject<UserModel> _currentUser = BehaviorSubject<UserModel>();

  Stream<UserModel> get _user => _firebaseAuth.onAuthStateChanged
      // .printIdToken()
      .switchMap<UserModel>((firebaseUser) => firebaseUser == null ||
              firebaseUser.uid.isBlank
          ? Stream.value(null)
          : _firestore
              .document('users/${firebaseUser.uid}')
              .snapshots()
              .map<UserModel>((snapshot) => UserModel.fromMap(snapshot.data)));

  @override
  Stream<UserModel> get currentUser$ => _currentUser.stream;

  @override
  UserModel get currentUser => _currentUser.value;

  @override
  Future<void> dispose() async {
    await _currentUser?.close();
  }
}
``` 
You could then inject your `UserProvider` into your own custom `BlocDelegate`.
```
BlocSupervisor.delegate =
      AppBlocDelegate(userProvider: locator.get<UserProvider>());
```
You don't have to use `get_it`/`injectable` for this, you could just create your own class however you prefer. I'm using it since it helps with providing different concrete implementations based on the environment/flavor.

**Comment by rodrigobastosv** [comment]
Wow, thank you @RollyPeres !
