### ISSUE TITLE
[question]  stopping ListView.builder from within BlocBuilder (returning null from BlocBuilder would be nice)

### ISSUE THREAD

**Issue by filly82** [felangel/bloc#1012]
sorry for posting my question here and not on stackoverflow. I just thought that maybe here I'll get better help :)

I want to build the items in a listview succesively one after the other.
My Bloc is getting its data from a stream, I do not know how much data is coming until it stops, so my State (**FilmeStateLoaded**) is getting yielded n-times

I'm using the **BlocBuilder** as the Item itself and not as the whole ListView. therefore i do not have the itemCount for the ListView (at least not where I need it). 
But I do know when to stop building the ListView (the **ListView.builder** allows to stop building by returning null to the **itemBuilder**, the problem is that the **BlocBuilder** does not allow to return null. So my ListView remains an infinite List filled with the infinite placeholders-Text-Widgets

I could use the BlocBuilder as a parent of the ListView, but then the complete ListView would rebuild n-times.

Is there a reason that BlocBuilder does not allow to return null? That would be great in this special scenario :)

Does anyone know how to achieve my goal somehow different? I'm very open for any kind of approach

```
return ListView.builder(itemBuilder: (context, index)
    {
      return BlocBuilder<FilmeBloc, FilmeState>(
          builder: (context, state) {
            if (state is FilmeStateLoaded) {
              if (index < state.moviesFiltered.length)
                return Container(child:Text(state.moviesFiltered.elementAt(index)["movieKey"]));
              //return null; // <-- does not work in BlocBuilder but would work in ListView.builder
            }

            return Container(child:Text("placeholder")); //
          });
    });
```

**Comment by theDarkBoffin** [comment]
Hey @filly82,
If I understand this correctly, you've got **N** items, which are being loaded dynamically. I understand you don't know the number of items in prior.

What's the problem with wrapping the whole `ListView.builder` directly inside `BlocBuilder` instead of keeping a `BlocBuilder` inside `ListView.builder`?
If you're worried about performance implications, you must know that ListView.builder lazily loads visible items, so that shouldn't be a problem. Does the below code work for you?

`return BlocBuilder<FilmeBloc, FilmeState>(
          builder: (context, state) {
            return ListView.builder(
                itemBuilder: (context, index) {
                  return Container(child:Text(state.moviesFiltered.elementAt(index)["movieKey"]));
                },
            itemCount: state.moviesFiltered.length); //
          });`

@felangel if there's a better solution so that the whole listview doesn't get rebuilt, I'm interested too.

**Comment by felangel** [comment]
As @theDarkBoffin mentioned, the simplest solution is to wrap the `ListView.builder` in a `BlocBuilder` and there shouldn't be any performance impact because only the visible portion of the list is being rebuilt.
