### ISSUE TITLE
Is there a way to access context inside the bloc class?

### ISSUE THREAD

**Issue by ffpetrovic** [felangel/bloc#1030]
Is there a way I can access `context` inside `mapEventToState`?

**Comment by felangel** [comment]
Hi @ffpetrovic 👋
Thanks for opening an issue!

BuildContext is not available inside a bloc because blocs are pure dart and BuildContext should only be used within the widget tree. If BuildContext was available inside the bloc, you would not be able to reuse blocs in AngularDart or for Dart CLIs etc...

Instead of trying to use BuildContext within your bloc, I would recommend using BuildContext within the widget tree to get whatever object you need and inject that object into the bloc.

Hope that helps 👍

**Comment by RobertApikyan** [comment]
I understand, and may be this is too late to ask or not a right place, however answer will be appreciated, what if bloc need to do a navigation to other screen, and for that context is needed, is it ok to pass the context through event to block, so block can handle that navigation internally?

**Comment by maherjaafar** [comment]
@RobertApikyan You can handle the navigation with a BlocListener when the event is changed.

**Comment by felangel** [comment]
I recommend checking out https://bloclibrary.dev/#/recipesflutternavigation

**Comment by giaur500** [comment]
Some other thoughts about context inside bloc. I need to add support for multiple languages in my app, there's soultion for that: https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization

But it sill requires to access app context to get localized strings. In my app, there's several `emit` calls, with some messages and they need to be localized too. Should I somehow inject strings/context to my bloc or is there any other way?
