### ISSUE TITLE
How to get the current state!

### ISSUE THREAD

**Issue by raslan3333** [felangel/bloc#1106]
When I try to print the current state, I get always the initialState!

`enum CounterEvent { increment, decrement }

class CounterBloc extends Bloc<CounterEvent, int> {
  @override
  int get initialState => 0;

  @override
  Stream<int> mapEventToState(CounterEvent event) async* {
    switch (event) {
      case CounterEvent.decrement:
        yield state - 1;
        break;
      case CounterEvent.increment:
        yield state + 1;
        break;
      default:
        throw Exception('unhandled event: $event');
    }
  }
}

void main() {
  final counterBloc = CounterBloc();

  counterBloc.add(CounterEvent.increment);
  counterBloc.add(CounterEvent.increment);
  counterBloc.add(CounterEvent.increment);

  print(counterBloc.state);
}`

**Comment by RollyPeres** [comment]
Hi @raslan3333 !

Your issue is in the method signature, it should be  `Stream<int> mapEventToState(CounterEvent event)`. 😉

**Comment by RollyPeres** [comment]
@raslan3333 Sorry, I missed the part where you were saying about the printing value.

You will always get initialValue there because events are handled asynchronously(but in the order they are added). So basically after you add those events your code will move forward and print the existing value which is 0 in your case. The added events will then be processed by the bloc. If you wish to see the current value you need to print from the bloc itself or to listen to the bloc state and print there.

Sorry again for missing out on this detail Hope it gives you a better understanding 👍

**Comment by raslan3333** [comment]
thank you,
`  List<int> myList = [];
  counterBloc.listen((v) => { myList.add(v) }).onDone(() => { print(myList.last) });`

I don't know if I will need this ever but I just wanted to understand how it work,
with flutter_bloc it is mutch easier.

thanks 👍

**Comment by felangel** [comment]
@raslan3333 you can also do

```dart
counterBloc.listen(print);
```

if you just want to see the values printed as the are emitted by the bloc.

**Comment by raslan3333** [comment]
this is mutch easier and cleaner, thank you
