### ISSUE TITLE
[question] One or multiple blocs for an entity ?

### ISSUE THREAD

**Issue by fvisticot** [felangel/bloc#1114]
If we take the sample Todos app available with bloc implementation.
A TodosBloc is used for adding / updating / getting Todo Entity

If an application has a complex Todo management (multiple screens to update different fields)
Each update operation related to the Todo needs to be done on dedicated Todo Screen
This dedicated TodoScreen needs to display Loading / Saving / Refreshing the state of the Todo

In that case is it a good practice to use a TodoBloc to manage operation related to a specific Todo ?
Do we need to "link" both Todo and Todos Bloc ?

**Comment by felangel** [comment]
Hi @fvisticot 👋 
Thanks for opening an issue!

It totally depends on the specific use-case but in the situation you've described it might make sense to manage the list of Todo IDs via the `TodosBloc` state and then manage the state of individual todos via their own `TodoBloc` like you mentioned. The key thing in my opinion, is to avoid redundancy in state between the `TodoBloc` and `TodosBloc` because you'll have to keep them in sync. It probably would make sense to use the `TodosBloc` to just manage the load and state of the todos list and rely on the individual `TodoBloc` to handle the rest. In this setup each TodoBloc will have a dependency on the `TodosBloc` and will need to notify the `TodosBloc` if a todo is deleted or created.

If you'd like to work through the implementation together I'm happy to do so, just message me on [discord](https://discord.gg/Hc5KD3g) 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
