### ISSUE TITLE
Bloc not outputting state with a list which has a value removed or modified.

### ISSUE THREAD

**Issue by abinvp** [felangel/bloc#114]
**Describe the bug**
I have an event that dispatches `EmailDeleted` event with the email to be removed. The state is not getting updated after the email is removed from the list and pushing new state.

**My mapEventToState method**

``` dart
@override
  Stream<InviteState> mapEventToState(
    InviteState currentState,
    InviteEvent event,
  ) async* {
    if (event is ScreenInitialized) {
      final List<String> _emails = [];
      yield EmailListUpdated(emails: _emails);
    }

    if (event is EmailSubmitted && currentState is EmailListUpdated) {
      if (!isEmail(event.email)) {
        yield currentState.copyWith(error: 'Please enter a valid email');
      } else {
        yield EmailListUpdated(emails: currentState.emails + [event.email]);
      }
    }

    if (event is EmailDeleted && currentState is EmailListUpdated) {
      yield EmailListUpdated(emails: currentState.emails..remove(event.email));
    }
  }
```

The following piece of code is supposed to remove the email passed in the event and map the new state but it isn't working. 

``` dart
if (event is EmailDeleted && currentState is EmailsListUpdated) {
      yield EmailsListUpdated(emails: currentState.emails..remove(event.email));
}
```

It works only if I remove extending Equatable or trigger another event with a different state and then trigger the delete event. Even in that case it will identify the change only for the first removal and ignores all changes thereafter.

Do you see any problem with the code? Any help will be highly appreciated. Thanks in advanve!

**Comment by felangel** [comment]
@abinvp thanks for opening this!
I think in order to understand why it's not working you need to understand two things:

First, if you yield the same state over and over it will not impact a Bloc (meaning no transition will occur and the UI won't be rebuilt). In your case, you are yielding the same event multiple times (`EmailsListUpdated(emails: ...)`).

The second part is why it works without `Equatable`.
It works without Equatable because by default two different instances will not be equal:
```dart
print(EmailsListUpdated(emails: []) == EmailsListUpdated(emails: [])); // false
```
 
In order to make the above statement true you would use `Equatable` or override `==` and `hashCode` yourself.

So when writing blocs and yielding states you need to keep in mind if you yield `state` where `state == currentState` then nothing will happen because from the bloc's perspective nothing has changed.

Let me know if that helps 👍 
If you are still having trouble and can give me access to your code then I can open a PR?

**Comment by abinvp** [comment]
@felangel, thank you for your response. Your response time is quite impressive :)

Even though I was yielding the same state, the emails list is modified. Just like `EmailListUpdated(emails: currentState.emails + [event.email])` for add events, I was expecting  `EmailListUpdated(emails: currentState.emails..remove(event.email));` to work.

**Comment by felangel** [comment]
Thanks haha 😄 

Is it possible for you to share a project that has the problem you're seeing? It'll be easier for me to help if I can have access to the full source code 👍

**Comment by abinvp** [comment]
Yes, I will get that shortly. Thank you!

**Comment by abinvp** [comment]
Hey @felangel,

I've pushed the code here. https://github.com/abinvp/flutter_bloc_package_demo
You can see a simple screen where users can be invited using the emails. The invited user's email will be displayed as chips in the UI. On clicking the close icon in the chip, that particular email should be removed and the UI should be updated.

**Comment by felangel** [comment]
@abinvp I've created a [PR](https://github.com/abinvp/flutter_bloc_package_demo/pull/1) to fix your issue. It was because you were mutating the list of emails instead of creating a new list. Bloc is built on the assumption that all state is immutable so you need to ensure that you are always creating new instances of state (all parts) instead of modifying the currentState.

Hope that helps! 👍

**Comment by abinvp** [comment]
Makes total sense @felangel.  That was an overlook from my side. Thank you so much for helping out and writing this wonderful package. 👍

**Comment by felangel** [comment]
No problem! It was a great question and evidence that I need to continue to improve the documentation 😅. Thanks for the positive feedback; I really appreciate it! 👍

**Comment by khalithartmann** [comment]
@felangel  dude ur awsome !!! thanks a lot

**Comment by pardipbhatti8791** [comment]
Hi I am using flutter_bloc package, at signing page while I am using Signin() instead of splash screen then redirecting working fine. but if use splash screen then login screen not redirecting to home. https://cl.ly/9be9be5eb844

**Comment by pardipbhatti8791** [comment]
https://cl.ly/967a4cd69e4d

**Comment by felangel** [comment]
@pardipbhatti8791 can you share a link to the repo? It would be much easier for me to help if I could run the application locally 👍
