### ISSUE TITLE
BlocProvider.of null safe alternative

### ISSUE THREAD

**Issue by jensencelestial** [felangel/bloc#1225]
Good Day,

Is there a null safe way to `BlocProvider.of` that returns `null` if the `Bloc` instance requested is not existing? Currently it throws `ProviderNotFoundException` which requires wrapping the statement into a `try/catch` block, adding a little boilerplate to the code.

Any suggestions are highly appreciated! And thank you very much for this library 😄

**Comment by RollyPeres** [comment]
Hi @jensencelestial 👋

The point of that exception being thrown is to help you in dev mode identify that you're not correctly providing your bloc; as a side note, the exception comes from the `provider` package and not bloc.

You shouldn't be needing to wrap your calls to `BlocProvider.of` in `try catch` blocks since that's a safe operation as long as you're placing your blocs in the right place within the widget tree. If you're stumbling upon that exception it only means you're not properly providing your blocs.

As a conclusion, `ProviderNotFoundException` is a feature and we shouldn't need or care to disable it, but instead make use of it. 👍

**Comment by felangel** [comment]
Hi @jensencelestial 👋 
Thanks for opening an issue!

As @RollyPeres pointed out this behavior comes from the `provider` package and you should ensure that the bloc is being provided correctly in order to address the exception rather than wrapping the `.of` in a try/catch.

Hope that helps 👍

**Comment by enricobenedos** [comment]
Hey guys, sorry for the intrusion. 
I'm facing with a similar problem: I have an utilities class that I reuse on different widgets of my app and one method of this class make some work based on inherited bloc state. Sometimes sometimes this work is done using `ToursBloc` state and sometimes I need to do this work using `CustomerBloc` state. Why I need to do this? Because both these blocs contains a common information that I need to make some work.
I try to give you an example to be more clear:
```dart
final customerBloc = BlocProvider.of<CustomerBloc>(context);
    if (customerBloc != null) {
      //Do work
    }
    final toursBloc = BlocProvider.of<ToursBloc>(context);
    if (toursBloc != null) {
      //Do work
    }
```
Sometimes this class inherit a `ToursBloc` and sometimes it inherits a `CustomerBloc`but with the above sample the package (`provider` if I correctly understand) thrown an exception because one of the two blocs does not exist.
```
FlutterError (        BlocProvider.of() called with a context that does not contain a Bloc of type Bloc<dynamic, dynamic>.
        No ancestor could be found starting from the context that was passed to BlocProvider.of<Bloc<dynamic, dynamic>>().

        This can happen if the context you used comes from a widget above the BlocProvider.
```
I've tried also with this strategy but the error is the same:
```dart
    final bloc = BlocProvider.of(context);
    if (bloc is CustomerBloc) {
      //Do work
    }
    if (bloc is ToursBloc) {
      //Do work
    }
```
How can I retrieve a bloc not knowing the type and then cast/test it in order to use its state?

**Comment by RollyPeres** [comment]
Hi @enricobenedos 👋

You should always know the type of blocs you're working with.
Most likely your issues comes from the current approach. Have you considered gathering all that common data and functionality into a separate bloc ? Or maybe your UI should be structured differently.

If you can't wrap your head around this feel free to share a minimal gist/repo with your feature and I'm happy to have a look 👍

**Comment by enricobenedos** [comment]
Hi @RollyPeres, 
thank you for your help. 
I was already aware that it was probably not possible to do what I wanted to do. 
Your explanation confirm me that I was fighting against the cornerstones that make this library so effective.
I will try to refactor my code, If I need help I will not hesitate to open a new issue.
Thank you for your time 😊

**Comment by s6joui** [comment]
As of Provider version `6.0.0` the `provider` package supports this:

```
Provider.of<MyCubit?>(context)?.start();
```

However using `BlocProvider.of` does not work.

```
BlocProvider.of<MyCubit?>(context)?.start(); // DOES NOT WORK
```
Would be nice if bloc included this now that it's supported in the provider package.

**Comment by jensencelestial** [comment]
Hey @cu-kha ,

Have you tried `context.of<MyCubit?>`? It works on my use case.

**Comment by CosmicPangolin** [comment]
I would also love to see this match Provider. I have complex nested routes where optional bloc dependencies are a terse and elegant way of expressing chains of events within a navigation stack.

**Comment by Gustl22** [comment]
`context.read<MyBloc?>()` returning `null` works also fine for me!
