### ISSUE TITLE
How to yield multiple states at the same time.

### ISSUE THREAD

**Issue by newajthevillager** [felangel/bloc#1226]
In my Ui there are mainly two parts, one shows article details, another part is a button where it shows whether the user is authenticated or guest user. I have two events for these two UI. I can show the first part UI (article details) using BlocBuilder & checking the posiible states for that event. But I dont know how to render UI for the other states. Should I use another BlocBuilder?

**Comment by RollyPeres** [comment]
Hi @newajthevillager 👋

You can definitely use a separate bloc builder hooked to your auth bloc to show your user state.

**Comment by felangel** [comment]
Hi @newajthevillager 👋 
Thanks for opening an issue!

As @RollyPeres mentioned, you can definitely wrap different parts of your UI in BlocBuilders in order to rebuild those widgets based on state changes in a bloc 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
