### ISSUE TITLE
to Main the Successful List with Bottom Navigation Bar changed on flutter_bloc

### ISSUE THREAD

**Issue by yetunnaing18121996** [felangel/bloc#1229]
I have three tabs on Bottom Navigation with different blocs, after I clicked the other item bar and try to click the old one, the lists that I have been fetched don't exist and then bloc start listening again and try to fetch the data start over again from server. For me, I want to maintain the success items and not to reload them again. Can you please give suggestion for me, how can I solve this.

**Comment by tintnaingwinn** [comment]
I suggest you use [Hydrated Bloc](https://github.com/felangel/hydrated_bloc)

**Comment by felangel** [comment]
Hi @yetunnaing18121996 👋 
Thanks for opening an issue!

You can either lift your blocs up higher (provide them above the BottomNavigationBar) so that their state is maintained throughout the lifecycle of the app or as @tintnaingwinn mentioned, you can use hydrated_bloc if you'd like to cache the state of the blocs and have it persist even across app launches.

Hope that helps 👍
