### ISSUE TITLE
Question regarding Dependency Injection

### ISSUE THREAD

**Issue by jaydangar** [felangel/bloc#1327]
**This is not a bug, but a question.**

Do we need to use Dependency Injection, If I am using flutter_bloc,? I am asking this silly question, because I am a beginner in flutter and used flutter_bloc extensively. I have seen people using get_it, mockito and various dependency injection tools in order to make apps modular. Do you think flutter_bloc is modular enough that we still need to use DI packages?

**Comment by felangel** [comment]
Hi @jaydangar 👋
Thanks for opening an issue!

flutter_bloc exposes BlocProvider and RepositoryProvider which use provider internally for dependency injection. You shouldn’t “need” to use other packages like get_it but if you are comfortable using service locators instead of inherited widget then you can opt to pull in an external dependency like get_it. In any case, mockito is still really useful for mocking your dependencies during tests and works with BlocProvider/RepositoryProvider as well as other solutions 👍

Hope that helps!

Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 🙂
