### ISSUE TITLE
[Request] Bloc Library Udemy Course

### ISSUE THREAD

**Issue by leenorshn** [felangel/bloc#1333]
Can you please make a course on udemy for helping peoples to user in more ways your librairy philosophy in thier apps? it can help more. you can take more cases as possible to help peoples integrate flutter_bloc and bloc in thier apps. from app 's state, auth, list load and sorting, likes or views systems, input falidations, steps, graphql , rest api, grpc, testing, logging and match more ....
 we can paye you for your course because you will help us many more. please help us any more. thanks a lot for what you done

**Comment by felangel** [comment]
Hi @leenorshn 👋 
Thanks for opening an issue!

I'm not sure what making a udemy course entails and I worry it will be extremely time consuming when there are many videos that cover the topic already.

Some great videos to take a look at are:

- [Bloc Library: Basics and Beyond 🚀](https://youtu.be/knMvKPKBzGE) - Talk given at [Flutter Europe](https://fluttereurope.dev) about the basics of the bloc library, by [Felix Angelov](https://github.com/felangel).
- [Flutter Bloc Library Tutorial](https://www.youtube.com/watch?v=hTExlt1nJZI) - Introduction to the Bloc Library, by [Reso Coder](https://resocoder.com).
- [Flutter Youtube Search](https://www.youtube.com/watch?v=BJY8nuYUM7M) - How to build a Youtube Search app which interacts with an API using the bloc and flutter_bloc packages, by [Reso Coder](https://resocoder.com).
- [Flutter Bloc - AUTOMATIC LOOKUP - v0.20 (and Up), Updated Tutorial](https://www.youtube.com/watch?v=_vOpPuVfmiU) - Updated Tutorial on the Flutter Bloc Package, by [Reso Coder](https://resocoder.com).
- [Dynamic Theming with flutter_bloc](https://www.youtube.com/watch?v=YYbhkg-W8Mg) - Tutorial on how to use the flutter_bloc package to implement dynamic theming, by [Reso Coder](https://resocoder.com).
- [Persist Bloc State in Flutter](https://www.youtube.com/watch?v=vSOpZd_FFEY) - Tutorial on how to use the hydrated_bloc package to automatically persist app state, by [Reso Coder](https://resocoder.com).
- [State Management Foundation](https://www.youtube.com/watch?v=S2KmxzgsTwk&t=731s) - Introduction to state management using the flutter_bloc package, by [Techie Blossom](https://techieblossom.com).
- [Flutter Football Player Search](https://www.youtube.com/watch?v=S2KmxzgsTwk) - How to build a Football Player Search app which interacts with an API using the bloc and flutter_bloc packages, by [Techie Blossom](https://techieblossom.com).
- [Learning the Flutter Bloc Package](https://www.youtube.com/watch?v=eAiCPl3yk9A&t=1s) - Learning the flutter_bloc package live, by [Robert Brunhage](https://www.youtube.com/channel/UCSLIg5O0JiYO1i2nD4RclaQ)
- [Bloc Test Tutorial](https://www.youtube.com/watch?v=S6jFBiiP0Mc) - Tutorial on how to unit test blocs using the bloc_test package, by [Reso Coder](https://resocoder.com).

Please upvote the issue if you would like me to produce video content as well as comment explaining which topics would be most beneficial 👍

**Comment by mikededo** [comment]
Hey @leenorshn!

**Comment by Gh05ts** [comment]
@mikededo Hi since you are someone who just learned it recently I'm hoping you can help me with this query it is a slightly long question but it will help me immensely because I've been stuck with progress for a while now.

In our app we have a authentication bloc, then we have a ```LoginBloc``` which gets the ```AuthBloc``` through provider and now I'm trying to implement a forgot password function in log in, for that I'm making another bloc ```FogotPasswordBloc```.

The previous work was not done by me so I'm having some confusion about changing blocs and states between pages, so here are my questions:

### How are you handling navigation with blocs?

For me I tried to have a normal flat button that is outside of bloc builder that uses 
```                  
Navigator.push(context, MaterialPageRoute(builder: (context) =>ResetPasswordScreen(state.username)));
```

Now the issue with this is that the LoginBloc is still the active bloc and my forgot password bloc is not initialized?

On forgot password page I have a blocBuilder with bloc as ForgotPasswordBloc, but the app is still logging the messages from my LoginBloc.

So my question is how do I go from one page to another and change my current bloc to one bloc to another while doing so?


Will I have to make use of BlocListener with one state changing route? and How do I initialize the next bloc in doing so?

**Comment by mikededo** [comment]
Could you please share a repo or an example so it is easier for me to take a look?

**Comment by Gh05ts** [comment]
Hi Mike thanks for the quick reply appreciate it, I can't share the repo directly it's not my work, I just work on it (NDA), but I can try to explain to you what I'm trying to achieve, if you can explain in words that could be enough, or in case you have some personal work that you can share, I can try to write a small code to try to help explain in case you have some confusion.

We have an ```authBloc``` which is basically helps with keeping the user logged in or out, so in the main.dart we have something like this

```
class _MyAppState extends State<MyApp> {
  Widget build(context) {
    return BlocProvider<authBloc>(
      create: (context) => authBloc,
      child: MaterialApp(
        home: BlocListener(
          bloc: authBloc,
          listener (context, state) {
            if(state is a)
              return A();
            else if(state is b)
               return B();
}
```

Now the part that is confusing me is that one of those return pages is a loginPage(), now on this page how should I go to the forgot password page?

Is it better to repeat this patter down there?

1)
For example instead of loginPage() I should send to loginPageController(), which would be something like this:
```
class _LoginControllerState extends State<LoginController> {
  Widget build(context) {
    return BlocProvider<LoginControllerBloc>(
      create: (context) => LoginControllerBloc,
      child: MaterialApp(
        home: BlocListener<LoginControllerBloc, LoginControllerState>(
          bloc: LoginControllerBloc,
          listener (context, state) {
            if(state is a)
              return LoginPage();
            else if(state is b)
               return forgotPasswordEnterDetailsPage();
            else if(state is c)
               return forgotPasswordEnterOTPPage();
        }
    }
}
```

and repeat this BlocProvider nesting strategy everytime I need to group different pages which fall under one category?
and each page having their own respective bloc to handle multiple events and when I need to move to the next page I will add an event to the LoginControllerBloc which I can get because it's provided. Is there any alternative approach that is better? I can think of one but I'm not sure if it's better.

Or should I do something like this going straight to LoginPage()

2)
```
class _LoginPageState extends State<LoginPage> {
  Widget builld(context) {
     BlocListener<LoginBloc, LoginState> {
        listener: (context, state) {
             if(state is NextPage)
               Navigator.push(context, MaterialRoute(builder: (context) => ForgotPasswordScreen()));
           }
         child: layout of the page and a button that will yield NextPageState.
      }
   }
}

```

I think first might be the better approach but I'm not entirely sure and I can't seem to find any good resource to help me with dealing with navigation better example by @felangel is very simple and I'm not able to understand these kind of situations from it.

**Comment by mikededo** [comment]
The first one looks like a good alternative. However, if you have inputs in the `LoginScreen`, you will have to find a way (if you want, and I would recommend it - for user experience) to keep the state of them.  
The user writes the email & password and it is declined. Goes to the recovery (or whatever) screen to get the password. When it gets back to the other page, they would still have the email in the input, without having to type it again.  
As I say, this is just to improve user experience and avoid making the user repeat themselves!

**Comment by felangel** [comment]
There’s a great bloc course on udemy at https://www.udemy.com/course/bloc-from-zero-to-hero/ 🎉
