### ISSUE TITLE
Google places / Address autocomplete Bloc

### ISSUE THREAD

**Issue by edgebasis** [felangel/bloc#1335]
This is not a bug nor an issue..
I am trying to see if anyone has done a bloc pattern application for a Google maps autocomplete addresses or not.
I could not find any examples on the web.
If you any please let me know. That would help.

Thanks

**Comment by felangel** [comment]
Hi @edgebasis 👋 
Thanks for opening an issue!

I don't have any of my own examples but is there something in particular that you are having difficulty with? I'm happy to help if you have a specific question or sample app that isn't working properly 👍

**Comment by edgebasis** [comment]
Hi  @felangel
I dont have any specific code right now. I wanted to integrate the Google
Address Autocomplete api  with my Flutter app and was wondering do I need
to use bloc since I am calling a google api to list the list of all
addresses while the use types in an address in. Any examples for calling
any google apis using a Flutter Bloc pattern might help me visualize an
architecture for this application.

Thanks

**Comment by felangel** [comment]
@edgebasis I would recommend checking out the [github search example](https://github.com/felangel/bloc/tree/master/examples/github_search). You can refer to the [GithubSearchBloc](https://github.com/felangel/bloc/blob/master/examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart) in particular. It should be fairly similar only instead of using the [GithubRepository](https://github.com/felangel/bloc/blob/master/examples/github_search/common_github_search/lib/src/github_repository.dart) you'd probably want a `PlacesSearchRepository` and instead of a [GithubClient](https://github.com/felangel/bloc/blob/master/examples/github_search/common_github_search/lib/src/github_client.dart) you'd probably want a `google_places_api_client`.

Let me know if that helps 👍

**Comment by edgebasis** [comment]
Thanks @felangel ..
I can see a road map now .. I will try to post my solution as soon as I am
done with it.

Thanks again..

**Comment by felangel** [comment]
Awesome! Closing this for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍
