### ISSUE TITLE
Question: How do I combine Provider and Bloc

### ISSUE THREAD

**Issue by arashbi** [felangel/bloc#1336]
I was wondering what is the best way to combine `Provider` to `Bloc`. For example:

Let's say I have a service class that I use in my bloc to fetch a list of entities. Now Ideally I want to have a single instance of the service and get it from inside bloc, and use it. 

I can have a provider of that, as upper widget and use BlocBuilder as child widget, but it feels a little clumsy. Wondering what is the preferred way of solving this issue. 

New version of provider has nice things like multiprovider and stuff that feels a bit better than delegate system that we have here.

That all said, I am pretty new to Dart, so this is merely a question.

**Comment by felangel** [comment]
Hi @arashbi 👋 
Thanks for opening an issue!

The [flutter_bloc](https://pub.dev/packages/flutter_bloc) package uses `provider` internally and exposes `BlocProvider`, `MultiBlocProvider`, `RepositoryProvider`, and `MultiRepositoryProvider` widgets which enable you to easily provide blocs and repositories throughout the widget tree.

In general, I would recommend providing blocs and repositories at the lowest common ancestor in the widget tree of all widgets that need access to them. In many cases, repositories end up being needed globally so you might end up providing them using `MultiRepositoryProvider` above your `MaterialApp` like:

```dart
return MultiRepositoryProvider(
  providers: [
    RepositoryProvider(create: (context) => RepositoryA()),
    RepositoryProvider(create: (context) => RepositoryB()),
  ],
  child: MaterialApp(...),
)
```

Then later in the widget tree you might need to provide a bloc which depends on a repository like:

```dart
return BlocProvider(
  create: (context) => BlocA(context.repository<RepositoryA>()),
  child: WidgetA(),
)
```

And `WidgetA` can use a `BlocBuilder` or `BlocListener` to consume/react to the state of `BlocA` like:

```dart
return BlocBuilder<BlocA, StateA>(
  builder: (context, state) { ... }
);
```

Hope that helps! 👍

**Comment by JohnGalt1717** [comment]
There is a common scenario where you end up repeating yourself a lot:

Let's say we have a page, and we have a bloc for the page itself. It is the lowest common ancestor and everything else goes from there.

Right now we have to do the following:

BlocProvider(create: (context) => new Bloc(), child: BuildBuilder<Type, State>( builder: (context, state) {})

It would be much nicer in answer to the question originally posed, if there was a BlocProvider option to pass a builder too and had a generic type for the state so that we could just write BlocProvider(create: (context) => new Bloc(), builder: (context, state) {}); in one line.

**Comment by felangel** [comment]
@JohnGalt1717 this is actually not recommended because by creating and consuming the bloc in the same widget you make it impossible to mock the bloc for testing purposes. See https://github.com/felangel/bloc/issues/1449#issuecomment-657262957 for an example 👍

**Comment by JohnGalt1717** [comment]
So what's the recommended pattern for pages against the Routing system? Generate the provider in the router and pass the provider with the child being the page?

**Comment by felangel** [comment]
Yeah that generally works well. If you're using a nested `Navigator` then you can also just wrap the Navigator in one or more providers.

**Comment by JohnGalt1717** [comment]
Is there an example of this?

**Comment by felangel** [comment]
I'm currently in the process of redoing all of the examples but you can check out the [in progress login example](https://github.com/felangel/bloc/blob/example/new-flutter-login/examples/flutter_login/lib/app.dart).

**Comment by arashbi** [comment]
Sorry for the late reply. The only reason I am following up here is that this library looks "the solution" for an age old problem. I really like this library, and as I am just a novice Dart dev with architecture background doing mostly Java. I wanted to give my 2cents. Please don't take it the wrong way. That said ...


I understand all these, well sort of. But I am still a bit fuzzy about the construction of the blocs. 

My issue is two fold, one is purely conceptual: `Provider` package gives a very nice way for building and injecting objects, cannot we simply use it here? With the principal of "do one thing, and do it right", it seems to be a huge win. 

The second is a more specific problem of how to create other classes and add them to blocs - which was my original question.

I understood the `Repository` providers. But not all my services are `Repository` per se. Of course I can simply pretend that they are repositories, and use this pattern and it works perfectly well, yet again it feels just distasteful. 

To connect it to my purely conceptual model, again I should ask why we are concerned with `Repository` at all here?  What is the scope of the Bloc library, where does it starts, and where does it ends?

**Comment by Shreyans13** [comment]
Little two late here but had one question about providers and bloc. I was wondering if I should use both providers and bloc together. For example I can create one AuthBloc which handles all logic for Authentication 

```
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  AuthBloc(this._authRepository) : super(const UnAuthorized()) {
    on<AuthTriggerOTP>(handlerAuthTriggerOTP);
    on<AuthVerifyOTP>(handlerAuthVerifyOTP);
  }
  }
  ```

Can I use provider to solve prop-drilling in UI Components in the same auth screen. I will use providers for my leaf based components which will be updating some value passed from the parent component. Using Bloc looks like an issue here because output from one component might affect my other component on the same screen.(This is more of how components interact with each other). I am thinking to use bloc to separate out my main business logic (authentication bloc, user bloc, FeatureA bloc.. etc) and provider to solve prop drilling.

Is there any other way we can solve prop-drilling via bloc or providers or something else which is recommended for big projects. I might be wrong to use provider to solve prop drilling all together. 

Happy developing !!
