### ISSUE TITLE
Modal bottom sheet and BlocProvider not found

### ISSUE THREAD

**Issue by gerryau** [felangel/bloc#1354]
**Describe the bug**
The following error is shown when the below code is ran: 
BlocProvider.of() called with a context that does not contain a Bloc.

**To replicate**

          BlocProvider(
              create: (context) => getIt<TheBloc>()
              child: BlocBuilder<TheBloc, TheState>(
              build: (context, state) =>
              MaterialButton(
                onPressed: () => _showModal(context),
                child: const Text('SHOW BLOC MODAL'),
              ),

```
void _showModal(BuildContext context) {
  showModalBottomSheet<void>(
    context: context,
    builder: (_) {
          return MaterialButton(
               onPressed() {
                       context.bloc<TheBloc>().add(
                         TheEvent.someEvent(),
                       );
               }
              child: Text('Press button to add event to bloc')
          );
    },
  );
}
```

**Comment by felangel** [comment]
Hi @gerryau 👋 
Thanks for opening an issue!

You need to wrap the modal in a `BlocProvider.value` in order to make the bloc available to the modal content. The same applies when pushing a new route.

You can check out the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=anonymous-route-access) for more details 👍
