### ISSUE TITLE
Doubt about Equatable

### ISSUE THREAD

**Issue by basketball-ico** [felangel/bloc#142]
Hello 😁

1. In which cases I don't need to `Extends` `Equatable` (or override the == operator as well as hashCode)?
I use ever, but i don't know if i did it correct o simply i am adding more code :(

2. If I have a `State` that Extends `Equatable` and this state have an other class like property, I need to extend Equatable also in this property?
Thanks
```Dart
class State extends Equatable{
  final Car car
  State(this.car): super([car]);
}

class Car{
  String type;
  String model;
  String color;
}
```

Thanks 🤗

**Comment by felangel** [comment]
Hey @basketball-ico 👋 
1. You never **need** to extend `Equatable`. If you want to optimize your application to avoid rebuilding if the state doesn't change you can extend `Equatable` but otherwise it shouldn't really have an impact.
2. Yes in order to accurately compare different instances of `State` you'd need to either have `Car` extend `Equatable` or have manually override `==` and `hashCode`.

Hope that helps! 👍

**Comment by basketball-ico** [comment]
Thanks I got it :D.

But i can't understand why you extends `Equatable` in the`Events` of your examples.
I see that you compare the states `if (currentState == nextState) return;` but not the events.

Thanks

**Comment by felangel** [comment]
@basketball-ico great question! 💯 

I extend `Equatable` in events as well because it makes it possible to do things like override `transform` in the bloc and manipulate the stream of events (using operators like debounce, distinct, etc..). Otherwise everything is technically a new/different `Event`. 

Does that help?

**Comment by basketball-ico** [comment]
Yeah, so for confirm :D, if I not need to override `transform`, not are any reason for extends `Equatable` in events. I am right?

Thanks ;D

**Comment by felangel** [comment]
@basketball-ico that's correct 👍
