### ISSUE TITLE
"Timer" tutorial doesn't compile due to "currentState" usage

### ISSUE THREAD

**Issue by MasterGroosha** [felangel/bloc#1445]
I was trying to compile Timer tutorial, however I got error: "undefined name currentState".
Here's the code:

```dart
  Stream<TimerState> _mapTimerPausedToState(TimerPaused pause) async* {
    final state = currentState;
    if (state is TimerRunInProgress) {
      _tickerSubscription?.pause();
      yield TimerRunPause(state.duration);
    }
  }

  Stream<TimerState> _mapTimerResumedToState(TimerResumed resume) async* {
    final state = currentState;
    if (state is TimerRunPause) {
      _tickerSubscription?.resume();
      yield TimerRunInProgress(state.duration);
    }
  }
```

After reading #985 it turned out that I had to remove `final state = currentState;` lines from both functions. 
Please fix your docs.

**To Reproduce**
1. Go to https://bloclibrary.dev/#/fluttertimertutorial
2. Try to compile code from tutorial

**Expected behavior**
Code works fine

**Actual behaviour**
Code doesn't compile due to "currentState" usage

**Comment by felangel** [comment]
Hi @MasterGroosha 👋 
Thanks for opening an issue!

All of the docs/tutorials are in the process of being rewritten for the v6.0.0 and will be accurate. In the meantime, please refer to the [example](https://github.com/felangel/bloc/tree/master/examples/flutter_timer) since that is guaranteed to be up-to-date at all times. Sorry for the inconvenience and thanks again for reporting this 👍
