### ISSUE TITLE
Incongruences in bloc_test 7.0.0-dev.1 skip README an behaviour

### ISSUE THREAD

**Issue by Supercaly** [felangel/bloc#1473]
I've taken a look a look at the new feature branch of bloc with the merged cubit (feat/export-cubit-class-from-bloc); in particular to bloc_test and I've seen an incongruence in the skip documentation: under **Unit Test with blocTest** first it's said that skip defaults to 1, then in the example it's said its default value is 0. In code, it defaults to 0.

I'm using bloc_test 7.0.0-dev.1 but the test is not considering the initial state of my `Cubit` even if I set skip to 0.

My test:
```dart
blocTest("emits loading as initial state",
   build: () async => HomeCubit.private(mockRepo),
   skip: 0,
   expect: [isA<HomeStateLoading>()],
);
```
In the cubit constructor:
```dart
@visibleForTesting
HomeCubit.private(this._repository) : super(HomeStateLoading());
```

The expected value for the test is an instance of `HomeStateLoading` but the actual value us `[ ]`

**Comment by felangel** [comment]
Hi @Supercaly 👋
Thanks for opening an issue!

I will update the README shortly but in the new version blocs and cubits won’t emit the current state upon subscribing. In order to test the initial state I would recommend a regular test like:

```dart
test("emits loading as initial state", () {
  expect(
    HomeCubit.private(...).state,
    isA<HomeStateLoading>(),
  );
});
```

Hope that helps and thanks again for bringing this up, I will make sure the docs are all up-to-date 👍
