### ISSUE TITLE
Boiler Plate remove for form validation

### ISSUE THREAD

**Issue by jaydangar** [felangel/bloc#1484]
As we all know, formz and flutter_bloc works great. there's an issue with that. We need to write alot of boilerplate code for that. Can we create an extension for that? Suppose I have many 10 fields I need to create Separate model classes such as email, phonenumber, name, firstname, lastname, address, etc. can we have any alternative solution to this problem, which reduced boilerplate?

**Comment by felangel** [comment]
Hi @jaydangar 👋
Thanks for opening an issue!

Can you describe a solution you were envisioning? I personally don’t think defining the models is boilerplate because that is where you define the custom validation rules. The models are also just a few lines of code and can be reused across multiple blocs and apps. All phone numbers will likely not have the same validation logic for example and this also has nothing to do with bloc. Let me know what you think 👍

**Comment by jaydangar** [comment]
@felangel so Creating the validation is one time process and can be reused as many times as - we can. I thought we need to create it everytime for every screen. That helps. Thanks for the response.

**Comment by felangel** [comment]
Yup the models are completely reusable haha.
Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍
