### ISSUE TITLE
Make it possible to get bloc using Bloc.of

### ISSUE THREAD

**Issue by Jomik** [felangel/bloc#1494]
**Is your feature request related to a problem? Please describe.**
I always thought there was a bit of an inconsistency with using `BlocProvider.of<MyBloc>(context)` to get a Bloc, since it semantically references `BlocProvider`.
I was looking at `Theme.of` and `Navigator.of`, but I realize now that they do not return a `Theme`/`Navigator`, they return data classes.

**Describe the solution you'd like**
A static `Bloc.of<MyBloc>(context)` would be nice, it is shorter to write and my head makes a better connection with the method path/name and the return type.
Obviously this has to reside in flutter_bloc, so I do not know if it is possible to do this cleanly..

**Describe alternatives you've considered**
We also have `context.bloc<MyBloc>()`, but I do not see that used anywhere for similar things, i.e. `Theme` or `Navigator`.

**Comment by felangel** [comment]
Hi @Jomik 👋 
Thanks for opening an issue!

The main issue with doing this is the `Bloc` class itself is pure Dart and has no Flutter dependency so the static `of` would have to be defined in the `flutter_bloc` package. We can create an extension in the `flutter_bloc` package to expose an `of(BuildContext)` but static extension methods can only be accessed via the extension name so we would need to do something like:

```dart
extension BlocX on Bloc {
  static C of<C extends Cubit<Object>>(BuildContext context) =>
      context.bloc<C>();
}
```

Which would mean the usage would look like:

```dart
final bloc = BlocX.of<MyBloc>(context);
```

I personally am leaning toward just leaving it like:

```dart
context.bloc<MyBloc>();
```

Since it's more concise and also doesn't involve referencing the extension by name. Thoughts?

**Comment by Jomik** [comment]
Yeah, no. No good. I have had no gripes since I discovered `context.bloc` 👍👍
