### ISSUE TITLE
BlocObserver Duplicate Call

### ISSUE THREAD

**Issue by Peng-Qian** [felangel/bloc#1537]
Hi @felangel ,

I found if we override onTransition and onChange in BlocObserver(If we apply both cubit and bloc in the app), it will call onTransition and then call onChange. In my case, the console will print transition info and then print change info, which is highly duplicate.

I understood bloc now is built on the cubit, so the onChange should be called, but is it possible when the onTransition is called, the onChange will not be called again?

**Comment by felangel** [comment]
Hi @Peng-Qian 👋 
Thanks for opening an issue!

This is intentional because it would be very strange for onChange to not function for blocs and it is also used by other packages like `hydrated_bloc` to ensure compatibility between the two. If you don't want onChange to fire for blocs you can just update your `BlocObserver`:

```dart
class MyBlocObserver extends BlocObserver {
  void onChange(Cubit cubit, Change change) {
    if (cubit is! Bloc) print(change);
    super.onChange(cubit, change);
  }
}
```

Hope that helps 👍

**Comment by Peng-Qian** [comment]
Many thx!
