### ISSUE TITLE
Listview builer one Provider for each item

### ISSUE THREAD

**Issue by fedeakd** [felangel/bloc#1564]
Hi, my query is that I have to do a listview.builer and for that each item has different states
And I imagine making a provaider pad for each item
But the listview buider rebuilds the item for me every time it scrolls

am I doing things the right way or is there a better idea?

![image](https://user-images.githubusercontent.com/11893306/89132272-67abc400-d4e9-11ea-9549-e15707259ac2.png)

**Comment by felangel** [comment]
Hi @fedeakd 👋 
Thanks for opening an issue!

That's totally fine and `ListView.builder` is optimized to only build the items which are visible so I wouldn't try to prematurely optimize unless you are experiencing performance issue.

Hope that helps 👍

**Comment by fedeakd** [comment]
thanks to you for responding, but my problem is that in this way I lose my state
How would you make each item have an individual status?

**Comment by kavienanj** [comment]
I think you want each news card to rebuild on some state emitted rather than the whole listview builder right. For that you would need seperate instances of your Bloc(to the number of news articles) and it would open too many listeners, and it will drastically affect your performance. As felix said keep this as before.
