### ISSUE TITLE
UI not updating after state change. 

### ISSUE THREAD

**Issue by JulianSwales** [felangel/bloc#1590]
First of all let me thank you for helping.. Your pointers on my first problem allowed me to get it working.. 
I now have a more complicated UI state problem.. A working app can be found here: 

https://github.com/JulianSwales/bloctest

This is a combination of the https://github.com/felangel/bloc/tree/master/examples/flutter_dynamic_form and the https://github.com/kkogut95/flutter_bloc_lyrics

I have a screen with a drop down to select a list of data.. For that I used the dynamic form example to get it to work. That all works.. When that page is presented I have the option to Add a record to the list, which takes me to a second page, where the add works, but on return to the first page, no update happens.. 

I can see the state changing as I expect, but I'm not understanding something such that the UI updates. I'm pretty sure it has something to do with managing the three pieces of data. What am I doing wrong? 
Thanks.

**Comment by RollyPeres** [comment]
Hi @JulianSwales 👋

Your problem is happening because you're working with two different instances of `JobSiteBloc`.
- https://github.com/JulianSwales/bloctest/blob/1d2ca2ee9f7a28efc3c605a25ea3430b538756fe/lib/main.dart#L31
- https://github.com/JulianSwales/bloctest/blob/1d2ca2ee9f7a28efc3c605a25ea3430b538756fe/lib/screens/jobsite_notes_screen.dart#L25

You should only deal with a single instance of your bloc.

Hope that gets you going in the right direction. 👍
