### ISSUE TITLE
Add a child field for BlocBuilder

### ISSUE THREAD

**Issue by SwissCheese5** [felangel/bloc#1596]
**Is your feature request related to a problem? Please describe.**
If you have a massive widget tree under a BlocBuilder and only the first (or second or third or however you want to utilize the builder) need the state update, but the REST of the tree does NOT need to be rebuilt, then you have a performance problem where a massive widget tree is rebuilt for the sake of a limited scope the bloc needs to access, because it rebuilds the entire widget tree under the builder for the sake of one widget.

**Describe the solution you'd like**
From flutter docs:
```
The third argument is child, which is there for optimization. If you have a large widget subtree under your Consumer that doesn’t change when the model changes, you can construct it once and get it through the builder.
```

This is an essential feature for any builder, I'm surprised Bloc doesn't do this. I think Provider does this as well but I'm not sure.

**Additional context**

https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple#consumer

**Comment by felangel** [comment]
Hi @SwissCheese5 👋 
Thanks for opening an issue!

Can you please provide a sample use-case where you feel this becomes necessary? Thanks!

**Comment by SwissCheese5** [comment]
Here's a limited example:

```dart
BlocBuilder<AuthBloc, AuthState>(builder: (context, state) {
                return FloatingActionButton(
                    backgroundColor: state is NetworkStateNotConnected
                        ? Colors.red
                        : Theme.of(context).accentColor,
                    child: AnimatedSwitcher(
                        transitionBuilder: (child, animation) => ScaleTransition(
                            child: child,
                            scale: CurvedAnimation(parent: animation, curve: Curves.easeInOutBack)),
                        duration: const Duration(milliseconds: 500),
                        child: state is NetworkStateNotConnected
                            ? Icon(Icons.offline_bolt,
                                key: ValueKey(2), color: Theme.of(context).backgroundColor)
                            : (navigationController.index == 1
                                ? Icon(
                                    Icons.add,
                                    key: ValueKey('0'),
                                    color: Theme.of(context).backgroundColor,
                                  )
                                : Icon(
                                    Icons.create_new_folder,
                                    key: ValueKey('1'),
                                    color: Theme.of(context).backgroundColor,
                                  ))),
                 );
              }),
```
I've omitted onPressed for simplicity's sake
That code can be made into this to avoid rebuilding 3 icon widgets. again, this is a very limited example, I have significantly larger examples that I can't use because my project is in the middle of a massive rebuild

```dart
BlocBuilder<AuthBloc, AuthState>(builder: (context, state, child) {
                return FloatingActionButton(
                    backgroundColor: state is NetworkStateNotConnected
                        ? Colors.red
                        : Theme.of(context).accentColor,
                    child: AnimatedSwitcher(
                        transitionBuilder: (child, animation) => ScaleTransition(
                            child: child,
                            scale: CurvedAnimation(parent: animation, curve: Curves.easeInOutBack)),
                        duration: const Duration(milliseconds: 500),
                        child: state is NetworkStateNotConnected
                            ? Icon(Icons.offline_bolt,
                                key: ValueKey(2), color: Theme.of(context).backgroundColor)
                            : child),
                 );
              },
        child: navigationController.index == 1
            ? Icon(
          Icons.add,
          key: ValueKey('0'),
          color: Theme.of(context).backgroundColor,
        )
            : Icon(
          Icons.create_new_folder,
          key: ValueKey('1'),
          color: Theme.of(context).backgroundColor,
        )),
```

**Comment by SwissCheese5** [comment]
Here's a more extreme example but it's very messy and incomplete. (red lines everywhere), but it gets the point across.


https://gist.github.com/83ff84f7940a611643213e2cbbd58333

**Comment by felangel** [comment]
@SwissCheese5 thanks for sharing an example but I'm still not convinced haha. Can you please provide a more realistic example where you would actually need to use child due to performance issues?

I could only find two places in Flutter where this pattern is used:
  - `TweenAnimationBuilder`
  - `ValueListenableBuilder`

I'm a bit skeptical of the value that this feature brings as it's going to force every developer to add `, child` to their `builder` which is pretty inconvenient especially if it isn't used majority of the time.

```dart
BlocBuilder<MyBloc, MyState>(
  builder: (context, state, child) {
    // return widget
  },
)
```

Would love to hear other people's thoughts 😄

**Comment by RollyPeres** [comment]
There are situations when caching the child would result in great performance improvements, but I don't think `BlocBuilder` needs this. This pattern is extensively used and recommended when dealing with animations, since you don't wanna rebuild your sub-tree on each animation frame. Widgets like `AnimatedBuilder` makes great use of this approach. 

As for `BlocBuilder`, it doesn't drive things like animations where a lot of rebuilds are performed, but instead builds UI based on a state containing some data(which is rarely changing at a fast pace).

If you'd to implement this feature it would only result in having people deal with an extra annoying parameter which is rarely ever gonna be used, not to mention having to refactor all existing code to include it.

If you really want to optimize performance in regards to bloc then just use multiple `BlocBuilder`s as low as possible in your widget tree and make use of `buildWhen` to further control when they rebuild.

**Comment by felangel** [comment]
Going to close this for now since I'm still not convinced that the benefit of adding a `child` outweighs the cons described above. Feel free to comment with additional thoughts/examples and I'm happy to continue the discussion 👍

**Comment by behnamsattar** [comment]
Depending on how large your sub-tree is, and how frequent your state changes are, this could be very valuable.

As to the downside mentioned above reading:
"it's going to force every developer to add, child to their builder which is pretty inconvenient (not to mention confusing) especially if it isn't used majority of the time.",
I would say the `child` could be an optional nullable value so adding it doesn't make a breaking change.
 
I'm creating my own bloc builder variation to do this currently, but it would be a nice addition to the library.

**Comment by takenoto** [comment]
> Depending on how large your sub-tree is, and how frequent your state changes are, this could be very valuable.
> 
> As to the downside mentioned above reading: "it's going to force every developer to add, child to their builder which is pretty inconvenient (not to mention confusing) especially if it isn't used majority of the time.", I would say the `child` could be an optional nullable value so adding it doesn't make a breaking change.
> 
> I'm creating my own bloc builder variation to do this currently, but it would be a nice addition to the library.

I think he meant old coldbases would need to add a "child" param to the builder so it could become a big problem in projects with a lot of blocs.

Anyways, my 2 cents, a child param wold be nice. I have a usecase where the parent widget needs to be updated but the child don't:
- I'm using *flutter_maps* and updating a marker according to the user location to show him on the map.
- For this, I need to update MarkerLayer everytime his position changes in order to update the internal Marker, since the "markers" param only accepts Marker not Widget, I can't put a bloc builder there.
- My marker has a longitude and latitude params that will be updated everytime the state changes.
- The internal child (an icon) will be rebuild again and again

I managed to solve this by wrapping my code in an external widget and using "const". Another way would be "saving" the widget reference before the BlocBuilder (in the main widget build method) and then passing it down.

Example:
```dart
class UserDeviceLocationMapMarker extends StatelessWidget {
  const UserDeviceLocationMapMarker({super.key});

  @override
  Widget build(BuildContext context) {
    final appColors = context.select(
      (ThemeCubit cubit) => cubit.state.getAppColors(context),
    );

    return BlocBuilder<DeviceLocationCubit, DeviceLocationState>(
      buildWhen: (previous, current) => previous.position != current.position,
      builder: (context, state) {
        if (state.position != null) {
          return MarkerLayer(
            key: userDeviceLocationMarkerLayerKey,
            rotate: true,
            markers: [
              Marker(
                point: LatLng(
                  state.position!.latitude,
                  state.position!.longitude,
                ),
                child: Container(
                  alignment: .center,
                  width:
                      Dimensions.iconSizeNormal +
                      Dimensions.horizontalSpacingClose,
                  height:
                      Dimensions.iconSizeNormal +
                      Dimensions.horizontalSpacingClose,
                  decoration: BoxDecoration(
                    color: appColors.surface1,
                    border: Border.all(
                      color: appColors.primary,
                      width: Dimensions.borderWidth,
                    ),
                    borderRadius: BorderRadius.circular(999),
                  ),
                  child: Icon(
                    Icons.person,
                    color: appColors.secondary,
                    size: Dimensions.iconSizeNormal,
                  ),
                ),
              ),
            ],
          );
        }
        return const SizedBox.shrink();
      },
    );
  }
}
```

Summary 
- I needed to update LatLng inside "Marker".
- For this I needed to wrap the whole MarkLayer in a BlocBuilder
- The internal widget can't be reused directly, it needs a workaround.
