### ISSUE TITLE
Keep state during runtime

### ISSUE THREAD

**Issue by wheel1992** [felangel/bloc#160]
Hi @felangel, this library is great! However, I'm new to this dependency and still learning how to implement it. Along the way, I had difficulty to maintain my state during the application runtime. For example, if screen A holds a person details, how can screen B update the state of person details without losing it?

**Comment by felangel** [comment]
Hi @wheel1992 👋 

Thanks for the positive feedback! I really appreciate it 🙏

Regarding your question, you would probably want to create a UserBloc which holds a given users model and you can then access it from anywhere using BlocProvider. To modify the user you would probably want to dispatch events which your bloc would respond to. 

I highly recommend going through the [Todos Application Tutorial](https://felangel.github.io/bloc/#/fluttertodostutorial) because it is very similar to what you’re trying to achieve.

Hope that helps! 👍

**Comment by wheel1992** [comment]
@felangel Thank you so much! I'll follow this example and if I have any more questions, can I post here?

**Comment by felangel** [comment]
@wheel1992 no problem and of course! Please don’t hesitate to post any follow up questions you have 👍

I’m more than happy to help 😄
