### ISSUE TITLE
In Flutter_Github_Search example how to hold context of previous page like builtin Showsearch(context, serachDelegate)

### ISSUE THREAD

**Issue by rravithejareddy** [felangel/bloc#1646]
I am planning to include whole serach in my app, but I want to navigate separate page like showSearch in flutter, how to use use flutter_github_search example. Can I navigate to SerachForm page?

[https://api.flutter.dev/flutter/material/showSearch.html](url)

If I use show showsearch with bloc pattern, something like this [https://medium.com/flutterpub/implementing-search-in-flutter-17dc5aa72018](url) will it be useful?

**Comment by felangel** [comment]
Hi @rravithejareddy 👋 
Thanks for opening an issue!

You can definitely use `showSearch` but you'll need to inject your bloc into the `SearchDelegate` since it won't have access via `BuildContext`.

Hope that helps and closing for now but feel free to comment if you have additional questions and I'm happy to continue the conversation 👍
