### ISSUE TITLE
Benefits of navigationkey in material app, and how to use in widget tree.

### ISSUE THREAD

**Issue by rravithejareddy** [felangel/bloc#1661]
In firebaselogin example you used <_navigatorkey.pushNamedAndRemoveUntil('/login', (Route<dynamic> route) => false);>
Suppose if I want to use navigationkey in homewidget tree do I need to use bloc. Or can I pass key over in constructors.

Instead if I use like this
<Navigator.of(context) .pushNamedAndRemoveUntil('/login', (Route<dynamic> route) => false);>

I don't understand why do we need Globalkey and navigationkey use over there.

What if I use navigationbloc example below
[https://dev.to/pedromassango/flutter-bloc-a-better-way-to-handle-navigation-4fig ]

**Comment by felangel** [comment]
Hi @rravithejareddy 👋 
Thanks for opening an issue!

The `NavigatorKey` should ideally stay inside the root app widget because it is only used to manipulate the top level Navigation stack (for authenticated/unauthenticated routes). If you wish to change the authentication state just add an event to the `AuthenticationBloc` -- you should not need to pass around the navigator key.

Hope that helps, closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
