### ISSUE TITLE
How to change complex state class in UI and send back to bloc as a event.

### ISSUE THREAD

**Issue by rravithejareddy** [felangel/bloc#1701]
Please see my sample app which exaplains my problem below
[https://github.com/rravithejareddy/flutter_mysample_app](https://github.com/rravithejareddy/flutter_mysample_app)

In app I have complex filter class (having lists as fields) which I am using as state and using at UI but how to add element to it using event. Since it's a class with final list it's not modifying, do I need to create set methods in filter class to add items in list and send as event. 

can you please edit or give me solution.

**Comment by mikededo** [comment]
Hello @rravithejareddy !

After lookin through your code, I've seen that you create all list as `const`. This implies that you will not be able to modify the list (it is not growable). In order to _protect it_, so to say, dart makes it a `UnmodifiableListView`. 

Instead of having all lists declared as `const` when initialised, 
```dart
const Filter.initial()
  : this(
    const <String>[],
    const <String>[],
    const <int>[],
    const <int>[],
);
```
try not making them `const`:
```dart
Filter.initial()
  : this(
    <String>[],
    <String>[],
    <int>[],
    <int>[],
  );
```

I will create a pull request to your repo! I hope I've been helpful! 😄

**Comment by rravithejareddy** [comment]
Thanks for reply, but in bloc we should not change the state directly, we should change through only events right.

**Comment by mikededo** [comment]
> Thanks for reply, but in bloc we should not change the state directly, we should change through only events right.

Yes, but I do not know how am I changing the _bloc state directly_ in this case. If you create constant lists, you will not be able to add nor remove items.

If you check the pull request I've made, you will see that when a filter button is pressed, then it adds an event to the bloc you have created and then the state is modified. 

Otherwise, I may not be understanding your problem.

**Comment by rravithejareddy** [comment]
If my filter is extended with Equatable (I want compare the filter changes as well for updating check boxes) below method I am passing the same state object to check_box_list

<
CheckBoxList(
              onSelected: (Filter filter) => {
                    BlocProvider.of<FilteredCropsBloc>(context)
                        .add(FilterUpdated(filter))
                  },
              filter: state.filter);
>

I am modifying state below method in check_box_list

< onChanged: (value) {
              if (value) {

                widget.filter.cropType.add(key);
               // widget.filter.cropName = cropName;
                widget.onSelected(widget.filter);
              }>

Sorry If I am thinking in wrong way

**Comment by mikededo** [comment]
I don't understand what this has to do with the `Filters.initial` constructor and removing the const errors.

When I forked your app, cloned and opened it, I tried to apply one of the three filters. When one was clicked, an execption was raised and it was due to the fact that you are making the lists const (`UnmodifiableListView`s). I understood that it was that your problem.

**Comment by rravithejareddy** [comment]
onemore problem related to this If you click oilandseeds filter, checkbox will not be checked because there is no crops in this type but I have to check the checkbox to user. it's not happening, it's because bloc is not rebuilding tree due to no state changes, only crops state is extended with Equatable that's why it's checking with only crops, I want to check with filter state as well for that I have extend filter class with Equatable.

**Comment by mikededo** [comment]
It keeps happening because you are trying to modify an `UnmodifiableListView`. As the name states, it can not be modified (the [api](https://api.dart.dev/stable/2.9.2/dart-collection/UnmodifiableListView-class.html) - I would recommend you reading it).  
It is also printed in the debug console of your editor (in my case I'm using VSCode). 

I'm creating a pull request with the problem solved, since it updates the state. I will give you the explanation there! 😄

**Comment by rravithejareddy** [comment]
Can make filter class extending with equatable and work as usual. I found hint from here
(Equatable properties should always be copied rather than modified. If an Equatable class contains a List or Map as properties, be sure to use List.from or Map.from respectively to ensure that equality is evaluated based on the values of the properties rather than the reference.)

**Comment by felangel** [comment]
Thanks so much for the support @mikededo 🙏 💯 

@rravithejareddy you can make `Filter` extend `Equatable` and you should be able to achieve the desired behavior as long as you are always returning new instances rather than modifying the same instance 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
