### ISSUE TITLE
What's the advantage of making Bloc state without subclasses?

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#1726]
I recently read the documentation again and I found that new examples are updated.

https://bloclibrary.dev/#/flutterfirebaselogintutorial?id=state

And I realized that the new implementation of the bloc state is a little different from the other in the past. Just like the above link,  the bloc state manages its state by its enum field. I'm wondering what's the advantage over the use of separated subclasses?

``` Dart
enum AuthenticationStatus { authenticated, unauthenticated, unknown }

class AuthenticationState extends Equatable {
  const AuthenticationState._({
    this.status = AuthenticationStatus.unknown,
    this.user = User.empty,
  });

  const AuthenticationState.unknown() : this._();

  const AuthenticationState.authenticated(User user)
      : this._(status: AuthenticationStatus.authenticated, user: user);

  const AuthenticationState.unauthenticated()
      : this._(status: AuthenticationStatus.unauthenticated);

  final AuthenticationStatus status;
  final User user;

  @override
  List<Object> get props => [status, user];
}
```

``` Dart
abstract class AuthenticationState extends Equatable {
  const AuthenticationState();

  @override
  List<Object> get props => [];
}

class Authenticated extends AuthenticationState {
  final User user;

  Authenticated(this.user);

  @override
  List<Object> get props => [user];
}

class Unauthenticated extends AuthenticationState {}

class Unknown extends AuthenticationState {}
```

**Comment by felangel** [comment]
Hey @jezsung 👋 
Thanks for opening an issue!

The main advantage is you don't need to perform type checks in order to access properties:

```dart
final user = context.bloc<AuthenticationBloc>().state.user;
```

With subclasses you'd need to check the type first like:

```dart
final state = context.bloc<AuthenticationBloc>().state;
final user = state is Authenticated ? state.user : null;
```

Another situation where a single class comes in handy is when your state needs to handle multiple properties at the same time. For example, if you still needed to have access to the previous user when an error occurred you would have access to both properties at the same time and could react to the error via an `AlertDialog` with `BlocListener` while still rendering the previous content behind the dialog with `BlocBuilder`.

With all that being said, it's safer (more strict) to use subclasses so there's definitely nothing wrong with it and it all comes down to the use-case and your preference 👍 

Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
