### ISSUE TITLE
Bloc plugin: allow to generate event, state and bloc in a single file

### ISSUE THREAD

**Issue by anticafe** [felangel/bloc#176]
**Is your feature request related to a problem? Please describe.**
When I choose `File > New > Bloc Generator > New Bloc`, 3 files *_event*, *_state* and *_bloc* are generated. However in some case I only have 1 event and 4 states, thus 3 separated files look so much.

**Describe the solution you'd like**
In `New Bloc` dialog, I wish there is an option to generate only single file instead.

**Describe alternatives you've considered**
If possible, we could have additional checkbox for such option in `New Bloc` dialog (see below image)

**Additional context**
![image](https://user-images.githubusercontent.com/340836/55132958-afcd1080-5156-11e9-9e4e-a47dee4a6a5e.png)

**Comment by felangel** [comment]
Hey @anticafe 👋 

I don’t think it’s a good idea to add this because we want the plugin to generate code that follows best practices like having public classes each defined in a separate file. I don’t think it’s too much because it’s consistent and developers will know exactly where to look when looking for an event definition or a state definition. Thoughts?

**Comment by felangel** [comment]
Closing this for now but feel free to comment with more questions/comments and we can continue the conversation. 👍
