### ISSUE TITLE
[Question] Project Structure

### ISSUE THREAD

**Issue by aliyazdi75** [felangel/bloc#1760]
Hi, Thanks for your amazing work.
I want to struct a new project and I read Bloc documentation again and in `Counter Tutorial` I found a new structure and I didn't get it, could you please explain this and why it's a good approach to struct feature-driven:

> The application uses a feature-driven directory structure. This project structure enables us to scale the project by having self-contained features. In this example we will only have a single feature (the counter itself) but in more complex applications we can have hundreds of different features.

And another thing is ambiguous to me, in `Login Tutorial` why repositories are separated from the library folder and we should point them in project `pubspec.yaml`, are we should behave them like external packages?

> ├── android
├── ios
├── lib
├── packages
│   └── authentication_repository
└── test

**Comment by felangel** [comment]
Hi @aliyazdi75 👋 
Thanks for opening an issue!

The benefit of organizing by feature is that as the codebase grows each feature is self-contained meaning you can add and remove features without disrupting other parts of the code. This becomes super important when you have larger teams which are each working on developer features in parallel. Also, a feature-driven approach makes it very easy to optimize things like ci because you can test features independently of each other.

Regarding the second question, the reason the repositories are separate packages is because the repository and data layers have nothing to do with the application layer and can be reused across multiple applications. You can read more about that in the [architecture section of the docs](https://bloclibrary.dev/#/architecture).

Hope that helps!

**Comment by aliyazdi75** [comment]
Thanks for your answer,
It's a good approach, but if we have some models and blocs that share between some features, is it correct to place them in a specific future? How do we treat these in a complicated application with network models?

**Comment by felangel** [comment]
Network models should not belong in the application and should instead be part of the networking/api client package. You can check out [fluttersaurus](https://github.com/felangel/fluttersaurus) for an example 👍
