### ISSUE TITLE
Graphql flutter bloc

### ISSUE THREAD

**Issue by vasilich6107** [felangel/bloc#1773]
**Is your feature request related to a problem? Please describe.**
Add a sample documentation how to work with graphql + bloc

**Describe the solution you'd like**
I wrote a [library](https://pub.dev/packages/graphql_flutter_bloc) that helps to wrap graphql requests in bloc pattern. I can add a corresponding section to the documentation.

**Comment by ram231** [comment]
I agree, 
on an advance usage. I believe that graphql should be on the level of http package(what I'm saying is to only use graphql client) as a repository.  but on a basic example, i think it's fine to use the widgets provided by graphql_flutter.

I'm on an advance usage(because there is no guarantee that when will our repository gets replaced later on).

**Comment by narcodico** [comment]
Hi @vasilich6107 👋

Thanks for your feature request.

Not sure if you're aware but there's already a graphql with bloc example available [here](https://github.com/felangel/bloc/tree/master/examples/flutter_graphql_jobs).

Just as a side note, your library is enforcing the use of `freezed`, which not everyone is using. Also the error handling could be improved towards something more generic.

**Comment by felangel** [comment]
Hi @vasilich6107 👋 
Thanks for opening an issue!

As @narcodico mentioned, there is already a graphql example included. If you'd like to add a link to your library in the README feel free to open a pull request 👍

Closing for now but don't hesitate to comment with any additional thoughts/questions and I'm happy to continue the conversation 😄

**Comment by vasilich6107** [comment]
Thanks a lot! I’ll make a PR
