### ISSUE TITLE
Structuring blocs

### ISSUE THREAD

**Issue by benplum** [felangel/bloc#178]
I have some general questions about how to structure blocs.

As a general example, let's say I have a collection of 'play lists' that contain 'songs'. I want to display first a screen with all play lists. After tapping a play list, a screen with all songs in that play list would show. Tap on a song and a screen with the song details would show. Data loads from a sqflite db after being synced from a rest api. Pretty basic.

Does this call for 3 blocs?

1. PlayListsBloc -> all play lists
2. PlayListBloc -> current play lists
3. SongBloc -> current song

Should each 'detail' view create its own bloc instance? 

1. Play lists view -> inherit from provider
2. Play list detail view -> create instance of PlayListBloc
3. Song detail view -> create instance of SongBloc

What happens when I introduce forms for user input? Would a 'create play list' form have its own instance of a PlayListBloc or would that be handled by PlayListsBloc? What about when using the same form to edit a play list's details? Finally, how should navigation handled? Should I be running push/replace/pop in response to bloc events directly in the views (create/update from form view)? 

I'm coming from the vuejs/mvvm world of reactive stores and am still trying to wrap my head around streams!

**Comment by felangel** [comment]
Hey @benplum 👋 

I think there's not a definitive right answer but in general I would recommend you think of your application as a collection of features and each feature can have its own bloc for local state management.

In your example, I think the structure you've outlined makes a lot of sense. Regarding the detail views, I would recommend when possible to keep them as stateless widgets and have all of the details they need injected. Check out the [Todos App](https://felangel.github.io/bloc/#/fluttertodostutorial) for some examples of this.

I also want to note that I would think of detail views as different features which could potentially have their own blocs and I would not recommend trying to reuse a PlayListBloc in the PlayListDetails feature.

Regarding forms, I would recommend having a separate bloc to manage form validation (keep an eye on #177 for an example of this over the next few days).

Regarding navigation, I would recommend trying to keep navigation separate from the blocs because it isn't really business logic and has dependencies on Flutter specific code (BuildContext, Navigator, etc...).

These are all really good questions and hopefully I was able to answer most of them. Feel free to comment with additional comments/questions as well as open new issues along the way. You can also reach me and other developers using bloc in [gitter](https://gitter.im/bloc_package/Lobby). 👍
