### ISSUE TITLE
Hydrated_bloc - Delete storage

### ISSUE THREAD

**Issue by mzafer** [felangel/bloc#1850]
I am using Hydrated_Bloc and it works as a breeze for caching data locally. But when I try to delete the data ( say when the user signs out ) the data is not cleared from the storage. I have tried the below two options

1. Clearing at the storage level

`await HydratedBloc.storage.clear();`

2.  In the bloc, clear the specific bloc based on a Clear event

```
if(event is ClearItems){
        await this.clear();
        yield ItemsState.empty();
}

```
The #1 almost never worked and the #2 worked most of the time. On debugging I found that whenever the storage is not deleted, the "_box.isOpen"  in the hydrated_storage.dart ( code below ) is false.

```@override
  Future<void> delete(String key) {
    if (_box.isOpen) {
      return _lock.synchronized(() => _box.delete(key));
    }
    return null;
  }

  @override
  Future<void> clear() {
    if (_box.isOpen) {
      _instance = null;
      return _lock.synchronized(_box.deleteFromDisk);
    }
    return null;
  }```

When is the hive box open? and how to delete the storage deterministically.

**Comment by felangel** [comment]
Hi @mzafer 👋 
Thanks for opening an issue!

Can you please share a sample app which reproduces the issue? Thanks! 🙏

**Comment by mzafer** [comment]
Here is a sample project, it is not a perfect but it does recreate the problem

https://github.com/mzafer/MyFlutterBloc

For Clearing at the storage level:

I am clearing the storage on Signout in the Home.dart screen. I could see on debug that "_open.isOpen" evaluates to false. To recreate this issue, open the app -> press "Sign In" -> in the next screen press "Sign out"

```
 RaisedButton(
                child: const Text('Sign Out'),
                onPressed: () async {
                  await HydratedBloc.storage.clear();
                  context
                      .bloc<AuthBloc>()
                      .add(AuthEvent_SignOut());
                },
              ),
```
For clearing at the block level:

I am clearing the bloc on  ClearItems event in the items_bloc.dart.  I am not 100% sure if this works, to test this, open the app -> press "Sign In" -> In the next screen press "Clear items"

```
} else if( event is ClearItems){
      await this.clear();
      yield ItemsState(items:[]);
    }
```

Also am seeing the below error when I toggle between "Clear Items" and "Sign out". It is not related to the original issue but no idea why this is happening. To recreate this, open the app -> press "Clear items" -> press "Sign out" -> In the next screen press "Sign In"

```
Tried calling: then<Null>(Closure: (void) => Null, onError: Closure: (Object, StackTrace) => void from Function 'onError':.) occurred in Instance of 'ItemsBloc'.
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      HydratedMixin.onChange
package:hydrated_bloc/src/hydrated_cubit.dart:149
#2      Cubit.emit
package:bloc/src/cubit.dart:85
#3      Bloc.emit

```

**Comment by felangel** [comment]
Hi @mzafer 👋 
I took a look and the reason `HydratedBloc.storage.clear();` appears to not be working is because it is wiping out the storage but the bloc is still around and re-caches the state. This is working as expected. The clearing works as expected and I will address the exception that is thrown 👍

**Comment by mzafer** [comment]
Hi @felangel ,

The bloc being around and still returning the state that is already precached makes sense, but still curious as to why "_box.isOpen" was evaluating to false and that block was not being executed.  

Also any thoughts on easily clearing the state across all blocs after I delete the storage instead of clearing them individually.

**Comment by evanholt1** [comment]
> 
> 
> Hi @mzafer 👋
> I took a look and the reason `HydratedBloc.storage.clear();` appears to not be working is because it is wiping out the storage but the bloc is still around and re-caches the state. This is working as expected. The clearing works as expected and I will address the exception that is thrown 👍

If this is expected behaviour, how can we clear the storage, or reset it, while the blocs are still there?
with hive alone i have been able to do this, but here this does not work.
I want a way to clear the storage, and thus the bloc's data.

**Comment by hey-nicolasklein** [comment]
I want to do the same thing as @evanholt1 What is the preferred way for doing that?

**Comment by talionderhobbit** [comment]
I also want to do the same as @evanholt1 and @hey-nicolasklein. Are there any further updates or informations available somewhere on how to do it in the right way?

**Comment by anoop-ananthan** [comment]
This is needed when the user logs out. It is an everyday use case. Has anybody come up with a solution?

**Comment by miguelangelflores1993** [comment]
any solution?

**Comment by felangel** [comment]
See my comment on https://github.com/felangel/bloc/issues/3834#issuecomment-1553296399

**Comment by rajjeet** [comment]
I tried clearing the storage and it works. I was hoping there was a flag in this library that lets us programmatically do this. Seems tedious and I can't see a clear use case for `storage.clear()` at the moment. 
<img width="241" alt="image" src="https://github.com/felangel/bloc/assets/11079062/7a6c4897-2179-47a7-bbaf-ec26d4c72383">

**Comment by gaiousawd** [comment]
If Anyone hasn't solve this yet I manage to clear the storage using this one
`dart
await HydratedBlocOverrides.current?.storage.clear();
`

**Comment by horlas08** [comment]
> HydratedBlocOverrides

HydratedBlocOverrides is not define from where did u see it

**Comment by felangel** [comment]
> > HydratedBlocOverrides
> 
> HydratedBlocOverrides is not define from where did u see it

You can use `HydratedBloc.storage.clear()`

**Comment by vfthome-eleme** [comment]
I would love a bloc command just like: 

> await HydratedBlocOverrides.current?.storage.clear();


But that would clear also all bloc states setting then to the initial value, globally automatically.

> await GlobalBlocReference.states?.clear();

This command would search for all active blocs on the current application and resolve then by setting all states to the initial one, this is very very useful for logout operations on my app, since after logout we have multiple hydrated blocs that gets closed and caching being cleared.

I think that one way of implementing this would be to have a function callback that:
1) Executes on all bloc classes constructors, after the user defined constructor call.
2) Initializes a Singleton class for all blocs that would be globally used in the application.
3) This singleton class should have: emitters (to emit states of each bloc) and initial states for each bloc.
4) This singleton class would have a .reset() method that would just iterate over the list of emitters and states and reset all the bloc states on a try-catch, if the bloc is not open anymore for some reason, it just ignores the error for bloc not being open.

**Comment by felangel** [comment]
> I would love a bloc command just like:
> 
> > await HydratedBlocOverrides.current?.storage.clear();
> 
> But that would clear also all bloc states setting then to the initial value, globally automatically.
> 
> > await GlobalBlocReference.states?.clear();
> 
> This command would search for all active blocs on the current application and resolve then by setting all states to the initial one, this is very very useful for logout operations on my app, since after logout we have multiple hydrated blocs that gets closed and caching being cleared.

That likely means your blocs are scoped too high in the widget tree.

**Comment by vfthome-eleme** [comment]
It is @felangel but think about this, in dependency injection systems we usually create a class with all the dependencies for a feature on my application, think about AUTH MODULE.

Auth Module pages:
- Sign up
- Sign in
- Reset password
- etc

I have one bloc instance kept on a DI class that is preserved until I navigate to a route outside the internal feature pages.
Each feature page is kept on a class that is a "Module" (flutter_modular).

So, when we have this situation, which I think is usually the case for most big applications, of a Core / Global dependency injection system on the codebase, what happens is that the blocs are kept alive, for this core services / dependencies / modules.

In this situation, we need a quick and easy way of saying to BLoC classes globally "Reset your states", this would be very very powerful and useful, in LOGOUT scenarios, because my core services would be kept (BLoCs) would be just fine being active.

**Comment by vfthome-eleme** [comment]
I do think lots of developers use this approach currently, It's just normal to think about DI packages or systems on the application, no one creates a huge app using only private class parameters and normal DI boilerplate, for my experience this is what happens.

I can help implement this class / feature if you guys also think it's something you would benefit from or like (dear reader / developer / BLoC user).


> In simple words:
> - Create a global API for resetting all active (live) blocs to their original / initial state.

I think that It may be possible, and it also may be very useful since we already have a global hydrated storage class.
It's something intuitive to have a global .clear() on it just like the current one for storage, but for states, or include an optional parameter on:

> await HydratedBlocOverrides.current?.storage.clear(clearStates: true);
> await HydratedBlocOverrides.current?.states.clear();

**Comment by vfthome-eleme** [comment]
@felangel I'm your fan, thanks for creating BLoC, if I can support this feature or any in the future would be glad to help.
