### ISSUE TITLE
Cubit bloc consumer never receives second state

### ISSUE THREAD

**Issue by PandaGeek1024** [felangel/bloc#1851]
It is so weird that it only happens on this specific page. In the blocConsumer,  listener receives the state with EditProjectLoading status and GeneratePdfFailed status correctly, but for builder it only receives state with EditProjectLoading status. Really need some help on this.

```
class TabEditProjectState extends Equatable {
  final Status status;
  final Project project;

  TabEditProjectState({this.status = const EditProjectInitial(), this.project});

  TabEditProjectState copyWith({Status status, Project project, String path}) {
    return TabEditProjectState(
      status: status ?? this.status,
      project: project ?? this.project
    );
  }

  @override
  List<Object> get props => [status, project];
}

Future<void> doSomeWork() async {
    emit(state.copyWith(status: const EditProjectLoading()));
    emit(state.copyWith(status: GeneratePdfFailed(ex.toString())));
}
class SomeWidget {
  @override
  Widget build(BuildContext context) {
    return BlocConsumer<T, S>(
      listener: (BuildContext context, state) {
          widget.blocListener(context, state);
      },
      builder: (BuildContext context, state) {
        return LoadingLayout(showLoading: showLoading, child: widget.child);
      },
    );
  }
}
```

**Comment by venkateshironman** [comment]
Remove equatable in state class it will work

**Comment by PandaGeek1024** [comment]
@venkateshironman appreciate your input, but how does cubit compare without equatable?

**Comment by mikededo** [comment]
@PandaGeek1024 `Equatable` it is just a shorcut to avoid implementing `hashCode` and the `==` operator. So, under the hood, it is using this methods (you can check the implementation in the `Equatable` package repository).  
It still compares it with the mentioned methods.

**Comment by II11II** [comment]
> Remove equatable in state class it will work

it does not work

**Comment by mikededo** [comment]
Do you use the `BlocObserver`?

With it, you could check if the event is sent. From there, if `onEvent` function from the observer does not `print` anything, I would mean you are not sending the new state properly. If it does but nothing shows up in the `onTransition` function, it is due to minor logic with the state.

Check that all custom classes used in it extend `Equatable` or they have implemented `hashCode` and `==` by value (since Dart equality works by reference).

If the problem persists, upload a bit more of code so we can dig deeper 😃

**Comment by II11II** [comment]
can i send the same  state   f.e. emit(state..network=Network.LOADED)?

**Comment by PandaGeek1024** [comment]
@mikededo does it mean I have to implement my own one after remove equatable?

**Comment by PandaGeek1024** [comment]
> Remove equatable in state class it will work

It does not work for me either

**Comment by mikededo** [comment]
> can i send the same state f.e. **emit(state..network=Network.LOADED)**?

I cannot see what you are asking for, could you explain a bit more?

---

> does it mean I have to implement my own one after remove equatable?

It depends. If you are using custom classes and you do not want to use `Equatable`, then yes. For example, let's say you have the nested classes, you have to extend `Equatable`  in all the classes:
```dart
class A extends Equatable {
  ...
  @override
  List<Object> get props => [];
}

class B extends Equatable {
  final A aInstance;
  ...
  @override
  List<Object> get props => [aInstance];
}

class C extends Equatable {
  final B bInstance;
  ...
  @override
  List<Object> get props => [bInstance];
}

/// And so on
```
So, when comparinc two C instances, it will go use the equatable from C, which involves B, which involves A.

Hope this helps!

**Comment by felangel** [comment]
Hi @PandaGeek1024 👋 
Thanks for opening an issue!

Are you still experiencing issues or can this issue be closed? If you're still experiencing issues can you please share a link to a complete sample app which illustrates the problem? Thanks 👍

**Comment by PandaGeek1024** [comment]
@felangel I have tried created a new project and copy all the code over and problem still exist. But when I create a sample project, I don't see the problem.  It is so confusing. I guess in my actual project, the view hierarchy is too complex that cause issue. I have spend 3 days on it and decided to switched to another solution, really don't want to spend time on it anymore.

**Comment by mikededo** [comment]
Well, I feel bad that you did not come with a solution 😞 
However, most of the problems that happend when the state is not updating or similar, are due to having classes not implementing `Equatable` (or `hashCode` and `==`) so that Dart does evaluate by reference but by value.
Similar with collections (`List`, `Map` and so on), whenever you are creating a new state with a `collection` from the state, you have to **create a new collection** with the `.for` constructor (the constructor `.of` works aswell). This is because you have to create a new instance of that `collection`, otherwise, it will point to that state `collection` and when comparing states, it would return true, since both states point to the same list

**Comment by felangel** [comment]
@PandaGeek1024 I'm sorry to hear that 😞  but as @mikededo mentioned it's usually an equality comparison issue. I'll close this for now if you don't want to spend more time on it but feel free to comment with additional questions/info and I'm happy to continue the conversation 👍

**Comment by ubaidillahSriyudi** [comment]
> Remove equatable in state class it will work

thanks it works for me !
1 day struggling to find out why state not emitted in the second time coming with same result, when i remove equatable finally state can emitted in many time

**Comment by venkateshironman** [comment]
@ubaidillahSriyudi thats glad to hear

**Comment by trojancode** [comment]
THis issue is not fixed. I spend a day on this. now i removed Equitable from my state then every thing works perfectly. Also i handled un-neccessary emits using onChange. I think this is the best method with cubit.
