### ISSUE TITLE
Events after the first are ignored

### ISSUE THREAD

**Issue by CarsonRedeye** [felangel/bloc#186]
**Describe the bug**
I return a Stream.periodic in the mapEventToState function and after that any further events are ignored

**Comment by felangel** [comment]
@CarsonRedeye thanks for bringing this up. This is because the stream periodic never closes so you are blocking the bloc (no pun intended). I would recommend moving the steam periodic outside of mapEventToState and instead dispatching an event in response to the periodic data. Hope that makes sense and great question! 👍
