### ISSUE TITLE
How do I test initial state properly?

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#1912]
``` dart
test('initial state is correct', () {
    final testBloc = TestBloc();
    expect(testBloc.state, TestInitialState());
    testBloc.close();
})
```
The above code works fine for most cases, but what if my bloc `add(SomeEvent())`in the constructor? Let's say

``` dart
class ExampleBloc extends Bloc<ExampleEvent, ExampleState> {
  ExampleBloc() : super(ExampleInitial()) {
    add(ExampleInitialized());
  }

  @override
  Stream<ExampleState> mapEventToState(
    ExampleEvent event,
  ) async* {
    if(event is ExampleInitialized) {
      // initialize something asynchronously
    }
  }
}
```

I use this pattern a lot for initializing something asynchronously. In this case, I can't ensure `expect()` will be called before `add(ExampleInitialized())` and any subsequent emitted states. How do I handle this case?

**Comment by felangel** [comment]
Hi @jezsung 👋 
Thanks for opening an issue!

First, I would generally recommend doing something like:

```dart
BlocProvider(
  create: (context) => ExampleBloc()..add(ExampleInitialized()),
  child: ...
)
```

Instead of adding the event internally. This makes the bloc more flexible and easier to test.

That being said, if you really want to test this case you do something like:

```dart
test('initial state is correct', () {
  expect(TestBloc().state, TestInitialState());
});

test('adds ExampleInitialized internally', () {
  final bloc = TestBloc();
  expectLater(bloc, emitsInOrder([expectedState]));
  bloc.close();
});
```

I hope this helps and I would highly recommend avoiding adding events internally 👍
