### ISSUE TITLE
CurrentState is magically changing?

### ISSUE THREAD

**Issue by carekb684** [felangel/bloc#1915]
Hello, thanks for this plugin.

I'm experiencing a strange issue where the BLoCBuilder is not updating due to currentState == nextState, which is of course correct but i'm not sure why currentState is being changed in my case.

I have this Bloc event:

if (event is RemovePhrase) {
      phraseRepo.removePhrase(event.phrase);
      phrases.remove(event.phrase);
      yield GetPhraseLoaded(phrases);
    }

phrases is my local list representing a list in a Database.

The use case: 
A list of phrases is retrieved and displayed to the user by yielding GetPhraseLoaded, then a phrase is clicked which adds the RemovePhrase event. The phrase is removed and GetPhraseLoaded is yielded again. However as you can see in the image screen shot the nextState and currentState has the same phrase:
![image](https://user-images.githubusercontent.com/8579710/98833445-4f2f3c00-243e-11eb-826a-ab99f55bca73.png)

It is expected that nextState should have 2 phrases, and that currentState should have 1.

Why is currentState changed here?

Please let me know if i can clarify anything.

**Comment by felangel** [comment]
Hi @carekb684 👋 
Thanks for opening an issue!

I believe this is happening because you are mutating state and maintaining internal bloc state. I would highly recommend avoiding maintaining an internal `phrases` in your bloc and I would also highly recommend not mutating state directly like:

```dart
phrases.remove(event.phrase);
```

Instead, I would recommend creating a new instance like:

```dart
final newPhrases = List.of(state.phrases)..remove(event.phrase);
yield GetPhraseLoaded(newPhrases);
```

Hope that helps 👍

**Comment by carekb684** [comment]
Thank you!
