### ISSUE TITLE
Using context.watch<Bloc> causes "Tried to use `context.watch<$T>` outside of the `build` method or `update` callback of a provider" errror

### ISSUE THREAD

**Issue by danielpirs** [felangel/bloc#1927]
Hi
I'm using the v6.1.1 version of flutter_bloc. As written in the documentation, to access state, context.watch should be used, but for me it causes a error below:
Tried to use `context.watch<$T>` outside of the `build` method or `update` callback of a provider...

If I use 'context.read' or deprecated 'context.bloc' everything works fine.
But according to a new migration guide (https://bloclibrary.dev/#/migration) for v6.1.x context.watch is the right approach.

Parent Widget:
      body: BlocProvider(
        create: (context) => getIt<bloc>(),

Child Widget:

Widget build(BuildContext context) {
    return BlocConsumer<Bloc, State>(
      listener: (context, state) { ....}
      builder: (context, state) {
        return Form(...
           child: ListView(
           children: [
              TextFormField(
                  validator: (_) => context.**watch**<SignInFormBloc>().state.emailAddressError

**Comment by felangel** [comment]
Hi @danielpirs 👋 
Thanks for opening an issue!

In this case you cannot use `context.watch` because it is not **directly** in the `build` method. The `validator` callback is invoked independently of the `build` method so you should prefer to use `context.read` or `context.select`.

Hope that helps and closing for now but if you have additional questions and I'm happy to continue the conversation 👍

**Comment by danielpirs** [comment]
Thanks!
