### ISSUE TITLE
Should I call close on Bloc in this case?

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#1931]
``` dart
final blocA = BlocA();

BlocListener<BlocA, BlocAState>(
  cubit: blocA,
  listener: (context, state) {

  }
)
```

Should I call `blocA.close()` or BlocListener/BlocBuilder/BlocConsumer do it for me?

**Comment by felangel** [comment]
Hi @jezsung 👋
Thanks for opening an issue!

The general rule of thumb is whoever creates the bloc should be responsible for closing it. In this case since it created outside of BlocProvider, it is your responsibility to close it.

I would highly recommend using BlocProvider to create and provide blocs whenever possible as it simplifies development and handles closing the bloc automatically 👍
