### ISSUE TITLE
Close instances of `dart.core.Sink`. warning by IDE

### ISSUE THREAD

**Issue by momoDragon** [felangel/bloc#1942]
**Documentation** 
<img width="792" alt="Screenshot 2020-11-18 at 5 44 48 PM" src="https://user-images.githubusercontent.com/40727575/99513753-ec055280-29c5-11eb-8473-352f2a173754.png">

**My implementation**
<img width="625" alt="Screenshot 2020-11-18 at 5 44 37 PM" src="https://user-images.githubusercontent.com/40727575/99513789-f58eba80-29c5-11eb-8be3-79a17ee435f9.png">

Got a warning by my IDE saying 
`Close instances of `dart.core.Sink``

The implementation should be correct based on the docs but there is waring.
Is the code violating anything? and if not, is there any plans to refactor to get rid of the warning?

Cheers

**Comment by shaan-saz** [comment]
In this way, you're manually accessing your bloc. To solve this, dispose your provider by calling `customerBloc?.close()` in your dispose().

**Comment by felangel** [comment]
@momoDragon what you’re doing is perfectly fine and the warning is a false positive from the dart linter. There’s an open issue for this but in the meantime you can disable close_sinks in your analysis_options.yaml. You shouldn’t need to call close because BlocProvider does that for you.

See https://github.com/felangel/bloc/issues/587 for more details.

**Comment by momoDragon** [comment]
Thanks for the info @felangel 

I found that getting state just once this would be ideal for my case.
`CustomerState customerState = BlocProvider.of<customerBloc>(context).state;
`

@shaan-saz  Calling .close() actually closes my bloc. so to get the bloc once and close it was not wise in my case.

Anyway thanks for the help
