### ISSUE TITLE
We should have built-in `SimpleBlocDelegate` 

### ISSUE THREAD

**Issue by anticafe** [felangel/bloc#200]
**Is your feature request related to a problem? Please describe.**
I'm lazy to copy and paste `SimpleBlocDelegate`.

**Describe the solution you'd like**
We should have `SimpleBlocDelegate` built-in, so that anyone can reuse it. And, if possible, rename it to `SimpleDebugBlocDelegate` or something similar to indicate that would print debug log. That class also to have a `printLog` param to enable print log.

**Additional context**
I'm using bloc v0.11.2

**Comment by felangel** [comment]
@anticafe thanks for the feature request 👍 

Just curious, are you using VSCode? If so, the [bloc vscode extension](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc) has a snippet for `BlocDelegate` so you don't have to type/copy it over and over.

I'm a bit hesitant to include this directly in the bloc package because I don't really think this is a "core" feature. I can definitely see it being included in a separate package which people can optionally install. Thoughts?

**Comment by anticafe** [comment]
I choose Android Studio as main IDE for Android development. 

If you don't want to include such `SimpleBlocDelegate` file into `core` feature, let think about add a method for `BlocSupervisor` to enable or disable log, such as `BlocSupervisor.enableDebugLog(bool enable)`. If so, we can enable debug log in debug build, and disable it in release build. Is it okay?

**Comment by felangel** [comment]
@anticafe I feel like that would be confusing then because it would be unclear if `enableDebugLog` overrides the BlocDelegate behavior or not. We can always create a separate package to export a `SimpleBlocDelegate` if you think that'd be useful or you can create a template for it in Android Studio (see san4io's comment in https://github.com/felangel/bloc/issues/116).

Closing this for now but let me know what you think! 👍
