### ISSUE TITLE
[6.1+] contex.bloc and context.repository deprecation question

### ISSUE THREAD

**Issue by andrea689** [felangel/bloc#2003]
Before 6.1 I used flutter_hooks and `useBloc` to create and dispose a Bloc instead of `BlocProvider` in this way:

```dart
class ActivitiesPage extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final myBloc = useBloc(
      () => MyBloc(
        myRepository: context.repository<MyRepository>(),
        otherBloc: context.bloc<OtherBloc>(),
      ),
    );
    ...
  }
}
```

Now that `context.repository` and `context.bloc` are deprecated, if I use `.read` I received an exception because I'm in build method, and if I use `.watch` I have unnecessary rebuild.

How can I solve? Am I forced to refactor my code and use BlocProvider?
Thank you!

**Comment by felangel** [comment]
Hi @andrea689 👋 
Thanks for opening an issue!

The `context.read` extension implementation is part of `provider` so it might be worthwhile raising this issue on the provider repo because in this case `context.read` isn't used directly within `build`. In the meantime you can create your own `context.bloc` extension like:

```dart
extension ContextBloc on BuildContext {
  C bloc<C extends Cubit<Object>>() => BlocProvider.of<C>(this);
}
```

Let me know if that helps 👍

**Comment by andrea689** [comment]
okay, thanks for the clarifications!
