### ISSUE TITLE
关于MultiBlocProvider的使用,如何在将某个Bloc作为另一个Bloc的参数?

### ISSUE THREAD

**Issue by hu70258tao** [felangel/bloc#2023]
MultiBlocProvider
![image](https://user-images.githubusercontent.com/20218008/102565984-7d78f900-4119-11eb-9707-d8b418c95d6f.png)
这是我的代码
但是我看你们都是一样的写法呢?
![image](https://user-images.githubusercontent.com/20218008/102566080-b1ecb500-4119-11eb-9f8f-46c20540bace.png)

**Comment by hu70258tao** [comment]
难道是因为我在中国的原因?为什么我在github看不到任何图片,包括自己的头像.

**Comment by hu70258tao** [comment]
![image](https://user-images.githubusercontent.com/20218008/102566141-d9dc1880-4119-11eb-969e-1a7f5fa1ec89.png)

**Comment by wuweijian1997** [comment]
图片是伟大的墙问题.提问以后尽量用英文吧...两个并不一样,你用的是 BlocProvider.value,他用的是create.你们两个的区别就是context不同.
```
BlocProvider<ScanBloc>(
          create: (context) => ScanBloc(context.read<MessageBloc>()),
        ),
```

**Comment by hu70258tao** [comment]
![image](https://user-images.githubusercontent.com/20218008/103336534-76f06700-4ab3-11eb-8dc2-fdd23b88eb54.png)
我有一处代码,被注释掉的写法,会报异常:Tried to use `context.read<MessageBloc>` inside either a `build` method or the `update` callback of a provider

**Comment by wuweijian1997** [comment]
read方法上的注释是说不要再build里面用这个方法,read是在事件里面用的.
```
/// **DON'T** call [read] inside build if the value is used only for events:
  ///
  /// ```dart
  /// Widget build(BuildContext context) {
  ///   // counter is used only for the onPressed of RaisedButton
  ///   final counter = context.read<Counter>();
  ///
  ///   return RaisedButton(
  ///     onPressed: () => counter.increment(),
  ///   );
  /// }
  /// ```
  ///
  /// While this code is not bugged in itself, this is an anti-pattern.
  /// It could easily lead to bugs in the future after refactoring the widget
  /// to use `counter` for other things, but forget to change [read] into [watch].
  ///
  /// **CONSIDER** calling [read] inside event handlers:
  ///
  /// ```dart
  /// Widget build(BuildContext context) {
  ///   return RaisedButton(
  ///     onPressed: () {
  ///       // as performant as the previous previous solution, but resilient to refactoring
  ///       context.read<Counter>().increment(),
  ///     },
  ///   );
  /// }
  /// ```
```

**Comment by Peng-Qian** [comment]
> ![image](https://user-images.githubusercontent.com/20218008/103336534-76f06700-4ab3-11eb-8dc2-fdd23b88eb54.png)
> 我有一处代码,被注释掉的写法,会报异常:Tried to use `context.read<MessageBloc>` inside either a `build` method or the `update` callback of a provider

1. `BlocProvider.value`是使用已有的bloc，所以你不应在这里创建新的bloc，因为`BlocProvider.value`不会在widget dispose的时候自动关闭bloc，因此如果在这里创建bloc，除非你手动关闭bloc，你的bloc将一直不会关闭而导致内存溢出。

2. `context.read<T>()` 其实就是`Provider.of<T>(context, listen: false)`的简写版本，你得到的错误其实别不是真正的逻辑或语法错误，而是Provider作者提醒的语义错误: 在build中的Provider应该因数据变化而rebuild widget，所以应使用`context.watch<T>()`,也就是`Provider.of<T>(context, listen: true)`。因此，你把`BlocProvider.value`换成`BlocProvider(create: (context) => SomeBloc())`后，就可以使用`context.read<T>()`了。

3. 推荐你用英文问问题，第一是尊重插件作者，第二是能得到来自不用国家的更多的帮助，第三是插件作者的回答往往是最准确和最有效的。这个插件作者非常负责，他每一个帖子都会认真看和回答。

---------------------------------------------------------------------------------------------------------------------------
1. You should pass an existing bloc to `BlocProvider.value`, rather than create a new bloc here. It is because `BlocProvider.value` will not automatically close the bloc when the widget dispose. Thus, if you create a bloc via `BlocProvider.value`,  the bloc will never be closed unless you manually close it, and it may causing memory overflow.

2. `context.read<T>()` is actually a syntax sugar of `Provider.of<T>(context, listen: false)`. The error you got is not a real logic or syntax error, but a reminder of possible semantic error from Provider author: The Provider in the build method should listen to the data changes and result widget rebuild due to data changes, so you should use `context.watch<T>()`, which actually is, `Provider.of<T>(context, listen: true)`. Therefore, you can safely use `context.read<T>()` after replacing `BlocProvider.value` with `BlocProvider(create: (context) => SomeBloc())`.

3. I highly recommend that you ask questions in English. The first is to show respect to the package author, the second is to get more help from different countries' developers, and the third is that the answer from the package author is often the most accurate and effective. And The author of this package is very responsible, he always carefully read and answer every post.

**Comment by hu70258tao** [comment]
我的英文能力比较差,机翻对英文阅读者来说,可能也很困难.

**Comment by wuweijian1997** [comment]
如果解决了你的问题就关闭issues,如果有其他问题另开一个issues就好了,不要一直开着.
