### ISSUE TITLE
Is map MapEventToState really needed ?

### ISSUE THREAD

**Issue by cedvdb** [felangel/bloc#2029]
Sending event to then call MapEventToState which in turn calls functions is essentially the same as calling those function directly. I don't think this level of indirection should be mandatory.

I understand the benefit is that you have a single entry point for the events, then it's easier to observe, but really you can observe a stream with scan and whatnot.

The cons is that it adds boiler plate.

So is there any benefits I'm not seeing ? I'm tempted to just call functions directly which call emit. Although the source code says emit shouldn't be used outside of tests. Or even make my own state management lib that maybe suit me more.

**Comment by II11II** [comment]
Hi @cedvdb ,
You may use cubit instead of bloc in your case. However, for some case events are needful in development of app.
F.e. If user search in your app some words and your app do request to your web server, then server side can take some seconds to reply to your app and you show results to user. As may you know for each typed letter can be done request to server. 
If you use here cubit, you can have some problems when you will do request  and show results user.
You will call Future to do request not steam in Cubit, so These futures may not be finished sequently. But in steam you can control sequences, so for this, bloc will help you.

**Comment by cedvdb** [comment]
I don't see how the bloc would help in your scenario. Wouldn't both scenario use something like a stream with a debounce ? or would the bloc work differently ?

**Comment by II11II** [comment]
@cedvdb [Almost the same question](https://github.com/felangel/bloc/issues/1444) 
 I recommend you to read about steams and rxdart.

**Comment by cedvdb** [comment]
> @cedvdb [Almost the same question](https://github.com/felangel/bloc/issues/1444)

thanks

> I recommend you to read about steams and rxdart.

ho. I'm fluent in rx, I've been using it for years and made multiple libs based on it.
