### ISSUE TITLE
[bloc_test] verify event dispached

### ISSUE THREAD

**Issue by andrea689** [felangel/bloc#2049]
Is there a way to verify that the bloc in testing has dispached an event?

Example bloc:

```dart
if (event is MyEvent) {
  ...
  add(MyOtherEvent());
  ...
}
```

Example test: 

```dart
  blocTest(
      'should dispatch MyOtherEvent',
      build: () {
        return myBloc;
      },
      act: (bloc) => bloc.add(MyEvent()),
      expect: [
        ...
      ],
      verify: (bloc) async {
        // ERROR: Used on a non-mockito object 
        verify(bloc.add(MyOtherEvent())).called(1);
      },
    );
```

**Comment by felangel** [comment]
Hi @andrea689 👋 
Thanks for opening an issue and sorry for the delayed response!

In this case you cannot use `verify` because the bloc instance isn't a `Mock`. Generally, you should be less concerned about internal events being added by the bloc and more concerned with the emitted states. If you really do want to verify that the other event was added internally, you can always create a `MockBlocObserver`:

```dart
class MockBlocObserver extends Mock implements BlocObserver {}

void main() {
  Bloc.observer = MockBlocObserver();
}
```

Then you can verify that `onEvent` was called with the correct bloc and event using the `verify` API from `mockito`.

Hope that helps and closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍
