### ISSUE TITLE
Release a null-safe pre-release of bloc_test

### ISSUE THREAD

**Issue by felix-barz-brickmakers** [felangel/bloc#2063]
bloc and flutter_bloc have already been released with a nullsafe version as prerelease. Please create such a prerelease for bloc_test as well, so we can actually upgrade flutter_bloc or bloc and try out nullsafety.

**Comment by felangel** [comment]
Hi @felix-barz-brickmakers 👋 
Thanks for opening an issue!

I'm more or less ready to do so but my hesitation has been due to the [breaking changes in mockito's API due to null safety](https://github.com/dart-lang/mockito/issues/286) (which bloc_test relies on). I have been experimenting with [a different approach to mocks](https://github.com/felangel/mocktail) which would avoid relying on manual overrides and code generation that would allow `bloc_test` to function as it did before but have been hesitant to push this approach because it could potentially create confusion.

I would love to hear everyone's feedback before proceeding either way, thanks! 🙏

**Comment by felix-barz-brickmakers** [comment]
Both variants have valid points. I might even prefer the second approach, as it seems that the mockito guys haven't really found a nice solution for the core problem yet. I have also hade quite some problems with the generated mocks. But one idea for mocktail: Instead of passing a string to the `calls` method, use symbols instead: `when(cat).calls(#meow)` - it looks cleaner and makes it explicit, that method names are required.

**Comment by felangel** [comment]
@felix-barz-brickmakers I took your suggestion and refactored [mocktail](https://pub.dev/packages/mocktail) to use `Symbol` (it was implemented like that originally anyway 😅) and you can track the progress at #2067 👍

**Comment by felangel** [comment]
[v8.0.0-nullsafety.0](https://pub.dev/packages/bloc_test/versions/8.0.0-nullsafety.0) is now available 🎉
