### ISSUE TITLE
[Question] Correct why to use nested models/classes with BloC

### ISSUE THREAD

**Issue by Lix-ai** [felangel/bloc#2090]
Hi,
What is the correct way to use nested models/classes with BloC?
For example, I creating X number of airplanes and for each plain I create Y number of passengers.

For controlling each X number of airplanes I saw it at the 'flutter_complex_list' example, but what is the correct approach with flutter bloc to control each Y number of passengers for each plain?

I'm thinking about several options (maybe I shall/can mix them?):
1. At the X airplanes class in the 'ListView.builder', call a new class for the Y passengers **+** create the model in the same models folder of the airplanes **+** at the state(success) call both lists (airplanes cubit and state classes are the same cubit and state classes of the passengers).
2. Create separate cubit and state for the passengers and use a BloCbuilder for it (like in the 'flutter_shopping_cart' example) at the passenger class.
3. At the airplane model class, one of the variables is the passengers list.

Regarding 1-3:
  * Shall in the cubit, I will check the ID of the airplane and than check the ID of the passenger to use the passenger?
  * AND/OR I need to pass airplane index to the passenger class?

Another general question = when using 'Stateful' class with bloc, there are any important guidelines? maybe regarding 'initState' and 'dispose' methods?

Thanks in advance =]

**Comment by felangel** [comment]
Hi @Lix-ai 👋 
Thanks for opening an issue and sorry for the delayed response!

Generally, the answer to your question depends on the circumstances. If the complexity of the nested models is fairly low and the cost to retrieve them is also fairly low, it might be simplest to go with option 3 where the models are nested and managed by a single bloc.

In general, I recommend creating a single bloc per feature/use-case. Rather than thinking of blocs as managing data, think of them as managing feature state. With that mentality, it's usually the most scalable to have separate blocs/cubits which potentially share one or more repositories as dependencies (you can cache at the repository) and query the data they need independently of each other.

For example, you might have an AirplanesBloc which exposes just a list of Airplanes (id and name). Then you might have a separate feature where you need to list the passengers for a given airplane. In that case, it's generally best to create a PassengersBloc and add a `PassengersRequested` event which requires an Airplane ID. This keeps the two blocs decoupled and allows your features to evolve independently of each other.

> Another general question = when using 'Stateful' class with bloc, there are any important guidelines? maybe regarding 'initState' and 'dispose' methods?

Generally, if you want to use a StatefulWidget with bloc you should remember to create the bloc in `initState` and close it in `dispose`. The rule of thumb is whoever creates the bloc is responsible for closing it 👍 

Hope that helps 😄 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation!

**Comment by Lix-ai** [comment]
Thanks Felix =]!!!
How i'm technically/practically doing the "PassengersBloc and add a PassengersRequested event which requires an Airplane ID"?

Can i do it with Cubit?

Thanks in advance!

**Comment by felangel** [comment]
@Lix-ai yup you should be able to use bloc or cubit 👍 

If you want to use `onGenerateRoute` take a look at [the Bloc Access Recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=generated-route-access).

**Comment by Lix-ai** [comment]
Thanks :)!
