### ISSUE TITLE
[QUESTION] What is the best practice on getting previous state information?

### ISSUE THREAD

**Issue by SEGVeenstra** [felangel/bloc#2097]
I've been learning to use BLoC the last couple of days but I ran into an 'problem' which I'm not sure of how to handle and was wondering if anyone could point me in the right direction.

I'm working on a little Wheel Of Fortune kind of app where the user can place bets on the colours on the Wheel.

I've was thinking of using the following states of the screen:

1. Initial
2. Loading - for getting saved data
3. Betting - the user can place bets
4. Spinning - the wheel is spinning, no bets can be placed
5. RoundWon - win screen
6. RoundLost - lost screen

While in Betting the state will contain the bets you are making.
When bets are made the user can start Spinning.
At this point I don't want to show the betting information so I was thinking to leave it out of the Spinning state.

But when the spinning stops, I need to know which bets had been placed to determine a win or loose.

What is the best way to keep a hold on these bets, without exposing them to the screen in the Spinning state?

I was thinking of the following solutions myself:

**A) Store in BLoC**
I'm not sure if this is good practice, because all the samples I've seen only base the next state on the previous state + event data. _Is it even 'allowed' to store things in the BLoC or should it only rely one states and events to prevent side-effects?_

**B) Pass the betting info with the Spin event**
I just came up with this while writing this question and feels like the way to go.

**C) Simplify the states to hold all the data**
This feels like I'm giving the UI to much responsibility

**Comment by felangel** [comment]
Hi @SEGVeenstra 👋 
Thanks for opening an issue!

A) I don't recommend this approach. Ideally, blocs should have no internal state and all state should be part of the bloc state type (as you correctly pointed out).

B) This is the best approach from the standpoint of the UI because there is a clean separation between the states and only the relevant properties are available to the UI in each state. The downside of this approach is that it is usually accompanied by an increase in complexity within the bloc due to having the type check and pass state properties from a previous state to a new state.

C) This is the simplest approach from the standpoint of the bloc but as you mentioned places extra responsibility on the UI to add additional checks before accessing the bloc state. This is usually also the most flexible approach because as your state evolves/becomes more complex it is fairly easy to refactor whereas with option B the complexity is usually fairly high.

Overall it's up to you to choose between B and C. In my opinion, there's no right/wrong but after having played around with each I find that for simple cases where there aren't many properties/complex states B works well but at a certain point I find myself refactoring to C because the added complexity in the bloc code isn't worth the benefit.

Hope that helps and great question! 👍

**Comment by SEGVeenstra** [comment]
Thank you for your response!
I currently implemented B and I understand what you mean by the complexity of passing states data.

Information that has to skip a state I can store in repositories and fetch when needed again. This way I persist my data in the actual data layer of my app. And I think that's beautiful ;)
