### ISSUE TITLE
Using context in initState

### ISSUE THREAD

**Issue by cosinus84** [felangel/bloc#210]
I was looking in your example and I saw in https://github.com/felangel/bloc/blob/master/examples/flutter_todos/lib/screens/home_screen.dart
```
_filteredTodosBloc = FilteredTodosBloc(
      todosBloc: BlocProvider.of<TodosBloc>(context),
    );
```
Is this safe to use the context in initState? Reading the all the documentation around everybody is saying not to use context in initState. Can you explain why is ok using as you did.
I am doing always in didChangeDependencies something like _filteredTodosBloc ??= ...

**Comment by felangel** [comment]
Hi @cosinus84 👋 
Thanks for opening an issue!

Great observation and normally I would recommend accessing inheritedWidgets in `didChangeDependencies` but with BlocProvider it works in `initState` because it uses `ancestorInheritedElementForWidgetOfExactType` combined with`updateShouldNotify(BlocProvider oldWidget) => false;`

Normally if you're using `inheritFromWidgetOfExactType` and support notifying on updates then you wouldn't be able to access it in `initState` as you mentioned.

Hope that helps and great question 💯
