### ISSUE TITLE
context.read rebuilds build() method

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2112]
**Describe the bug**
context.read rebuilds whole build() method
I used context.read to get const list length in state 

**Expected behavior**
Just get state and dont rebuild it because i have stateful widget builder (PageView.builder)

[Link to gist](https://gist.github.com/II11II/1c5004580aaecd50fb1a0c5cfb8b10fe)

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

I took a look and I believe the reason for the rebuild is because you are also using `context.watch` at https://gist.github.com/II11II/1c5004580aaecd50fb1a0c5cfb8b10fe#file-onboard_page-dart-L33.

Closing for now but if you still have questions feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by II11II** [comment]
HI @felangel,
Big thanks for taken a look my code,
What do you recommend instead of context.watch in order to not rebuild my widget ( the widget is stateful as default)
