### ISSUE TITLE
[feature request] Ability to provide bloc in BlocBuilder / BlocConsumer

### ISSUE THREAD

**Issue by cedvdb** [felangel/bloc#2130]
**Is your feature request related to a problem? Please describe.**
I would like to avoid nesting unnecessarily by having a BlocProvider + a Bloc Consumer for screens cubit. This would make the use leaner of the UI. 

**Describe the solution you'd like**
 instead of this

```
            BlocProvider(
              create: (ctx) => PhoneFormBloc(),
              child: BlocConsumer<PhoneFormBloc, FormxState>( 
                builder: (context, state) => PhoneForm(
                        onSubmit: context.read<PhoneFormBloc>().submit,
               )
```

Having this:

```
            BlocConsumer<PhoneFormBloc, FormxState>(
              cubit: PhoneFormBloc(),
              builder: (context, state) => PhoneForm(
                    onSubmit: context.read<PhoneFormBloc>().submit,
               )
```

or 

```
            BlocConsumer<PhoneFormBloc, FormxState>(
                create: (ctx) => PhoneFormBloc(),
                builder: (context, state) => PhoneForm(
                        onSubmit: context.read<PhoneFormBloc>().submit,
                )
```

**Comment by felangel** [comment]
Hi @cedvdb 👋 
Thanks for opening an issue!

I would highly recommend against this because it results in tightly coupling the widget which is creating the bloc with the widget that is consuming the bloc. This makes it extremely difficult to write widget tests because they will be using the real bloc and it's not possible to provide a mock.

For an example, you can refer to the [weather example](https://github.com/felangel/bloc/blob/daf09b994cbcc4b7105572d954c069e4795abbd0/examples/flutter_weather/lib/weather/view/weather_page.dart#L10) and note that the role of the `WeatherPage` is to provide an instance of a `WeatherCubit` to the `WeatherView`. Then the `WeatherView` is just consuming the cubit state and has no idea where it came from.

We can then [test the WeatherView](https://github.com/felangel/bloc/blob/daf09b994cbcc4b7105572d954c069e4795abbd0/examples/flutter_weather/test/weather/view/weather_page_test.dart#L40) very easily by providing a `Mock` instance of the `WeatherCubit`.

Hope thatt helps 👍

**Comment by cedvdb** [comment]
I see, good observation as always. Hopefully there will be something leaner in the future when reflectivity is solved rather than a whole widget for providing, like annotations in angular.

Closing

**Comment by cedvdb** [comment]
@felangel 

I think something can be said about instantiating the cubit as a default in the constructor.

EG: you only have WeatherView in your example as such

```
class WeatherView extends StatelessWidget {
    WeatherCubit weatherCubit;
    WeatherView({ this.weatherCubit = WeatherCubit() });
    // ...
}
```

The arguable advantages I see:

  - Your page component interacts with the cubit but everything under it stays "dumb"
  - The cubit is properly scoped only to that specific component. When using provider it's accessible in the whole subtree (which is the point of provider).

Whether it's a better solution is debatable, I just thought it's worth mentioning.

**Comment by cedvdb** [comment]
@felangel 

I think something can be said about instantiating the cubit as a default in the constructor.

EG: transform your example to only have WeatherView in your example as such

```
class WeatherView extends StatelessWidget {
    WeatherCubit weatherCubit;
    WeatherView({ this.weatherCubit = WeatherCubit() });
    // ...
}
```

The arguable advantages I see:

  - Your page widget interacts with the cubit but everything under it stays "dumb". Which makes sub widgets more reusable. (Not tied to a specific cubit).
  - The cubit is properly scoped only to that specific container / smart widget. When using provider it's accessible in the whole subtree (which is the point of provider, but I don't think it's always good).
  - Testing is even easier.

For the dependency injection of the repository the same can be applied where there is a default (could be injected via get it or whatever) and you can override it.

Whether it's a better solution is debatable, I just thought it's worth noting.

**Comment by cedvdb** [comment]
@felangel Do you see any drawbacks of doing it like this (and bubbling everything to the top):

```
class PreferencesScreen extends StatelessWidget {
  final PreferencesBloc _preferencesBloc = PreferencesBloc();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: SentAppBar(
      body: BlocBuilder<PreferencesBloc, FormxState>(
        bloc: _preferencesBloc,
        builder: (ctx, state) => state is FormxStateForm
            ? PreferencesForm(
                value: state.initialValue,
                onChange: (value) => _preferencesBloc.submit(value),
              )
            : Spinner(),
      ),
    );
  }
}
```

**Comment by felangel** [comment]
@cedvdb yes, you should avoid doing that because the bloc will never be disposed properly.
