### ISSUE TITLE
Rebuilding the widget when showing error message in snackbar

### ISSUE THREAD

**Issue by Sourabhlpu** [felangel/bloc#217]
Hi,

I have a listview in the bloc builder. Before returning the list in the builder I am checking for error and showing a snackbar:
```
   if (state is GenericError) {
                _onWidgetDidBuild(() {
                  Scaffold.of(context).showSnackBar(
                    SnackBar(
                      content: Text('${state.error}'),
                      backgroundColor: Colors.red,
                    ),
                  );
                });
              }
```
The issue is that when there is an error the whole widget is built again and the list ends up being empty. 

Also if my last state was an error state and when the widget is built again (eg. keyboard close or open) the snackbar is shown everytime.

**Comment by felangel** [comment]
Hi @Sourabhlpu 👋 
Thanks for opening an issue!

We recently added `BlocListener` to flutter_bloc v0.10.0. BlocBuilder should not be used for one-time actions like showing a SnackBar because the builder method can be called multiple times by Flutter.

Check out the [BlocListener Recipe](https://felangel.github.io/bloc/#/recipesbloclistener) for an example 👍 

Hope that helps!

**Comment by Sourabhlpu** [comment]
Wow, I was just thinking if a feature something like that could be added
and it was already there. Great this is cool👍

**Comment by Sourabhlpu** [comment]
Hi @felangel,

I have a question again on this. So listener is great but the same any event calls both the listener and the bloc builder right? My main issue is, suppose I have already loaded a list, now I want to display some error message in snackbar as user taps on some button. Because this new event rebuilds my widget as well and since this new state doesn't have a list I don't have a list to display in this new state. 

I hope I made myself clear in explaining the scenario and if I doing some stupid mistake here please let me know.

**Comment by felangel** [comment]
Hey @Sourabhlpu,

I think it might help if I better explain how it all works:

1. An event is dispatched
2. The bloc processes the event and yields a new state
3. BlocListener gets notified of the state change
  - Here we can do one-time actions like navigate or show a SnackBar
4. BlocBuilder gets notified of the state change
  - Here we need to tell Flutter what widgets to build in based on the current state
  - BlocBuilder can also get called at any time by Flutter to re-render the widgets so it should be pure

Regarding your particular scenario, if a feature can have an error and a list at the same time, then I would recommend having the state contain both the error as well as the list so that BlocBuilder renders the list while BlocListener shows a SnackBar. Hope that helps 👍

**Comment by Sourabhlpu** [comment]
Thanks for the quick response. That helped. I was thinking the same way
about the solution but I thought probably it was not the right thing to do
and there was a better way. 😊

**Comment by felangel** [comment]
No problem! Bloc has no opinion about how to set up your states and events so it's totally up to you and depends on the feature 👍
