### ISSUE TITLE
flutter_bloc: Rename `RepositoryProvider` to `Provider`

### ISSUE THREAD

**Issue by vinayluzrao** [felangel/bloc#2171]
**Is your feature request related to a problem? Please describe.**
The `RepositoryProvider` class can actually provide any `Object`, not just repositories, and there isn't any `Repository` abstraction in either of `package: flutter_bloc` or `package: bloc`. Therefore, the name is misleading. It:
- hides the fact that objects besides repositories can be injected
- makes it seem that a `Repository` abstraction actually exists in the package

**Describe the solution you'd like**
From my understanding, `RepositoryProvider` et. al. are opinionated quality of life improvements over `package: provider`'s `Provider`, and therefore the name I suggest for `RepositoryProvider` is `Provider` as that is succinct and indicative that its functionality is very similar to `package: provider`'s `Provider`. I don't think the consequent naming conflicts with `package: provider` have much weight as dart's package namespacing feature (e.g. `import '...' as flutter_bloc;`) trivially solves this.
Obviously, in this case related code such as `MultiRepositoryProvider` should be renamed as well.

**Additional context**
For example, I'm currently using `RepositoryProvider`s as a way to inject my custom `ApiClient` data provider into my repositories. Because of the misleading naming of `RepositoryProvider`, this looks confusing and the first impression to a reader is a spaghetti mess at the repository layer (multiple repositories are coupled, which should never be the case).

**Comment by felangel** [comment]
Hi @vinayluzrao 👋 
Thanks for opening an issue!

The main point of the naming `RepositoryProvider` is to discourage providing any type of object and to indicate to developers that things like `ApiClients` should generally not be passed throughout the widget tree. The reason there is no `Repository` abstraction is because it would likely end up being an empty class (although I'm not entirely opposed to this it doesn't seem super valuable).

Generally, I recommend that data providers like `ApiClients` are injected into repositories and the repositories themselves are provided to the widget tree to avoid tightly coupling the application layer to the underlying data acquisition layer.

If you would like to pass around any type of objects you can definitely use `package:provider` directly but I generally don't recommend that approach as part of the bloc library architecture.

Let me know if that helps clarify things.

**Comment by vinayluzrao** [comment]
Hi @felangel, thanks for the quick response!

> Generally, I recommend that data providers like `ApiClients` are injected into repositories and the repositories themselves are provided to the widget tree to avoid tightly coupling the application layer to the underlying data acquisition layer (refer to the [architecture docs](https://bloclibrary.dev/#/architecture) for more details).

I looked through the weather example, and understood your motivation, but I'd like to mention that this only partially avoids the problem: even when doing this, the view layer still has access to repositories via `context.read()`, and these should ideally only be used to inject into `Cubit`s. An example of a misusage is calling repository methods in a  `Widget`'s build methods. The moral of the story is that it is still up to the programmer to architect things correctly, and the first thing step to that in this case is to read amazing documentation (thank you!). Doing that would quickly make their mistake apparent, and that leads me to my key argument: *guidance should be done through documentation*. Sure, you can put useful guard rails in the code, e.g. static type checking and the `@mustCallSuper` annotation, but the naming choice we are discussing is not a guard rail as it is not enforced by anything.

I will admit I am quite "purist" about naming things accurately. I see misnaming is misinformation, and the latter often leads to confusion, which leads to bugs and wasted time.

**Comment by felangel** [comment]
@vinayluzrao the repositories must be available to the widget tree in order to be injected into various blocs. I personally don't think renaming `RepositoryProvider` to `Provider` would be beneficial for several reasons:

- It will introduce confusion/overlap with `package:provider`
- It will imply that anything can/should be provided (which as I mentioned is not advisable)

> The moral of the story is that it is still up to the programmer to architect things correctly.

In my opinion, API naming plays a big role in promoting consistent, scalable architecture and in this case making the name more generic isn't beneficial (see above).

> I will admit I am quite "purist" about naming things accurately. I see misnaming is misinformation, and the latter often leads to confusion, which leads to bugs and wasted time.

In my opinion this isn't misnaming. While functionality definitely has an impact on naming, the intention of the component is also a key part of naming. In this case, the intention of this class is to provide Repositories, not ApiClients, StorageClients, etc.

I think there are 3 potential paths forward:

### 1. Do nothing
  
Advantages:
- No additional dependencies needed
- Discourages misused via naming (not strict)

Disadvantages:
- Can technically be misused (to provide ApiClients, etc.)

### 2. Add a `Repository` base which all Repositories must extend.

Advantages:
- No additional dependencies needed
- Strictly enforces that only repositories are provided

Disadvantages:
- All repositories need to extend `Repository` which requires that they have a dependency on flutter_bloc (and `flutter`)
- Developers can still do `class ApiClient extends Repository {...}` which takes us back to the disadvantages of 1.

### 3. Remove `RepositoryProvider` and `MultiRepositoryProvider` from `flutter_bloc` 

Advantages:
- No confusion about RepositoryProvider naming

Disadvantages:
- Developers must figure out how to inject dependencies
- Additional 3rd party packages are required (in most cases)
- It's up to developers to determine what to provide to the widget tree (complete freedom with minimal guidance)
- disruptive breaking change

For these reasons I prefer to go with option 1. Let me know what you think and thanks for the awesome discussion 👍

**Comment by vinayluzrao** [comment]
@felangel you've convinced me, and I agree that option 1 is best. Thanks a lot, I had a gap in knowledge in how to properly use data providers.

A side note: besides the tutorials section, the documentation for them is quite little, and, at least for me, it wasn't at all clear that the best way to instantiate them is outside `runApp()` for mocking purposes. But perhaps this is only because when I was learning `bloc` I didn't yet have a need for data providers, and so I skimmed the details about their usage in the tutorials section.

Thanks for the amazing work! I'll leave the closing of the issue to you, in case you'd like to leave the discussion open.

**Comment by felangel** [comment]
@vinayluzrao No worries! The documentation should definitely be improved to make this more clear. I created #2172 to track the documentation improvement 👍 

Closing for now but happy to continue the conversation as needed 😄
