### ISSUE TITLE
How cubit to cubit stream listens?

### ISSUE THREAD

**Issue by Puspharaj** [felangel/bloc#2185]
This is not a bug or feature.

What I observed, when bloc to bloc communication, Same as goes to cubit i guess that's right,

But they streams won't be listening within the cubit until i set the lazy to false while creating the MyCubit.
Strange it took 3 hours find what went wrong. 

`class MyBloc extends Bloc {
          final OtherBloc otherBloc;
         StreamSubscription otherBlocSubscription;

     MyBloc(this.otherBloc) {
        otherBlocSubscription = otherBloc.listen((state) {
        // React to state changes here.
        // Add events here to trigger changes in MyBloc.
         });
      }

         @override
        Future<void> close() {
         otherBlocSubscription.cancel();
           return super.close();
          }
      }`

  BlocProvider<ItemCreationCubit>(
                  lazy: false,
                  create: (context) =>

**Comment by felangel** [comment]
Hi @Puspharaj 👋 
Thanks for opening an issue!

Sorry for the inconvenience but yes, by default, `BlocProvider` only creates the bloc or cubit when it is requested so you need to set `lazy` to false if you want it to be instantiated immediately (even if there's no `BlocBuilder` or `BlocListener`).

Closing for now since it sounds like you were able to resolve the issue but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by Jayasubin** [comment]
I faced a similar problem while trying to listen to a cubit state from another. I expected the cubit to intialise as soon as this chained call like this:

`BlocProvider(
          create: (context) => ChatsCubit(
            authCubit: context.read<AuthCubit>(),
          )..listenToAuth(),
        ),`

 is encountered. But it didn't.

Setting lazy to false solves the problem, but isn't the chained function call considered as a request to the cubit.
