### ISSUE TITLE
Show side-effects without change data

### ISSUE THREAD

**Issue by furkanvatandas** [felangel/bloc#2200]
Hi Felix,

I got this code from https://github.com/felangel/fluttersaurus and modified it a little bit. 
I am not sure if it is a correct use? Or how can I use it cleaner?

I'm using ProcessStatus for BlocListener:
-> Show LoadingDialog for async methods 
-> Show ErrorDialog when get exceptions
-> Navigate other pages

While doing these, I also show the suggestions list. I don't want to change the main state(PageStatus). 
When the list refreshed, I don't want to change PageStatus just showing LoadingDialog on the screen.

```
enum PageStatus { initial, loading, success, failure }
enum ProcessStatus { initial, loading, success, failure }

class SearchState {
  final PageStatus pageStatus;
  final ProcessStatus processStatus;
  final List<String> suggestions;
  final bool isEditable;

  const SearchState._({
    this.suggestions = const [],
    this.pageStatus = PageStatus.initial,
    this.processStatus = ProcessStatus.initial,
    this.isEditable = false,
  });

  const SearchState.initial() : this._();

  const SearchState.loading()
      : this._(
          pageStatus: PageStatus.loading,
        );

  const SearchState.success({
    bool isEditable,
    List<String> suggestions,
    ProcessStatus processStatus,
  }) : this._(
          isEditable: isEditable,
          suggestions: suggestions,
          processStatus: processStatus,
          pageStatus: PageStatus.success,
        );

  const SearchState.failure()
      : this._(
          pageStatus: PageStatus.failure,
        );

  SearchState copyWithProcessSuccess({
    bool isEditable,
    List<String> suggestions,
    ProcessStatus processStatus,
  }) {
    return SearchState.success(
      isEditable: isEditable ?? this isEditable,
      suggestions: suggestions ?? this.suggestions,
      processStatus: processStatus ?? this.processStatus,
    );
  }
}
```

On the other hand, I can create PageStatus cases in separate classes.

```
abstract class SearchState extends Equatable {
  SearchState();
}

class SearchInitial extends SearchState {
  SearchInitial();

  @override
  List<Object> get props => [];
}

class SearchLoading extends SearchState {
  SearchLoading();

  @override
  List<Object> get props => [];
}

class SearchSuccess extends SearchState {
  final ProcessStatus processStatus;
  final List<String> suggestions;
  final bool isEditable;

  SearchSuccess(this.processStatus, this.suggestions, this.isEditable);

  @override
  List<Object> get props => [processStatus, suggestions];
}

class SearchError extends SearchState {
  @override
  List<Object> get props => [];
}
```

What I can't decide is that, even if my PageStatus fails in the first case still I can access other states, this seems to me wrong, but in the second case, I have to constantly check the

```
 final currentState = state
 if (currentState is SearchSuccess) {
```
in the cubit. The second case sounds more secure, but I don't know if it makes sense to check the situation in all methods.

How should we approach this kind of situation?

**Comment by Elias8** [comment]
Hello @furkanvatandas 👋, I think `BlocBuilder` and/or `BlocListnener` are what you are looking for. For the first case, using a `BlocBuilder` you can build a widget depending on some conditions by passing the condition to `buildWhen` parameter of the `BlocBuilder` itself. And for the second case, again you can use `BlocBuilder`, since it is inside another widget(class as you said) it will be built independently from the other `BlocBuilder`. 

Hope this helps.

**Comment by furkanvatandas** [comment]
Actually, I'm curious about which of the approaches I have written will be more correct. Although I showed the FailureScreen(PageStatus==Failure) in the first case, I can access other states like _isEditable_ or _suggestions_. Although I don't need to use this states.

**Comment by RobertHeim** [comment]
@furkanvatandas I feel you. I am also often confused about how to structure state in the BLoC pattern. The reason is, that the bloc pattern only defines how the communication between UI and the BLoC is build but it does not guide you in defining state (e.g. redux is more explicit about it).

Both of your approaches are fine as long as they meet the domain needs.  While most examples are very easy they can easily be implemented by subclassing different states (i.e. your second approach). From my experience, this is not as easy when state becomes more complex. In this situations I tend to build a single class for state per feature (i.e. your first approach and I start thinking about the state more like in redux). If you need access to specific parts of the state even if, for example, another field indicates a request-failure, you end up using `copyWith` a lot and probably will see constructors less often.

Remember that [state management is a complex topic](https://hackernoon.com/avoiding-accidental-complexity-when-structuring-your-app-state-6e6d22ad5e2a) and BLoC let's it more or less open to the developer's freedom and responsibility.

**Comment by felangel** [comment]
Hi @furkanvatandas 👋 
Thanks for opening an issue and sorry for the delayed response!

In my opinion, having multiple subclasses enforces a strict separation and is safer but it comes at the cost of more code and may be awkward in scenarios where "partial states" are supported (for example the feature can be in an error state but still presenting the previous data).

I think both approaches are ok and have their pros and cons (depending on the feature and requirements). See https://github.com/felangel/bloc/issues/1726#issuecomment-691763469 for more details. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
