### ISSUE TITLE
using cubit functions and states in Dialog

### ISSUE THREAD

**Issue by mehrdad78** [felangel/bloc#2215]
I want to use my cubit in a dialog but it throw an error and i can't use the cubit.
i have a FAB ,when user Tap on that i should show a dialog  and i want to use Bloclistener and Blocbuilderin that.
 the **Error**:

 `Could not find the correct Provider<AccidentCubit> above this BlocBuilder<AccidentCubit, AccidentState> Widget

This likely happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that BlocBuilder<AccidentCubit, AccidentState> is under your MultiProvider/Provider<AccidentCubit>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
  ```
`

**Comment by Elias8** [comment]
Hello @mehrdad78 👋, if you want to use a `bloc` on the same widget tree where you are creating the bloc using `BlocProvider`, checkout the `Builder` widget from flutter. It will give you a child `BuildeContext` in a `build` callback, so that you can use that context to read the `bloc` on the same widget tree.

Hope this helps.

**Comment by Elias8** [comment]
Hey @felangel, don't you think it would be better if we could add a `builder` param the same as a provider package so that people don't get into the same issue? 

I could do that and create a pr if you think it would be good to have that.  
Thanks!!

**Comment by felangel** [comment]
Hi @Elias8 👋 

I'd rather not encourage this pattern because ideally there should be a separation between the widget providing the object and the widget consuming the object. If the same widget provides and consumes the object then it is no longer possible to provide a mock instance for testing and developers will be forced to test the internal implementation details of the thing being provided. Hope that makes sense 👍

**Comment by felangel** [comment]
Hi @mehrdad78 👋 
Thanks for opening an issue!

I recommend providing the existing bloc to the Dialog using `BlocProvider.value`. You can see an example [here](https://bloclibrary.dev/#/recipesflutterblocaccess?id=anonymous-route-access).

Hope that helps 👍

**Comment by Elias8** [comment]
@felangel You are right. That actually makes sense 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍

**Comment by SebastianEngel** [comment]
Thank you @felangel, that helped 👍
