### ISSUE TITLE
Question about usage - Repository ConnectionString Parameters

### ISSUE THREAD

**Issue by yashhema** [felangel/bloc#2281]
Hello,
In our use case , connectionstring of the repository is dependent on scenarios.
So we are doing something like this --

class UserRepository
{
final String var1;
final String  var2;
final String  var3;
UserRepository(this.var1,this.var2,this.var3);
}

class UserBloc extends Bloc<UserEvents, UserState> {
  UserRepository _userRepository;
UserBloc(String var1,String var2, String var3)
{
_userRepository = new UserRepository(var1,var2,var3)
}
  
Do you see any issue with this kind of initiation . (We might have different BLOC with different repository existing at the same time , we initiate them and use providers to pass to widgets)

**Comment by yashhema** [comment]
Hello,
In our case , repository selection depends on user current selections  (which may be different in different screen) . If repository is not a good place , is it ok for BLOC to store these variables , and when we call repository methods , we pass those variables , if yes (or u see drawback for that) , can I just have them as final variable and initiatiate them during constructor.
regards

**Comment by felangel** [comment]
@yashhema sorry for the delayed response. You can maintain the state as part of a feature bloc and pass the relevant information to the repositories. It's hard to say without additional context.

> Is it ok , to destroy BLOC explicitly (not in widget dispose)

You can manually control the lifecycle of your blocs but if you decide to do that make sure to use `StatefulWidgets` to handle creating and closing the instances and I recommend not mixing that approach with `BlocProvider(create: (context) {...})` since the `BlocProvider` normally handles closing the bloc instance for you. You can still use `BlocProvider` with `BlocProvider.value` which will not automatically handle calling `close` for you 👍 

Hope that helps! Closing for now but feel free to comment with additional questions or [join the bloc discord](https://discord.gg/bloc) 😄
