### ISSUE TITLE
[Question] of BLOC usage or sharedpreferences?

### ISSUE THREAD

**Issue by scheung38** [felangel/bloc#2286]
Like to ask how to implement such flow with BLOC library:

After initial login, user is presented with a multi page questionnaire flow we use sharedpreferences or some other state management BLOC logic correct?

Idea is that first time Login  user is presented with  -> Q1 screen -> Q2 screen etc -> Landing Page and persisting to maybe FireStore, and only when user wants to do questionnaire again few months down the road, can optionally retake such assessment as it is rather long, (7 screens), or optionally if needing to retake again, can choose to do so.

So guarantee user performs  questionnaire at least once before using app.

So if user now closes and reopens app immediately again after login, will skip and goes straight to Landing Page. Any advice thanks

**Comment by felangel** [comment]
Hi @scheung38 👋 
Thanks for opening an issue!

I would recommend using [hydrated_bloc](https://pub.dev/packages/hydrated_bloc) because it will handle automatically caching and restoring your bloc's state. In this case you can maintain in your state a bool to indicate if the user is a first time user and once they have completed the assessment you can update the bool. If you bloc is a HydratedBloc, the next time the bloc is created, it will read the last state from cache and the user won't be presented the assessment.

Hope that helps! 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional questions or [join the bloc discord](https://discord.gg/bloc) to continue the conversation 👍
