### ISSUE TITLE
What's the best practice for error handling?

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#2318]
Having multiple `try {} catch {}` all over the places is painful to manage and it causes so many duplicate codes. I think it would be great if there's something central place for handling errors. I thought of using the `onError` callback but with this approach, I couldn't push new states.

I'm not sure if the creator had experience with the Node.js Express framework but I'd like to mention it because it does exactly what I want to have in Bloc. With Express, you can handle all errors in one place by calling `next(err)` wherever the error occurs.

Are there any ways to handle errors in one place and can push new states based on the errors?

**Comment by narcodico** [comment]
Hi @jezsung 👋

This is very subjective especially since most people want fine grained error handling because they need to react differently on case by case basis.
If your needs are more generic you can always override `onError` in your bloc and simply add an event which will handle any potential error/exception, assuming you removed all try catch blocs. States are user defined, same as events, so this is something you should manually handle.

As for node.js parallel, there's `addError` which you can call anywhere in your bloc to forward errors/exceptions to `onError`.

Alternatively you can take a look at using `Either` and `Task` from `dartz` package, they get rid of the need for try catch.

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions or [join the bloc discord](https://discord.gg/bloc) 👍
