### ISSUE TITLE
[Question]Why do we define a lot of states for state(data)? Such as LoginInitial, LoginLoading

### ISSUE THREAD

**Issue by fantasy525** [felangel/bloc#234]
Why do we define a lot of states for state(data)? Such as LoginInitial, LoginLoading?
I'm confused about state.
For the login page.I might just need a username and password
```dart
enum LoginPageEvent{
  login,
  logout
}
class LoginPageState{
  String name;
  String pwd;
  void mapEventToState(LoginPageEvent event){
    if(event == LoginPageEvent.login){
      name = 'jack';
      pwd = '12345';
    }
  }
}
```
I mean: name and pwd are state,state to UI.

**Comment by felangel** [comment]
Hi @fantasy525 👋 
Thanks for opening an issue!

Regarding you question, if you think about the feature as a [state machine](https://en.wikipedia.org/wiki/Finite-state_machine#/media/File:Turnstile_state_machine_colored.svg) then you need to define all the possible states that the state machine can be in. For login they would be `initial`, `loading`, `failure`, and `success` (in a basic example).

With the representation you have included, there is no way to indicate to the presentation layer that can action is processing in order to show some sort of loading/progress indicator to the user. Hope that helps 👍
