### ISSUE TITLE
A lot of breaking changes

### ISSUE THREAD

**Issue by Valentin-Seehausen** [felangel/bloc#2388]
Hey @felangel, 👋🏻

I really like this library and I am really impressed by your coding skills and by the effort you put into this. This is without doubt one of the most important libraries in the flutter space.

I realized, that I spend most of the time I have to put into the maintenance of my app with the breaking changes of the bloc library and its siblings (last one mocktail). So this library not only helps me most but also needs the most time. 

There is no request or proposal, but I just wanted to raise this and hear your thoughts on it.

Thanks again for your great work! 🙏🏻

**Comment by felangel** [comment]
Hi @Valentin-Seehausen 👋 
Thanks for opening an issue!

It would be really helpful if you could provide more information regarding which breaking changes you spent the most time on. 

Unfortunately, switching to `mocktail` was done out of necessity due to null safety support (see https://github.com/dart-lang/mockito/issues/286 and https://github.com/dart-lang/mockito/issues/347). Without `mocktail` it would not have been possible to support the existing `blocTest` api when it came to mocking and there would have likely been much larger breaking changes involving code generation.

I have tried my best to provide [migration guides](https://bloclibrary.dev/#/migration) to walk through all breaking changes and explain why they were made and how to upgrade. I hope that helps and I apologize for any inconvenience!

**Comment by Valentin-Seehausen** [comment]
Hey @felangel,

thank you very much for your kind answer.

I don't think there are breaking changes that need more work than others but in sum, it's just a lot. Nothing more. The migration guides are very good. 🙏🏻

**Comment by felangel** [comment]
@Valentin-Seehausen I'm sorry to hear that and I understand how you feel -- migrating large applications to null safety is fairly challenging. If you haven't already, I highly recommend joining the [bloc discord](https://discord.gg/bloc) and you can post any questions/challenges you have when migrating (failing tests, weird errors, etc.) and I'm sure the community will be able to help 👍 

Closing for now since there doesn't appear to be any actionable items, thanks! 🙏
