### ISSUE TITLE
Calling BlocBuilder in a listview returning the last value

### ISSUE THREAD

**Issue by Moswag** [felangel/bloc#2391]
I am getting a list of accounts from a bloc and from that list i am going to fetch the account balance from another endpoint which i created the bloc for, the problem now is the balance is being updated to the last response, what i need is for the the widget not to be rebuild after the state changes.

Here is my code

class AccountBalance extends StatefulWidget {
  @override
  _AccountBalanceState createState() => _AccountBalanceState();
}

class _AccountBalanceState extends State<AccountBalance> {
  BankCardBloc _bankCardBloc;
  AccountBalanceBloc _accountBalanceBloc;

  void getUserAccounts(String customerId) {
    _bankCardBloc.add(GetUserAccounts(customerId: customerId));
  }

  void getAccountBalance(String accountNumber) {
    _accountBalanceBloc.add(GetAccountBalance(accountNumber: accountNumber));
  }

  void getAccountListing() {
    getCurrentUser().then((AuthResponse authResponse) => getUserAccounts(authResponse.customerId));
  }

@override
  void initState() {
     _bankCardBloc = BlocProvider.of<BankCardBloc>(context);
    _accountBalanceBloc = BlocProvider.of<AccountBalanceBloc>(context);
  }

  @override
  Widget build(BuildContext context) {
    getAccountListing();

    return Scaffold(
      appBar: topBar("Balance"),
      body: BlocBuilder<BankCardBloc, BankCardListState>(
        builder: (context, state) {
          if (state is Loaded) {
            print(state.accountDetailsList.toString());
            return _buildBody(state.accountDetailsList);
          }
          if (state is Error) {
            print(state.message);
            return error(state.message);
          }
          return loading(context);
        },
      ),
    );
  }

  Widget _buildBody(List<AccountDetails> bankAccounts) {
    return Container(
        child: ListView.builder(
            itemCount: bankAccounts.length,
            itemBuilder: (BuildContext context, int index) {
              getAccountBalance(bankAccounts[index].accountNumber);

              return BlocBuilder<AccountBalanceBloc, AccountBalanceState>(
                  bloc: _accountBalanceBloc,
                  builder: (context, state) {
                    if (state is AccountBalanceLoaded) {
                      return BalanceCard(
                          balanceResponse: state.balanceResponse);
                    } else {
                      return loading(context);
                    }
                  });
            }));
  }

  @override
  void dispose() {
    super.dispose();
  }
}

**Comment by II11II** [comment]
@Moswag If i understood you problem correctly, you should override buildWhen field in BlocBuilder

**Comment by felangel** [comment]
Hi @Moswag 👋 
Thanks for opening an issue!

Can you explain why you don't want the list to update when the state changes? The main purpose of `BlocBuilder` is to rebuild the a portion of the UI when the bloc state changes. Thanks 👍

**Comment by Moswag** [comment]
I have a list of accounts i am holding, i need to get account balances for those accounts, so in my listview i am making a call to the backend to get balances for each account. In the listview i added BlocBuilder to do that, i realised each time a new balance comes, all other accounts already loaded in the listview are updating their balances to the latest one

**Comment by II11II** [comment]
Hi @Moswag 👋 

BlocBuilder rebuilds each time when new state is emitted.

In your case, i would wrap the child of listview or filter information in bloc.

**Comment by Jaykocha** [comment]
Hi @II11II, @felangel 
I have a similar issue to @Moswag .  I am still a beginner with bloc but worked through the tutorials and implemented about 10 different blocs/cubits successfully. 

So I have a Listview.builder as well and I want to display an Avatar for each user in my friends' list. 
The "final" states can be either DisplayFromLocal, DisplayFromNetwork, or DisplayPlaceholder.  But the behaviour I am observing is that the last emitted state is being applied to all Avatars.  
With one person in friends list it all works perfectly. 

My code looks basically like that (simplified): 

```
ListView.builder(
     itemCount: friends.length,
     itemBuilder: (context, index) {
         return Column( children: [
             Avatar( 
             keyString: friends[index].key,
             category: AvatarCategory.friend),
             Text(friends[index].value["name]) // This works as supposed to and
              //shows different name for different friend
         ]);
      }
)
```
Where my class Avatar looks as such:

```
class Avatar extends StatelessWidget {
  Avatar({this.keyString, required this.category});

  final String? keyString;
  final AvatarCategory category;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<PhotoFlowCubit, PhotoFlowState>(
      builder: (context, state) {
      if (state is CheckIfPhotosExistsLocally) {
        context.read<PhotoFlowCubit>().checkIfPhotoExistsLocally(keyString, category);
        return circleAvatarLoading(context);
      }
      if (state is DisplayPlaceholderPhoto) {
        return circleAvatarPlaceholder(context);
      }
      if (state is DisplayPhotoFromLocal) {
        return circleAvatarLocally(context, state.path);
      }
      if (state is DisplayPhotoFromNetwork) {
        return circleAvatarNetwork(context, state.path);
      } else {
        return circleAvatarPlaceholder(context);
      }
    });
  }
```
I am using a Cubit to handle the logic, which looks like that (don't think the problem is here):

```
class PhotoFlowCubit extends Cubit<PhotoFlowState> {
  PhotoFlowCubit(this._storageRepository) : super(CheckIfPhotosExistsLocally());

  StorageRepository _storageRepository;
  late Directory _appDirectory;

  Future<void> checkIfPhotoExistsLocally(
      String? idString, AvatarCategory category) async {
    _appDirectory = await getApplicationDocumentsDirectory();
    if (idString == null) {
      emit(DisplayPlaceholderPhoto());
    } else if (File('${_appDirectory.path}/$idString.jpg').existsSync()) {
      emit(DisplayPhotoFromLocal('${_appDirectory.path}/$idString.jpg'));
    } else {
      switch (category) {
        case AvatarCategory.group:
          await checkIfPhotoExistsOnStorageAndGetDownloadUrl(
              path: 'groups/$idString/$idString');
          break;
        default:
          await checkIfPhotoExistsOnStorageAndGetDownloadUrl(
              path: 'users/avatars/$idString');
          break;
      }
    }
  }

  Future<void> checkIfPhotoExistsOnStorageAndGetDownloadUrl(
      {required String path}) async {
    String? downloadUrl =
        await _storageRepository.checkIfFileExistsOnStorage(path: path); //returns null if no photo exists
    if (downloadUrl != null) {
      emit(DisplayPhotoFromNetwork(downloadUrl));
      downloadPhotoToLocalStorage(downloadUrl);
    } else {
      emit(DisplayPlaceholderPhoto());
    }
 }

```
I am struggling a bit where the problem could be :/. I think I am lagging some general understanding here. Do you have any idea, what could be the reason?

**Comment by II11II** [comment]
Hi @Jaykocha 👋
Can you share your state code, please?

**Comment by II11II** [comment]
@Jaykocha Before seeing your state code, i predict that you do not have List for your photos, but instead of it, you have single parameter which saves last image

**Comment by Jaykocha** [comment]
you are absolutely right! :D

part of 'photo_flow_cubit.dart';

```
abstract class PhotoFlowState extends Equatable {
  const PhotoFlowState();

  @override
  List<Object> get props => [];
}

class CheckIfPhotosExistsLocally extends PhotoFlowState {}

class CheckIfPhotoExistsOnStorage extends PhotoFlowState {
  final String path;
  CheckIfPhotoExistsOnStorage(this.path);
}

class DisplayPhotoFromLocal extends PhotoFlowState {
  final String path;

  DisplayPhotoFromLocal(this.path);
}

class DisplayPhotoFromNetwork extends PhotoFlowState {
  final String path;

  DisplayPhotoFromNetwork(this.path);
}

class DisplayPlaceholderPhoto extends PhotoFlowState {}
```

For sure the problem is here. But not sure how to fix it

**Comment by II11II** [comment]
@Jaykocha Change all fields ```String path;``` to ```List<String> paths;```  in state class and override props field adding ```paths``` field in props ;

**Comment by Jaykocha** [comment]
Thank you a lot! It is already way better in the sense that if all photos exist at the same location, for example for every user there exists a photo on storage, it now shows the different photos. But unfortunately if for one id a photo exists on storage and for the other one it does not, still both try to DisplayPhotoFromNetwork beacuse the state still is the same. I guess it is because the Cubit cannot have 2 different states at the same time, which makes sense. So I should probably introduce an enum called f.e. 'Status' and use List<Map<String, Status>> and build according to status. 

So that when all operations are done I have a List like that: [{localPath : Status.localPath}, {networkUrl : Status.networkImage}]. (for two friends, one with local picture one with picture on storage).

I basically would only have two States: StartLoadingImages and DoneLoadingImages. Then return my AvatarWidgets according to 'Status' and 'Path'. 

I am gonna make it work now but not sure if I am even gonna keep it like that, feels kind of messy. Can you tell me how you would do it? If you had to display photos according to a List of Ids and then first check locally, then on storage, and if both fails display a placeholder image? And I have to do it again for other categories like groups.  

Probably one should just use this cached_network_image package, make a database entry for the URL, and in Cubit just check if they have uploaded or changed their photo and modify database accordingly while showing either old photo from cache or placeholder until a new one is downloaded.  I am gonna test it both and then I will see. But thanks again, for putting me on the right track!

**Comment by II11II** [comment]
@Jaykocha In your case, I would use Hydrated bloc because it can save state and restore it when app relaunched.
About state structure, if you need to save list<photos> in each state change you need create field in state logically, but there is another solution. I would create such kind of state:
``` 
enum NetworkState{INITIAL,LOADING,SUCCESS,FAILURE}
class MyState extends Equtable{
final List<User> userList;
final NetworkState networkState;
// and other needful fields
MyState({this.userList=const [],networkState=NetworkState.INITIAL});
MyState copyWith({List<User>? userList,NetworkState ?networkState}){
return MyState(networkState:networkState??this.networkState,userList:userList??this.userList);
}
List<Object> props=[networkState,userList,/* other fields*/];
}
