### ISSUE TITLE
Should repositories return Bloc's states?

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#2425]
I'm wondering what's the best practice for handling communication between Blocs and repositories. Here's my thoughts and solutions.

1. Repository returns a Bloc's state. Repository takes all the responsibilities to convert the HTTP response to a correct Bloc's state.

2. Repository returns a Model that matches the HTTP response JSON model and Bloc state has that model as its property.

3.  Repository returns a Model that matches the HTTP response JSON model and the Model will be converted to a Bloc state.

Which one is the best? Please suggest me if there's better solution. Thanks!

**Comment by Gene-Dana** [comment]
Good question.. @narcodico, are there any suggestions you would have here?

**Comment by felangel** [comment]
Hi @jezsung 👋 
Thanks for opening an issue!

I would recommend having your repository return a model which is independent of the http response. Ideally, the repository layer should be the abstraction over the data layer so that you can easily switch underlying data providers and not have to change your application layer or the public api surface of the repository. I would advise against having repositories return bloc states because repositories should be more domain driven whereas blocs should be more feature driven. A single repository can be used by multiple features and even across multiple applications/clients.

Hope that helps! Closing for now but feel free to comment with additional questions or join the [bloc discord](https://discord.gg/bloc) 👍

**Comment by narcodico** [comment]
@Gene-Dana I think @felangel 's answer is on point. I personally like to keep layers as separated as possible, in terms of models too and I always convert models in the upper layer, since dependencies should flow from lower layers to upper ones and never the other way around.
