### ISSUE TITLE
Problem in one bloc to multiple screen

### ISSUE THREAD

**Issue by GaneshSingaravelu** [felangel/bloc#2435]
Hi,

Below I have mentioned my requirements and issue details and I have made a sample application and attached the same here. Please do the needful

**Demo Project Attached**
[demoapp.zip](https://github.com/felangel/bloc/files/6409410/demoapp.zip)

**Requirement**

I need to use the same bloc (Signup bloc) in two pages (Register Account & complete profile)
I need to maintain the state/instances on the two pages (either push or pop the page)

**Issue**

The values get removed, whenever I have entered the value on the second page.
My values are empty on the screen When I go back to the first page "Complete Profile" from the second page "Sign up". But values remain in the state and not shown on the screen.

**Doubt**

If I declare more blocs globally then will it impact the performance of my app?

Thanks

**Comment by felangel** [comment]
Hi @GaneshSingaravelu 👋 
Thanks for opening an issue!

If you want to have a single bloc provide state to multiple screens you can follow the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess).

I would always recommend scoping the bloc as low as possible in the widget tree rather than providing the bloc globally unnecessarily 👍 

Hope that helps! Closing for now but feel free to comment with additional questions and/or join the [bloc discord](https://discord.gg/bloc) 😄
