### ISSUE TITLE
Make ignoring equal states configurable

### ISSUE THREAD

**Issue by dmorawetz** [felangel/bloc#2509]
**Is your feature request related to a problem? Please describe.**
My app gets notified by an event from my API which in turn emits a new state. It's possible, that the state will be equivalent to the last. Emitting the state causes another part of the UI to refresh data. It would be nice, if I could configure my bloc to also emit states, even if they equal the last.

**Describe the solution you'd like**
Maybe add an optional parameter to BlocBase constructor to configure this behaviour?

**Describe alternatives you've considered**
My current workaround is to have a field in my state that i set to a random value just so the bloc thinks it's different.

**Comment by felangel** [comment]
Hi @dmorawetz 👋 
Thanks for opening an issue!

The reason why bloc doesn't allow emitting duplicate states is because by definition a state change shouldn't occur when there is no change. It's up to you as a developer to determine how equality is defined. For example, if you just use plain objects then each new state instance will be treated as unique and will be emitted. If you choose to use Equatable or override `==` and `hashCode` you're in full control over how equality is determined.

Hope that helps! Closing for now but feel free to comment with any additional questions/comments or [join the bloc discord](https://discord.gg/bloc) 👍

**Comment by dmorawetz** [comment]
Thanks for your response. I always use freezed with bloc and became blind to the obvious 😅

**Comment by ndson040496** [comment]
@felangel I'm working with a rather complex object, I just want to modify the state directly and emit it again. As far I know, I have these options:
1. Making a clone of state, modifying, and emitting the clone.
2. Overriding == to make it always false (I don't like this one).

I think providing an option to dictate this behavior is still a good addition. Or if you have a better solution, please share it.
Thank you
