### ISSUE TITLE
[HydratedBloc]Send token from Auth HydratedBloc to Interceptor

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2518]
I am using HydratedBloc for Auth Feature and I save token in AuthState as well in its Database.
I am thinking about how to get a properly and correctly token in Interceptor.

P.s. I can pass the token from UI to BLOC->REPOSITORY->REMOTE-DATA-SOURCE and make a request. However, it is not a clean code.
  
Can you suggest  clearer way?

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

I would highly recommend avoiding that flow because it violates the unidirectional data flow (data provider -> repository -> bloc -> ui).

I would highly recommend using [fresh_dio](https://pub.dev/packages/fresh_dio) to manage your token so that the token management stays scoped within the networking layer. Bloc should manage feature state and features generally should not know (or care) about auth tokens.

Hope that helps! Closing for now but feel free to comment with additional questions or [join the bloc discord](https://discord.gg/bloc) and I'm happy to continue the conversation 👍
