### ISSUE TITLE
Get a scoped instance from BlocProvider

### ISSUE THREAD

**Issue by AndreGroeschel** [felangel/bloc#2529]
We are using Bloc extensively in our app and due to testing reasons, all Blocs get injected via Multi Bloc Provider. We have things like Stream subscriptions in each constructor of the Bloc and dispose them in `close()`. On the presentation layer, each page is a StatefulWidget and we call each Bloc's `close `method in the Widget's `dipose `method. 
We found that the instances created by BlocProvider are in fact Singletons and no new instances get created after calling `close`. Each Bloc's constructor is only called a single time

**Describe the solution you'd like**
It would be cool if BlocProvider could create something like a scoped instance. I.e. each time when entering a page, a fresh instance is provided if the previous one is already closed

**Describe alternatives you've considered**
At the moment, we are using the `injectable `package along with `getit ` to create a Bloc instance in the StatefulWidget's `init `method and in `dispose`, the Bloc's `close `method gets called

**Comment by felangel** [comment]
Hi @AndreGroeschel 👋 
Thanks for opening an issue!

Since `BlocProvider` uses `package:provider` internally, the behavior you are describing is consistent with `package:provider`. I would advise against providing all blocs globally -- if instead, each bloc was provided only to the sub-tree where it is needed, then each time `BlocProvider` is unmounted, it will automatically `close` the bloc instance and each time you mount `BlocProvider` it'll create a new instance. I would recommend relying on `InheritedWidget` (through `BlocProvider` instead of `get_it` when it comes to injecting bloc instances into the widget tree.

> due to testing reasons, all Blocs get injected via Multi Bloc Provider.

You should be able to easily test blocs which are injected lower in the subtree (refer to most of the [examples](https://github.com/felangel/bloc/tree/master/examples)).

Let me know if that helps 👍 

Hope that helps 👍

**Comment by AndreGroeschel** [comment]
Thx for clarifying! An interesting approach that we haven't thought about.

So if I understand this correctly, every of our "page" widgets needs to get wrapped with an extra layer of `BlocProvider`. And then when navigating from location to location the `BlocProvider `gets mounted/unmounted right?

**Comment by felangel** [comment]
> Thx for clarifying! An interesting approach that we haven't thought about.
> 
> So if I understand this correctly, every of our "page" widgets needs to get wrapped with an extra layer of `BlocProvider`. And then when navigating from location to location the `BlocProvider `gets mounted/unmounted right?

Yes, that's correct! I highly recommend looking through the [weather example](https://github.com/felangel/bloc/tree/master/examples/flutter_weather), [firebase login example](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login), and [fluttersaurus](https://github.com/felangel/fluttersaurus) for reference 👍

**Comment by AndreGroeschel** [comment]
Cool! Thanks for your support!!
