### ISSUE TITLE
The event field is needed in callbacks of Bloclistener and BlocBuilder widget

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2547]
Depending on the event of bloc in ```buildWhen , listenWhen , builder ,listerer``` callbacks, ui can be built easily and programmer can have more control while rebuilding or showing dialog

Moreover, there will no need to create some extra bloc. 

The scenario when this feature is needed:
When one bloc or cubit responds to get data and upload data while saving the state of gotten data. 

**Describe the solution you'd like**
```
 BlocBuilder<Cubit, State>(
            buildWhen: (previous_state, current_state,previous_event,current_event) {
             // here code logic when to build depending on states or/and events
            }
             
            builder: (context, state, event) {
            // build widget depending on state or/and event
            }
 )
            
```
```
 BlocListener<Cubit, State>(
            listenWhen: (previous_state, current_state,previous_event,current_event) {
            // here code logic when to listen depending on states or/and events
            }
             
            listener: (context, state, event) {
            // listen widget depending on state or/and event
            }
 )
            
```

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

By definition, the UI should only react to state changes. If we also expose the previous and current event then we are violating the BLoC pattern (events in and states out). Furthermore, since you are in control of the state you can make sure to include all relevant information needed as part of the state.

For those reasons, I strongly advise against this pattern and am closing this issue but feel free to comment with additional information/concrete use-cases and I'm happy to continue the discussion 👍
