### ISSUE TITLE
Bad state: Cannot add new events after calling close in BottomNavigationBar

### ISSUE THREAD

**Issue by TahaMalas** [felangel/bloc#256]
I'm trying to make something like a BottomNavigationBar with multiple fragments up to 4 fragments, and I figured that each fragment must have its own BLoC. But the problem is when trying to load the fragment for the second time it crashes and fails to get the data throwing this exception.

`Unhandled Exception: Bad state: Cannot add new events after calling close`

For reference I'm trying to inject my BLoC class inside the screen using Kiwi injection framework using the following code:

```
void initKiwi() {
  Kiwi.Container()
    ..registerInstance(Dio(BaseOptions(
        connectTimeout: 30,
        responseType: ResponseType.json,
        baseUrl: 'http://192.168.1.100:8000/api/')))
    ..registerSingleton((c) => HttpHelper(c.resolve()))
    ..registerSingleton((c) => PrefsHelper())
    ..registerSingleton((c) => DatabaseHelper())
    ..registerSingleton(
        (c) => Repository(c.resolve(), c.resolve(), c.resolve()))
    ..registerFactory((c) => AppBloc(c.resolve()))
    ..registerFactory((c) => ProductsBloc(c.resolve()))
    ..registerFactory((c) => LoginBloc(c.resolve()));
}
```
And here is my 'fragment' code 
```

class Products extends StatefulWidget {
  final _bloc = kiwi.Container().resolve<ProductsBloc>();

  @override
  _ProductsState createState() => _ProductsState();
}

class _ProductsState extends State<Products> {
  @override
  void initState() {
    widget._bloc.getProducts();
    super.initState();
  }

  @override
  void dispose() {
    widget._bloc.dispose();
    super.dispose();
  }
}
```

Is there something wrong in my workflow that I must change in order to overcome this issue.

**Comment by felangel** [comment]
Hey @TahaMalas 👋 
Thanks for opening an issue!

This means that your bloc still had some events that were being processed after you called dispose. It's not really a big deal in terms of user experience (no one will ever know while using your app) but it's more for you as a developer to be aware that you dispatched some events, they were being processed, you called dispose, and then they finishing being processed.

I am currently thinking of adding a `drain` api on the bloc so that you can `await bloc.drain()` before calling `bloc.dispose()`. Awaiting `bloc.drain()` would wait for all events to finish being processed so that you only dispose the bloc when the streams are empty. 

It's still up for discussion so I would love any feedback you have and thanks again for bringing this up.
👍
