### ISSUE TITLE
[Question] Passing Bloc through constructor

### ISSUE THREAD

**Issue by BaranMichal25** [felangel/bloc#2595]
The [documentation](https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/lib/src/bloc_builder.dart#L36) of BlocBuilder states:
```
Only specify the [bloc] if you wish to provide a [bloc] that is otherwise not accessible via [BlocProvider] and the current BuildContext
```
I'm curious: why?

I mean, assuming I have a BlocProvider, then using BlocBuilder in this way seems convenient for me, but I just wonder whether there are any _technical_ reasons behind it (perf, problems) ?

Which would justify that we shouldn't be passing bloc instance via constructors to children of a given screen (widget), because actually some bad things may happen, other than writing more code / style issues.

**Comment by felangel** [comment]
Hi @BaranMichal25 👋 
Thanks for opening an issue!

There's nothing inherently wrong with passing blocs via constructor -- the main drawback is prop-drilling and making sure you don't forget to close the bloc. The documentation is stating that you should avoid specifying the `bloc` if it's already available via the current `BuildContext` because the lookup will be automatically performed internally for you.

If you don't have a `BlocProvider` which provides the bloc instance then you should explicitly specify the `bloc` in order for the `BlocBuilder` to know which bloc to subscribe to. Hope that helps 👍

**Comment by BaranMichal25** [comment]
Thanks for detailed response, that answers my question! :)
