### ISSUE TITLE
[Best Practice] can you make a best practice documentation of using flutter_bloc with various conditions?

### ISSUE THREAD

**Issue by robyhuzwandar** [felangel/bloc#2603]
best practice usage of various usage, for example, 
1. May I call `context.read<XxBloc>().functionXx();` inside the build method in StatelessWidget
2. May I create a logic function and call directly without change state, for example;

```
BLoC class
.
.
void xxxFunction(){
    //logic   
     return  xx;
}
.
.
```
and call directly on the UI :
`final foo = context.read<XxBloc>().xxxFunction();`

etc. 
Thanks

**Comment by felangel** [comment]
Hi @robyhuzwandar 👋 
Thanks for opening an issue!

I would highly recommend reading through the [core concepts](https://bloclibrary.dev/#/coreconcepts) but to answer your question I would advise against doing that. Blocs should react to events and emit states in order to keep your application reactive and to maintain a consistent, predictable approach to managing your application state. You can use cubit with a similar approach to the one you're describing but you should always emit new states rather than directly returning data:

```dart
void xxxFunction() {
  // logic
  emit(newState);
}
```

Then from the use you can call the method directly on the cubit:

```dart
context.read<MyCubit>().xxxFunction();
```

And react to state changes in the cubit via `BlocBuilder`, `BlocListener`, etc.

Hope that helps 👍 

Closing for now but feel free to comment with any additional questions or [join the bloc discord](https://discord.gg/bloc).
