### ISSUE TITLE
Why i am getting this error "Bad state: Tried to read a provider that threw during the creation of its value."

### ISSUE THREAD

**Issue by robinchauhan5000** [felangel/bloc#2642]
**Describe the bug**

```
Bad state: Tried to read a provider that threw during the creation of its value.
The exception occurred during the creation of type QuizBloc.

The relevant error-causing widget was: 
  MaterialApp file:///C:/Users/robin/AndroidStudioProjects/bloc_quiz/lib/main.dart:15:14
When the exception was thrown, this was the stack: 
#0      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:661:7)
#1      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:544:33)
#2      Provider.of (package:provider/src/provider.dart:289:29)
#3      BlocProvider.of (package:flutter_bloc/src/bloc_provider.dart:100:23)
#4      _QuizScreenState.initState (package:bloc_quiz/presentaion/screens/quiz_screen.dart:22:18)
```

I just want to get data in my QuizScreen.dart and when I run the app I am getting this error. I tried to figure out the solution but failed and also googled but could not find any solution. Please could you help to solve this issue. Could tell me what I am doing wrong.

**Expected behavior**
I want to get the data to my QuizScreen.dart. So I can implement the other functionality. But initially check, I started getting this error.
.
**Repo Link**
[](url)https://github.com/robinchauhan5000/Bloc_quiz

**Additional context**
I really want to learn flutter_bloc and I have been practising by building small projects. With the flutter_bloc I was able to easily make an API request and able to use Firebase Auth properly. 

@felangel Could you provide us with more learning resources and more projects or video tutorials. It would be really helpful and
thank you for this great library.

**Comment by elianmortega** [comment]
Hello @robinchauhan5000 , I cloned the repo to find out what was going on.

The main line causing the issue is 
`QuizModel _quizModel = QuizModel();`

I'll recommend checking your model, also I saw that you are not  on latest dart null-safety, I'll recommend upgrading your dart/flutter sdk as that is the current standard.

Regarding the learning resources, there are plenty of step to step examples in the [bloc library dev website ](https://bloclibrary.dev/#/) you should check them  out and do them step by step so you learn the best practices when using flutter bloc.

Also reading the architecture segment of the docs helps a lot [architecture](https://bloclibrary.dev/#/architecture)

**Comment by robinchauhan5000** [comment]
@elianmortega Thanks for your reply. Yes, because of my model class I was getting errors. But still struggling to get that data in my Quiz Screen, Now there is no error but the app is in LoadingState. Because it couldn't get that data inside which inside model. 
**Could you tell me where I should pass that model because when I pass that mode through QuizBoc, I still get the same error.**

I did the same with API calls and I was able to achieve the task.  I didn't get that error. 
Please could you guide me?

I have read the documentation and examples, but It would be great to see more examples and video tutorials and a special  Bloc course by @felangel would be amazing. Also if it is possible to create an official group on social apps (like telegram) where people can share problems and projects in which they have used the Bloc Library.


`class QuizBloc extends Bloc<QuizEvent, QuizState> {
  QuizBloc({QuizModel quizModel}) : assert(quizModel != null), _quizModel = quizModel,
  super(QuizInitialState());

  QuizModel? _quizModel;
  List<QuizModel>? quizListModel;
  @override
  Stream<QuizState> mapEventToState( QuizEvent event, ) async* {
    print(_quizModel?.data.length);
    yield QuizLoadingState();
    quizListModel = _quizModel?.data;

    if (state is QuizLoadedEvent) {
      yield QuizLoadedState(quizListData: quizListModel);
    }

    if (event is SelectOptionEvent) {
      
    }
  }
}`

**Comment by felangel** [comment]
Hi @robinchauhan5000 👋 
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? I'm happy to take a closer look and open a pull request with suggestions. 

> Also if it is possible to create an official group on social apps (like telegram) where people can share problems and projects in which they have used the Bloc Library.

You can join the [bloc discord server](https://discord.gg/bloc) to chat with the bloc library community 👍

**Comment by robinchauhan5000** [comment]
Thank you @felangel for your response and for the library.

> The main line causing the issue is
> `QuizModel _quizModel = QuizModel();`

I was getting an error in my because of my model class as pointed out in the first response. I want to know how should I pass that model because that model contains temporary data inside. When I pass that model, I get the error below. I wanna know the right way to do it

> Bad state: Tried to read a provider that threw during the creation of its value.
The exception occurred during the creation of the type QuizBloc.


[](url)https://github.com/robinchauhan5000/Bloc_quiz/blob/master/lib/models/quiz_model.dart

[](url)https://github.com/robinchauhan5000/Bloc_quiz/blob/master/lib/bloc/quiz_bloc.dart

> QuizBloc({QuizModel? quizModel}) : assert(quizModel != null),
        _quizModel = quizModel,
        super(QuizInitialState());

>  QuizModel? _quizModel;
  List<QuizModel>? quizListModel;

I really want to use flutter_bloc in my project.

**Comment by Gene-Dana** [comment]
Hi there ! I fully understand where you are coming from when you **need** more examples ! I literally live off of them! 

So the first thing I noticed is you are looking to access the `List<QuizModel> data` from your bloc, and although you have it in the Quiz model file,  your model itself doesn't quite provide it ! 

Rather than keep this list in your model, I'd suggest you add this list of quiz models directly to the state of your quiz_bloc in quiz_state, just like I added a list of questions to my question_state[ in this example ](https://github.com/Team-Crushing-It/wine_game_admin/blob/f8de5d239f8b0543fc45294b3eba407c6e2fa1db/lib/home/_features/questions/cubit/question_state.dart#L51) 

Feel free to study this example more. You can visit it live [at this link](https://firestore-bloc-crud-demo.netlify.app/#/). Go ahead and add, update or delete to your hearts content to see how everything works - I made it for this purpose :D

If you have any additional questions please ask them here or on the discord link that Felix provided above !

**Comment by robinchauhan5000** [comment]
@Gene-Dana @felangel   Thank you for your help and for sharing the repo. I understood now. Thank you all for your Quick Response.
> If you have any additional questions please ask them here or on the discord link that Felix provided above !

Sure, I have joined the group, now I will be getting updates there and find more sample projects to advance my knowledge about the library.

Thank you.
