### ISSUE TITLE
docs: [Question] related to State

### ISSUE THREAD

**Issue by miriam-z** [felangel/bloc#2682]
**Description**

Clearly describe what documentation you are looking to add or improve.

I have an audio recording, but everything I stop and playback, it is playing the previous audio, and not the just recorded audio. 

Is it related to state not saved or managed properly. I know I dont have concrete example but could this be better managed by bloc logic?

**Comment by felangel** [comment]
Hi @miriam-z 👋 
Thanks for opening an issue!

It's hard to say without having a minimal reproduction sample but in theory yes this type of state can be managed pretty easily with bloc since you can represent the audio recording and playback using a state machine (similar to the [timer example](https://github.com/felangel/bloc/tree/master/examples/flutter_timer)).

Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍
