### ISSUE TITLE
'A build function returned null' but all the build fonction return a widget

### ISSUE THREAD

**Issue by MichelMelhem** [felangel/bloc#269]
Hello,
I encounter some issue with the BlocBuilder widget,
First of all this is my BlocBuilder,
```
import "package:flutter/material.dart";
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:smartwork/src/blocs/Auth.bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:smartwork/src/components/form/LoginForm.dart';
import 'package:smartwork/src/pages/Loading.dart';
import 'package:smartwork/src/states/Auth.state.dart';

class SignInPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: BlocBuilder(
        bloc: BlocProvider.of<AuthBloc>(context),
        builder: (BuildContext context, AuthState state) {
          if (state.auth == false) {
            return Center(
                child: FlatButton(
              child: Text("Test"),
              onPressed: () {
                BlocProvider.of<AuthBloc>(context)
                    .authRequest("_email", "_password");
              },
            ));
          }
          if (state.isFetching == true) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
        },
      ),
    );
  }
}

```
My issue is when the state isFetching go to true i succefuly get the CircularProgressIndicator() when when the isFetching go to false i get the 'A build function returned null' error.
The blocBuilder is supposed render FlatButton() beacause the auth state is equal to false;
Thank you in advance for your help

Ps: it will be nice if you open a discord for the community of this lib

**Comment by felangel** [comment]
Hi @MichelMelhem 👋 
Thanks for opening an issue!
We have a [gitter](https://gitter.im/bloc_package/Lobby) which you can join. If you think it would be valuable to have a discord in addition please let me know.

Regarding your question,
It looks like in your example if `state.auth` is `true` and `state.isFetching` is `false` then BlocBuilder returns null which is why you're seeing an exception. You need to make sure that BlocBuilder always returns a widget.

Hope that helps 👍
