### ISSUE TITLE
Updating state directly

### ISSUE THREAD

**Issue by altherat** [felangel/bloc#270]
I'm not too too familiar with Dart/Flutter/BLoC, but I'm finding it a bit tedious having to create specific classes (often entirely empty) for each event you want to `dispatch` to a bloc and then checking the type of the event in the `mapEventToState` method. It's also unfortunate because IDEs won't hint which concrete classes can be accepted by the `dispatch` method.

It might be a good idea to allow more flexibility to `Bloc`s by allowing subclasses to directly update the state through some protected `updateState` method or something, instead of having to go through `mapEventToState`. Then we could define our own methods in our blocs (which are effectively the same as events), and then these methods could update the state directly. Maybe this violates the pattern or the standards this library wants to uphold, but you could have this functionality in some `OtherBloc` and then users could choose which style they want to use by subclassing either `Bloc` or `OtherBloc`.

**Comment by felangel** [comment]
Hi @altherat 👋 
Thanks for opening an issue!

I think this violates the pattern and goes against the core concepts.
There should only be a single way to update state in order for the library to be predictable.

I'm not sure I understand the issue you're having. A state doesn't have to be an empty class; you can use an enum for simple cases. Can you please provide a concrete example of the problems you're having? Thanks! 👍

**Comment by altherat** [comment]
I just meant that events are sometimes empty classes and it doesn't seem like the best design to me. It makes more sense to me to use methods which would avoid unnecessary event object creation and type checking. And it's a bit easier to call the events because IDEs will hint which methods are available.

Here's an example of an empty event:
https://github.com/felangel/bloc/blob/a4ecf0153359488553eea979173df22ac0f2446f/examples/flutter_todos/lib/blocs/todos/todos_event.dart#L10-L13

But it's understandable if this goes against core concepts. I just thought it was bit tedious and I thought I'd offer a suggestion.

**Comment by felangel** [comment]
@altherat I would look at the explicit event declaration as a positive. It forces you to define all the events that can trigger state changes in the bloc as well as all the states that the bloc can output. I would think of it as a finite state machine. The idea was to have a clear separation of how state changes are determined (mapEventToState) and how state changes are initiated (dispatch).

In addition, as a developer you are in full control of the events and states so it is up to you to define them however you see fit. There are extensions for IntelliJ and VSCode which generate the bloc files for you (bloc, events, states) so that you can have an organized project structure with minimal effort. 

At the end of the day the only rules are blocs are notified of events via dispatch and output immutable states in mapEventToState. Hope I was able to help and if you have additional feedback please don’t hesitate to share. Thanks 🙏
