### ISSUE TITLE
question: Is it not possible to listen to the events of a bloc?

### ISSUE THREAD

**Issue by realshovanshah** [felangel/bloc#2705]
**Description**
Similar to how we usually listen to another bloc's state in bloc-to-bloc communication, I wanted to listen to the events emitted by bloc but didn't find a way to do so myself. 

Is this not possible because listening to state should always be enough as every state is a result of an event?
Shouldn't there be a way to directly listen to a bloc's events from another bloc?

That's all. And hey Felix, sorry for marking this as a bug. I didn't see the 'question' label as an option. Was it removed?

Always appreciate your help to the community! Your fast response and the drive to help us has made this library really stand out.

**Comment by narcodico** [comment]
Hi @realshovanshah 👋 

It is not directly possible since the events controller is internal to the bloc. Also it's an antipattern to do such. 
The whole idea is to add events to the bloc that cares about those events. If you feel you need to add the same events to a different bloc then it might be that you need a single bloc instead of two.
Requirements like this are often the result of poor bloc architecture.

We also advice against tightly coupling your blocs so even thought listening to a bloc's state from another bloc is possible we surely don't encourage that.

Hope you find this helpful and we appreciate your positive feedback! 💙

**Comment by realshovanshah** [comment]
In large apps its pretty common to have a part of business logic dependent on data from another bloc. So bloc to bloc communication has been really helpful to us especially in reducing network calls.

I was just wondering that since listening to states of another bloc is a common use case, why isn't there a easy way to do the same with the stream of events. So basically this would go against the bloc paradigm, right?

**Comment by narcodico** [comment]
Bloc to bloc communication is indeed used but it doesn't mean that is the right way of architecting your features.
We're strongly recommending a bloc/cubit per feature and avoiding any inter-bloc dependencies as much as possible.


> bloc to bloc communication has been really helpful to us especially in reducing network calls.

I assume you're mostly referring here to streams of data. You can make use of `rxdart` operators(`shareValue` being one) to achieve caching thus allowing you to have multiple stream subscriptions in different features without hitting the server each time you set up a new one. But this is unrelated to bloc.

> So basically this would go against the bloc paradigm, right?

Very true.

**Comment by realshovanshah** [comment]
Okay I'll consider the things you have said and see how I can make this library even more effective in my projects.
I really appreciate your help and insights.
