### ISSUE TITLE
refactor: bloc snippet for v8.0.0

### ISSUE THREAD

**Issue by marcossevilla** [felangel/bloc#2731]
**Description**

I wanted to ask for opinions regarding how the bloc snippet on the VSCode/IntelliJ extensions should look, based on the new v8.0.0 changes ([here](https://github.com/felangel/bloc/issues/2526)'s the proposal if you haven't seen it).

1. Having a simple snippet with only one empty handler. 

This keeps the simplicity of the previous bloc snippet but can lead to misuse from other developers by having only one handler for all of their events. If they do that, probably they’ll notice is the same as using `mapEventToState` from previous versions, but I think newcomers can be misguided cause of this.

```dart
class SubjectBloc extends Bloc<SubjectEvent, SubjectState> {
      SubjectBloc() : super(SubjectInitial()) {
          on<SubjectEvent>((event, emit) {});
     }
}
```

2. Having a snippet with more code built-in, including basic events and states to set the correct use of the new syntax.

Some base events and states can be added to have a basic example with two handlers emitting different states just to clarify you shouldn’t have one emitter for many events, that would involve extra code that most probably will be deleted anyway, but renaming those classes can save time creating them.

```dart
class SubjectBloc extends Bloc<SubjectEvent, SubjectState> {
      SubjectBloc() : super(SubjectInitial()) {
          on<Event1>((event, emit) => emit(State1()));
          on<Event2>((event, emit) => emit(State2()));
     }
}
```

**Comment by elianmortega** [comment]
Hey @marcossevilla, I do prefer option #2 because just as you mentioned it represents better the idea that every single event should be registered with an `on` method. 

Also, I do think it's a more realistic snippet as usually with complex logic you will do:
```dart
class SubjectBloc extends Bloc<SubjectEvent, SubjectState> {
      SubjectBloc() : super(SubjectInitial()) {
          on<Event1>(_onEvent1);
          on<Event2>(_onEvent2);
     }
     
     Future<void> _onEvent1(Event1 event, Emitter<SubjectState> emit){}
     Future<void> _onEvent2(Event2 event, Emitter<SubjectState> emit){}
}
```

**Comment by prasant10050** [comment]
Is it a good practice to call member function from constructor?
Short answer:

Big No..! Please think twice before going with that approach. Actually, the problem arises when you go for inheritance.

Long answer:

Let’s take an example for discussing the problem we incur if we call the member method inside constructor.
```
public class A { 
 
    protected int a = 10; 
    public A() { 
        System.out.println("A::constructor"); 
        method(); 
    } 
 
    public void method() { 
        System.out.println("A::method(): a = " + a); 
    } 
} 
```

Extending class A in class B

```
public class B extends A { 
 
    protected int a = 20; 
 
    public B() { 
        super(); 
        System.out.println("B::constructor"); 
    } 
 
    @Override 
    public void method() { 
        System.out.println("B::method() a = " + a); 
    } 
} 
```

Test program
```
public class TestMain { 
 
    public static void main(String args[]) { 
        B b = new B(); 
        System.out.println("Object created...!"); 
        b.method(); 
    } 
} 
```

Expected output:
```
A::constructor 
B::method() a = 20 
B::constructor 
Object created...! 
B::method() a = 20 
```

Actual output:
```
A::constructor 
B::method() a = 0 
B::constructor 
Object created...! 
B::method() a = 20 
```

Here, you would’ve observed that the value of the member variable ‘a’ is printed as ‘0’ while the construction of object B.

Reason:When the object creation of B, the super class constructor A is called, on the execution run-time sees a overloaded method and tries to execute the same, but as the member variable in B class is yet to be initialized. (!!!! We are still in the way of constructing the B object, only after the successful execution of constructor, member variables are initialized.) Hence we get ‘0’ as the value of ‘a’ variable.

Hope that helps.

**Comment by felangel** [comment]
> Is it a good practice to call member function from constructor?
> Short answer:
> 
> Big No..! Please think twice before going with that approach. Actually, the problem arises when you go for inheritance.
> 
> Long answer:
> 
> Let’s take an example for discussing the problem we incur if we call the member method inside constructor.
> 
> ```
> public class A { 
>  
>     protected int a = 10; 
>     public A() { 
>         System.out.println("A::constructor"); 
>         method(); 
>     } 
>  
>     public void method() { 
>         System.out.println("A::method(): a = " + a); 
>     } 
> } 
> ```
> 
> Extending class A in class B
> 
> ```
> public class B extends A { 
>  
>     protected int a = 20; 
>  
>     public B() { 
>         super(); 
>         System.out.println("B::constructor"); 
>     } 
>  
>     @Override 
>     public void method() { 
>         System.out.println("B::method() a = " + a); 
>     } 
> } 
> ```
> 
> Test program
> 
> ```
> public class TestMain { 
>  
>     public static void main(String args[]) { 
>         B b = new B(); 
>         System.out.println("Object created...!"); 
>         b.method(); 
>     } 
> } 
> ```
> 
> Expected output:
> 
> ```
> A::constructor 
> B::method() a = 20 
> B::constructor 
> Object created...! 
> B::method() a = 20 
> ```
> 
> Actual output:
> 
> ```
> A::constructor 
> B::method() a = 0 
> B::constructor 
> Object created...! 
> B::method() a = 20 
> ```
> 
> Here, you would’ve observed that the value of the member variable ‘a’ is printed as ‘0’ while the construction of object B.
> 
> Reason:When the object creation of B, the super class constructor A is called, on the execution run-time sees a overloaded method and tries to execute the same, but as the member variable in B class is yet to be initialized. (!!!! We are still in the way of constructing the B object, only after the successful execution of constructor, member variables are initialized.) Hence we get ‘0’ as the value of ‘a’ variable.
> 
> Hope that helps.

@prasant10050 I don't think this is an appropriate place to have this discussion. If you are against the changes proposed, then you should leave the feedback on the proposal (#2526). This issue was posing a very specific question to gather feedback regarding what the snippet should look like in the vscode and intelliJ extensions not to discuss the new API.

In any case, `on<E>` is registering an event handler for when an event of type `E` is added to the respective bloc. If you don't want to register an event handler in the constructor body you don't have to but in most cases, you'd want a bloc to start reacting to incoming events as soon as the bloc is constructed (hence the registration in the constructor).

Furthermore, in the case of bloc, you generally shouldn't be using inheritance to compose blocs (especially not with registered event handlers in super-classes). Generally, a bloc should manage state for a given feature and if you have some shared code the recommended approach is to extract that shared functionality and inject it as a dependency into the bloc (think repositories). In addition, you should generally not maintain internal, mutable state as part of a bloc (all state should ideally be part of the bloc's state object). Hope that helps clarify your concerns and if you still feel strongly I'd ask you to move this discussion to the proposal since it is tangential to this issue, thanks 🙏

**Comment by felangel** [comment]
@marcossevilla @elianmortega I've thought about this some more and currently I feel it's safer for the snippet to use a single event handler rather than breaking things out into multiple event handlers because the single event handler guarantees that all events are processed the same way (based on the applied event transformer). If we default to multiple event handlers, then it might not be immediately obvious to developers that those individual event handlers will process events concurrently (specifically when the event handlers are asynchronous).

Also, it's easier to add a second event handler (if needed) rather than having to always delete and rename things so from the standpoint of keeping the snippet as simple as possible it would make sense to keep it as is:

```dart
import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';

part 'test_event.dart';
part 'test_state.dart';

class TestBloc extends Bloc<TestEvent, TestState> {
  TestBloc() : super(TestInitial()) {
    on<TestEvent>((event, emit) {
      // TODO: implement event handler
    });
  }
}
```

Let me know what you think and I'm happy to discuss more in depth but just wanted to jot my current thoughts down 😄

**Comment by marcossevilla** [comment]
@felangel I agree, I think keeping it simple it's okay since you can have one-liners as event handlers or even just one handler. Making multiple handlers would imply that you need to extract the handler's body to private methods and that's not going to be the best way to do it every time. I think it's a good way to show the equivalent to mapEventToState, but I'm a bit worried about developers leaving multiple event logic in just one handler, hope that's not a concurrent (pun intended) issue.

**Comment by felangel** [comment]
> @felangel I agree, I think keeping it simple it's okay since you can have one-liners as event handlers or even just one handler. Making multiple handlers would imply that you need to extract the handler's body to private methods and that's not going to be the best way to do it every time. I think it's a good way to show the equivalent to mapEventToState, but I'm a bit worried about developers leaving multiple event logic in just one handler, hope that's not a concurrent (pun intended) issue.

Awesome! Yeah we can keep on eye on it and adjust as needed. Closing for now 👍
