### ISSUE TITLE
feat: allow sending events to bloclistener

### ISSUE THREAD

**Issue by steeling** [felangel/bloc#2753]
This is likely going to get shot down, but here it goes.

The listener method should not accept a state. It should accept events. States are for building. Listener listens to events. Often times events are important not just to the business logic, but to the widgets themselves. A good example is a loading indicator. If i want to show a CircularProgressIndicator, while maintaining my state, i then have to wrap it in a new state, ie:

```
class LoadingState extends Equatable {
   state MyState;
  LoadingState(this.myState);
}
```

I can get around this with the whenBuild/whenListen methods, but really it's a hack to get around the concept that listeners don't really need state, they need events.

**Comment by felangel** [comment]
Hi @steeling 👋 
Thanks for opening an issue!

I disagree, events are used to notify the bloc and the UI reacts to states. It would be an anti-pattern imo to have the UI listen for events because the UI is responsible for dispatching events in the first place.

Regarding the loading indicator example, `loading` is a state. In your snippet, `myState` is some data/model it isn't the state in my opinion. You are in complete control over the state as a developer and can choose to model it however you'd like. I'd personally recommend having something like:

```dart
enum MyStatus { initial, loading, success, failure };

class MyState extends Equatable {
  const MyState({this.someModel, this.status = MyStatus.initial});
  final SomeModel? someModel;
  final MyStatus status;

  MyState copyWith({SomeModel? someModel, MyStatus? status}) {
    return MyState(
      someModel: someModel ?? this.someModel,
      status: status ?? this.status,
    );
  }
}
```

Then when the bloc receives a `ContentRequested` event it can emit a new loading state followed by a success/failure state like:

```dart
yield state.copyWith(status: MyStatus.loading);

try {
  final someModel = await _getSomeModel();
  yield state.copyWith(status: MyStatus.success, someModel: someModel);
} catch (_) {
  yield state.copyWith(status: MyStatus.failure);
}
```

Hope that helps 👍

**Comment by steeling** [comment]
Gotcha, that makes sense, i'll give this a shot. Thanks for the quick and detailed reply!
