### ISSUE TITLE
feat: allow setting state outside of mapEventToState

### ISSUE THREAD

**Issue by steeling** [felangel/bloc#2754]
Why restrict your users to this? Provide a happy path, sure, but don't put baricades up for power users.

**Comment by felangel** [comment]
Hi @steeling 👋 
Thanks for opening an issue!

This is because when using a `Bloc`, a state change should only happen in response to an incoming event. By allowing developers to set state outside of `mapEventToState` we violate this principle and it would no longer be possible to trace how a certain state became a certain value.

If you want to be able to trigger state changes from anywhere, then I highly recommend using `Cubit` instead -- you can `emit` a new state from anywhere. Hope that helps 👍

**Comment by steeling** [comment]
It just adds a lot more boilerplate. I would much prefer to have a single function for each event on my bloc, and call `myBloc.myEventCall(....)`, which would avoids large functions, and saves me from having to create a model for each event. At the end of the day I can work around it, but would be nice to have IMO

**Comment by felangel** [comment]
> It just adds a lot more boilerplate. I would much prefer to have a single function for each event on my bloc, and call `myBloc.myEventCall(....)`, which would avoids large functions, and saves me from having to create a model for each event. At the end of the day I can work around it, but would be nice to have IMO

What you're describing is `Cubit` 😄 .
If you don't need events you can just use `Cubit` and define functions:

```dart
class MyCubit extends Cubit<MyState> {
  MyCubit() : super(MyState(...));

  void doSomething() {
    // ...
    emit(MyState(...));
  }
}
```

**Comment by steeling** [comment]
thanks for pointing me in the right direction!
