### ISSUE TITLE
docs: Can't find an example of mocking a bloc to emit states in reponse to events

### ISSUE THREAD

**Issue by andrewdixon1000** [felangel/bloc#2757]
Hi,

I asked [this question](https://stackoverflow.com/questions/68809649/how-do-i-mock-a-bloc-in-flutter-with-states-being-emitted-in-response-to-events) on stackoverflow around a month ago but didn't get any response, so I want to try and get an answer here.

I want to test a widget that uses a bloc.  I want to be able to emit states from a mock of the bloc in response to events being raised by the widget under test.  I haven't been able to find any documentation covering what I'm trying to do. Included in the stackoverflow question is a [very simple project](https://github.com/andrewdixon1000/flutter_bloc_mocking_issue.git) demonstrating what I'm trying to achieve. Any help greatly appreciated.

Thanks

**Comment by scugn1zz0** [comment]
First of all your issue boils down to, is **widget testing with bloc**.
See [this](https://stackoverflow.com/questions/68809649/how-do-i-mock-a-bloc-in-flutter-with-states-being-emitted-in-response-to-events) resource, and [this](https://gist.github.com/reinaldomoreira/98e6d8ce1c296defe66fb064bbc2733b) resource.

Secondly. I wouldn’t merge widget + bloc test, unless you are doing integration testing, first you test the bloc, and you ensure that for every single event sent (among the possible ones) it emits the state that you expect.
Then, do your widget test iterating over all the possible states that your bloc can produce.

**Comment by andrewdixon1000** [comment]
Thanks for taking the time to post.

If I'm understanding you correctly what you suggest that I do is exactly what I'm trying to do.  I have a set of unit tests for my bloc and then I have a widget test for a widget that has the bloc as a dependency.  In that widget test I need to mock the bloc in such a way that it emits states in response to events and that's the part I'm struggling with.

I don't think that either of the resources you listed tells me how to do this (one of them is just a link to my question of stackoverflow).

Thanks

**Comment by felangel** [comment]
Hi @andrewdixon1000 👋 
Thanks for opening an issue!

I took a look and [opened a pull request](https://github.com/andrewdixon1000/flutter_bloc_mocking_issue/pull/1) with my suggestions. I highly recommend thinking of your tests in terms of notifications and reactions. In this case, I recommend having one test to verify that when the button is tapped, the correct event is added to the bloc (the bloc is notified). Then I recommend having a separate test to ensure that when the state changes from `FirstState` to `SecondState` that the correct page is rendered (the UI reacts to state changes appropriately). In the future, I highly recommend taking a look at the [example apps](https://github.com/felangel/bloc/tree/master/examples) since most of them are fully tested.

Hope that helps 👍

**Comment by andrewdixon1000** [comment]
Hi @felangel

Thanks a lot for your reply.  You PR has opened my eyes to how to approach these tests and I've successfully fixed the tests I was struggling with.
