### ISSUE TITLE
docs(flutter_firebase_login): documentation feedback

### ISSUE THREAD

**Issue by jeroen-meijer** [felangel/bloc#2758]
## Description

This issue is meant to log and keep track of feedback gathered from people who have used the Flutter Firebase Login example, including comments about the documentation, the example code itself and any other aspects related to the project.

### Feedback
- Links to firebase intructions dont point to the correct page
- Cache package points to a local path
- Alot of missing barrel files
- Avatar widget not mentioned
- Routes not mentioned

### Action Items
- ...

**Comment by jeroen-meijer** [comment]
Assigning @gvdvoort to provide feedback since he recently tried out this example.

**Comment by marcossevilla** [comment]
hi @CrossBread! 

>  In Java, you might infer the file name from the class name, but in Dart a little more hand-holding seems appropriate since authentication_repository.dart appears twice in the package, but only one contains code. The other contains a library and two export statements, but it isn't clear when the reader would want to structure their project the same way or not. What advantage does adding the library here add and how do you then reference it in other parts of the project?

Regarding this, we use barrel files to keep the code more organized, that way you can define your package exports and in case you have a whole folder that exports multiple files, you can create a `folder.dart` that exports them all. Similar to this:
```
// not recommended
import 'my_file.dart';
import 'my_other_file.dart';
import 'another_file.dart';

// recommended
import 'my_files.dart';
```

> Is it standard structure to have files with identical names in both /lib and /lib/src with the one in src importing the one in /lib? This is the case with authentication_repository.dart in the example.

You can also check [this link](https://dart.dev/guides/libraries/create-library-packages#organizing-a-library-package) to see the practices the Dart team recommends, as they suggest splitting implementation and export files, that's why you end up with 2 files for the authentication repository.

Thanks for all your feedback on the tutorial, we will update it as soon as we can with better documentation on the practices we just discussed and reach back to you! 👍

**Comment by CrossBread** [comment]
Awesome, thanks for sending along this information! I've developed software
for a long time, but mostly in a Java environment. I'm pretty new to Dart
and still getting a handle on what are the recommended best practices for
Dart and Flutter versus just a convention that a group of devs has adopted.

**Comment by felangel** [comment]
We've already done a pass at updating examples and docs so closing this for now. Feel free to open new issues with specific areas of improvement 👍
