### ISSUE TITLE
No MediaQuery widget ancestor found

### ISSUE THREAD

**Issue by mado-bohsali** [felangel/bloc#2777]
Dear team,

Today I have tried to install the hydrated_bloc package. Throughout my coding I received this error

![Simulator Screen Shot - iPod touch (7th generation) - 2021-09-22 at 11 04 32](https://user-images.githubusercontent.com/18421260/134306083-03a5f64a-3583-4b68-805f-812313d72224.png)
:
<img width="619" alt="Screen Shot 2021-09-22 at 11 06 19 AM" src="https://user-images.githubusercontent.com/18421260/134306203-7556af81-e97c-4bd8-9ef5-9a87442c068e.png">

I appreciate your input!

**Comment by felangel** [comment]
Hi @mado-bohsali 👋 
Thanks for opening an issue!

The problem is you don't have a `MaterialApp` at the top of your widget tree. To resolve it you just need to wrap `MyHomePage` in a `MaterialApp`:

```dart
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => CounterCubit(),
      child: MaterialApp(home: const MyHomePage(title: 'App'))
    );
  }
}
```

This issue is not related to the bloc library so in the future please try to avoid opening issues here that aren't directly related to the library, thanks 🙏
