### ISSUE TITLE
[Discussion] What was the rationale to change the default behavior from sequential / expandAsync to concurrent / flatMap in 7.2.0?

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#2778]
Not a bug; rather a question of a long-time user. As in the title, the default behavior changed considerably in the latest version, and I would be interested why. (I'm not implying it is good or bad or anything, just plain curious.)
In my previous enterprise project with Flutter, the default of being sequential was very welcome as we could foresee how the bloc would behave and life was simple. We did need to change it to parallel once (so we overrode `transformEvents`). So, in my experience the previous default was much more common, but maybe I and my project are an anomaly.

**Comment by felangel** [comment]
Hi @wujek-srujek 👋 
Thanks for opening an issue!

We went back and forth on this and there are several reasons for the change:

1. Many developers we spoke with actually expected/thought the events would be processed concurrently and were surprised to hear that in the previous implementation the default was sequential.
2. It's pretty common to have events that are triggered by user input (button taps for example) which execute some asynchronous operation (like a login button triggering a login request to some backend). With the default behavior it is very easy to build up a queue of events and "clog" the bloc because the user spammed the button.
3. It's a more performant default that aligns more closely with how Cubit works.

With all that being said, I totally acknowledge that some teams might prefer `sequential` as the default which is why we tried to make it relatively easy to customize this:

```dart
import 'package:bloc/bloc.dart';
import 'package:bloc_concurrency/bloc_concurrency.dart';

void main() {
  Bloc.transformer = sequential();
  ...
}
```

Let me know if that helps and great question!

**Comment by wujek-srujek** [comment]
1. I actually expected the same when I first stared working with Dart, Flutter and Bloc, and so did pretty much everybody in my team. But I did feel the default of being sequential was a nice gift.
2. Yes, but as I said, in our case (a huge mobile application that you know very well...) the great majority of cases wanted the sequential behavior, `switchMap` being the second most common, and I haven't seen a single `flatMap`, which is now the default. With `flatMap`, there is no guarantee whatsoever about the current state and in my experience the code must be full of checks for it, something that isn't the case in `expandAsync`. Granted, my code may have been bad and others may be more successful. As I'm redacting this comment, I actually came to think that `switchMap` might be a much better default?
3. I don't understand the Cubit part, I think it is the other way round - when I have code:
```dart
cubit.methodA();
cubit.methodB();
```
I have always believed that in no way can any state emitted in `methodB` somehow be observed earlier than any state emitted in `methodA` - processing the methods was sequential. Default Bloc behavior was the same, sequential, and now it is concurrent, so if anything, the behavior was consistent before and now it isn't. Or have I been wrong all along?

As for overriding this behavior, I know it is possible and easy, I have no issues with the new default, just curious.

My only concern is that the new behavior has been introduced in a minor version, and while it doesn't break existing code, it does hugely change runtime behavior, right? It remains to be seen how many tests and how many apps suddenly break (but I hope to be mistaken).

**Comment by wujek-srujek** [comment]
I love the new `on<Event>` API, BTW.

**Comment by felangel** [comment]
> 2. Yes, but as I said, in our case (a huge mobile application that you know very well...) the great majority of cases wanted the sequential behavior, `switchMap` being the second most common, and I haven't seen a single `flatMap`, which is now the default. With `flatMap`, there is no guarantee whatsoever about the current state and in my experience the code must be full of checks for it, something that isn't the case in `expandAsync`. Granted, my code may have been bad and others may be more successful. As I'm redacting this comment, I actually came to think that `switchMap` might be a much better default?

It all depends on the use-case. The concurrency/event transformers were inspired by [ember concurrency](http://ember-concurrency.com/docs/task-concurrency/) which defaults to `concurrent` as well.

> 3. I don't understand the Cubit part, I think it is the other way round - when I have code:
> 
> ```dart
> cubit.methodA();
> cubit.methodB();
> ```
> 
> I have always believed that in no way can any state emitted in `methodB` somehow be observed earlier than any state emitted in `methodA` - processing the methods was sequential. Default Bloc behavior was the same, sequential, and now it is concurrent, so if anything, the behavior was consistent before and now it isn't. Or have I been wrong all along?

If the methods are asynchronous, then the order of state changes is determined by when `emit` is called so just because `methodA` was called before `methodB` doesn't mean `methodA` will complete before `methodB`.

> As for overriding this behavior, I know it is possible and easy, I have no issues with the new default, just curious.
> 
> My only concern is that the new behavior has been introduced in a minor version, and while it doesn't break existing code, it does hugely change runtime behavior, right? It remains to be seen how many tests and how many apps suddenly break (but I hope to be mistaken).

The change is not breaking because `mapEventToState` remains the same (it still processes events sequentially). The change only applies to the new `on<Event>` API so existing apps should be able to use v7.2.0 without any changes.

**Comment by felangel** [comment]
> I love the new `on<Event>` API, BTW.

Thanks for the support! That's great to hear 😄 💙

**Comment by wujek-srujek** [comment]
> If the methods are asynchronous,

Yes, if they are `async` everything changes, but in this case the developer knows that there is no way to foresee much. I was focusing on the sync case.

> The change is not breaking because mapEventToState remains the same (it still processes events sequentially).

Great to hear, I understood the release notes differently, sorry for this.

**Comment by felangel** [comment]
> > If the methods are asynchronous,
> 
> Yes, if they are `async` everything changes, but in this case the developer knows that there is no way to foresee much. I was focusing on the sync case.
> 
> > The change is not breaking because mapEventToState remains the same (it still processes events sequentially).
> 
> Great to hear, I understood the release notes differently, sorry for this.

No problem at all! Let me know if you have any other questions/concerns -- I'm always happy to discuss 😄
