### ISSUE TITLE
Change the parameters of mapEventToState

### ISSUE THREAD

**Issue by JohannesKlauss** [felangel/bloc#28]
**Is your feature request related to a problem? Please describe.**
The `Bloc` class type signature as well as the `onTransition` method is `<E, S>`. But the `mapEventToState` parameters are `(S, E)`.

**Describe the solution you'd like**
It would be more consistent if the `mapEventToState` method would follow the signature of the rest of the package and also have `(E event, S state)` instead of `(S state, E event)`.

**Comment by felangel** [comment]
Hi @JohannesKlauss, thanks for the feedback.

The reason the `mapEventToState` signature is `(S state, E event)` is because the state parameter is referring to the currentState.

In `onTransition` as well as the `Bloc` class type signature the state is referring to the next state (the output of the `Bloc`).

Also, `mapEventToState` is inspired by Redux Reducers whose function signature is `(S previousState, A action)`.

Thoughts? Does that help clarify why it's written the way it is?

**Comment by felangel** [comment]
@JohannesKlauss  closing this for now.
Feel free to respond with any comments or concerns and I'll gladly reopen the issue.

**Comment by ThinkDigitalRepair** [comment]
OK, came to report this as well. It was confusing. Can you add in the docs what the generic types are for? I figured them out, but not after digging.
Like It's not clear what E is, and what S is until later down the code

**Comment by ThinkDigitalRepair** [comment]
Well making sense is relative to the one understanding. The way I view it,
the event should be on the left, cause input is generally considered to be
coming from the left side, and whatever is going out to the stream should
go out to the right. Cause we're not actually mapping anything to (AKA
changing) the state, we're creating a new state object and sending it out,
correct?

**Comment by felangel** [comment]
Yes I agree that generally input is coming from the left side but the way I view it is in the case we have two inputs and we're creating a new state object. The two inputs are S currentState and E event. I personally thought it made sense in that order because the currentState precedes the event. Thoughts?

**Comment by ThinkDigitalRepair** [comment]
Wait. If state is the current state, then it makes sense because it exists before the event does. I really need to study this function

**Comment by ThinkDigitalRepair** [comment]
It would be very clear if the variable was named currentState or oldState, etc

**Comment by felangel** [comment]
haha yeah I will rename it and add the documentation for the generic types

**Comment by felangel** [comment]
changes included in bloc v0.7.4
