### ISSUE TITLE
`PostFetched` event triggered twice in the flutter_infinite_list example

### ISSUE THREAD

**Issue by karanokk** [felangel/bloc#2800]
When using a faster speed to ~~slide~~ drag the list, `PostFetched` event will trigger twice.
697ms interval between two requests.

I hope that the `PostFetched` event will not be triggered again when the `PostFetched` event is triggered until the list(UI) is updated.

`bloc`: 7.2.0

<img width="949" alt="2021-09-27 下午12 27 51" src="https://user-images.githubusercontent.com/62784811/134846077-71659fd2-2b02-417d-b587-9105f9839c21.png">

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 What do you mean 'using a faster speed to slide the list?'

**Comment by karanokk** [comment]
> Hi there 👋🏼 What do you mean 'using a faster speed to slide the list?'

Drag the list quickly

**Comment by felangel** [comment]
Hi @karanokk 👋 
Thanks for opening an issue!

In this case, `droppable` is working as expected because when you scroll quickly, the UI adds a `PostFetched`, the bloc fetches the next set of posts and the ListView is still moving (due to the scroll momentum) which triggers another `PostFetched` event to the bloc (but since the previous one finished it is processed). To account for the momentum scrolling we can create a custom `throttleDroppable` transformer. I'll push that change shortly, hope that helps and thanks for bringing this up!
