### ISSUE TITLE
question: How do I use generic with the new on<Event>?

### ISSUE THREAD

**Issue by nghialm269** [felangel/bloc#2823]
**Description**
In my app, there are many screens that need to do pagination, so I'm trying to create a generic bloc to help reduce duplicate.

Here is what I'm trying to do:
```dart

abstract class PaginatedEvent<T> extends Equatable {
  @override
  List<Object?> get props => const [];
}

class PaginatedEventLoadFirstPage<T> extends PaginatedEvent<T> {
  final T opts;

  PaginatedEventLoadFirstPage(this.opts);

  @override
  List<Object?> get props => [opts];
}

class PaginatedEventLoadNextPage<T> extends PaginatedEvent<T> {}

@freezed
class PaginatedState<T> with _$PaginatedState<T> {
  const PaginatedState._();
  const factory PaginatedState.initial(
    List<T> data,
  ) = _PaginatedStateInitial;
  const factory PaginatedState.loadInProgress(
    List<T> data,
  ) = _PaginatedStateLoadInProgress;
  const factory PaginatedState.loadSuccess(
    List<T> data, {
    required bool isNextPageAvailable,
  }) = _PaginatedStateLoadSuccess;
  const factory PaginatedState.loadFailure(
    List<T> data, {
    String? message,
  }) = _PaginatedStateLoadFailure;
}

abstract class PaginatedBloc<
    OptionsType,
    ListType,
    Event extends PaginatedEvent<OptionsType>,
    State extends PaginatedState<ListType>> extends Bloc<Event, State> {
  PaginatedBloc(State initialState) : super(initialState) {
    on<PaginatedEventLoadFirstPage<OptionsType>>(
      _onLoadFirstPage,
      transformer: restartable(),
    );

    on<PaginatedEventLoadNextPage<OptionsType>>(
      _onLoadNextPage,
      transformer: droppable(),
    );
  }
  late OptionsType opts;

  Future<void> _onLoadFirstPage(
    PaginatedEventLoadFirstPage<OptionsType> event,
    Emitter<State> emit,
  ) async {
    opts = event.opts;
    await loadFirstPage(emit);
  }

  Future<void> _onLoadNextPage(
    PaginatedEventLoadNextPage<OptionsType> event,
    Emitter<State> emit,
  ) async {
    await loadNextPage(emit);
  }

  Future<void> loadFirstPage(Emitter<State> emit);
  Future<void> loadNextPage(Emitter<State> emit);
}
```

But I got this errors:
```
'PaginatedEventLoadFirstPage<OptionsType>' doesn't conform to the bound 'Event' of the type parameter 'E'.
Try using a type that is or is a subclass of 'Event'.

'PaginatedEventLoadNextPage<OptionsType>' doesn't conform to the bound 'Event' of the type parameter 'E'.
Try using a type that is or is a subclass of 'Event'.
```

How do I create a generic bloc like this?

**Comment by brianrobles204** [comment]
I think it's failing because Dart cannot guarantee that `PaginatedEventLoadFirstPage<OptionsType>` etc. will extend `Event` specifically. For example, you could conceivably do something like this:

```dart
class UnrelatedEvent extends PaginatedEvent<String> {}

class RealBloc extends PaginatedBloc<String, String, UnrelatedEvent, UnrelatedState> {
   // ...
}
```

In which case `PaginatedEventLoadFirstPage<String>` will not extend `UnrelatedEvent`. They have a common supertype (`PaginatedEvent<String>`) but one is not a subtype of the other.

Could something like this work instead?

```dart
abstract class PaginatedBloc<OptionsType, ListType> 
    extends Bloc<PaginatedEvent<OptionsType>, PaginatedState<ListType>> {
   // ...
}
```

**Comment by nghialm269** [comment]
> I think it's failing because Dart cannot guarantee that `PaginatedEventLoadFirstPage<OptionsType>` etc. will extend `Event` specifically. For example, you could conceivably do something like this:
> 
> ```dart
> class UnrelatedEvent extends PaginatedEvent<String> {}
> 
> class RealBloc extends PaginatedBloc<String, String, UnrelatedEvent, UnrelatedState> {
>    // ...
> }
> ```
> 
> In which case `PaginatedEventLoadFirstPage<String>` will not extend `UnrelatedEvent`. They have a common supertype (`PaginatedEvent<String>`) but one is not a subtype of the other.
> 
> Could something like this work instead?
> 
> ```dart
> abstract class PaginatedBloc<OptionsType, ListType> 
>     extends Bloc<PaginatedEvent<OptionsType>, PaginatedState<ListType>> {
>    // ...
> }
> ```

Thank you, your solution works for me!

I have some more questions:

* Is there anyway I could alias `PaginatedEvent<OptionsType>` and `PaginatedState<ListType>` to `E` and `S` respectively? since writing them repeatedly is too lengthy. (that's why I was doing something like `Event extends PaginatedEvent<OptionsType>` in the first place, but I just created problems for myself in the end).

* Is there anyway to consume the generic bloc without passing the real bloc's type to the type parameter?

Currently I have something like this (which works):
```dart
typedef Widget ItemBuilder<T>(BuildContext context, T item);
typedef Widget SeparatorBuilder(BuildContext context, int index);

class PaginatedListView<Options, Type,
    Bloc extends PaginatedBloc<Options, Type>> extends StatelessWidget {
  PaginatedListView({
    Key? key,
    required this.itemBuilder,
    this.separatorBuilder,
  }) : super(key: key);

  final ItemBuilder<Type> itemBuilder;
  final SeparatorBuilder? separatorBuilder;

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<Bloc, PaginatedState<Type>>(
        // ...
    );
  }
}

typedef UserListState = PaginatedState<User>;
class UserListBloc extends PaginatedBloc<UserListOptions, User> {
  // ...
}

class UserListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider<UserListBloc, UserListState>(
        // ...
       child: UserListForm(),
    );
  }
}

class UserListForm extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PaginatedListView<UserListOptions, User, UserBloc>(/* ... */);
  }
}
```

But since the generic list view **only** needs to know about the type of the list, I want something like this (which does not work):
```dart
class PaginatedListView<Type> extends StatelessWidget {
  // ...

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<PaginatedBloc, PaginatedState<Type>>(
        // ...
    );
  }
}
```

**Comment by brianrobles204** [comment]
Hi, sorry for the late reply! To address your questions,

> Is there anyway I could alias PaginatedEvent<OptionsType> and PaginatedState<ListType> to E and S respectively? since writing them repeatedly is too lengthy.

If you're on the newer versions of Flutter / Dart, you might want to consider using non-functional type aliases, like so

```dart
typedef UserState = PaginatedState<UserListType>;
```

Etc. You may need to adjust your pubspec.yaml so the minimum SDK version is at least 2.14.0 and run `pub get`

> Is there anyway to consume the generic bloc without passing the real bloc's type to the type parameter?

This is a bit trickier. You should know that `BlocProvider` (which uses Provider under the hood) uses the type of the bloc as a key which can later be accessed by a `BlocConsumer`. You can't just use `BlocConsumer<PaginatedBloc<UserOptions,UserType>>` and get a provided `UserBloc` for example. From my understanding, only `BlocConsumer<UserBloc>` will work.

One workaround is to provide the generic type itself, directly. For example, you could do

```dart

class PaginatedBlocProvider<OptionsType, ListType,
    T extends PaginatedBloc<OptionsType, ListType>> extends StatelessWidget {
  const PaginatedBlocProvider({
    Key? key,
    required this.child,
    required this.create,
  }) : super(key: key);

  final Widget child;
  final Create<T> create;

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        BlocProvider<T>(create: create),
        ProxyProvider<PaginatedBloc<OptionsType, ListType>>(
          update: (context) => Provider.of<T>(context),
        ),
        // Optional if you just want to use BlocProvider.of<PaginatedBloc> or 
        // BlocConsumer<PaginatedBloc,PaginatedState>, meaning you want to add events 
        // or access state without needing the generic parts of the event / state
        ProxyProvider<PaginatedBloc>(
          update: (context) => Provider.of<T>(context),
        ),
      ],
      child: child,
    );
  }
}
```

And use this PaginatedBlocProvider instead of a vanilla BlocProvider. This *should* let you do `BlocConsumer<PaginatedBloc<O,L>>` (though admittedly I haven't tested it). Note that with each looser type you register you also work with a bit less type safety when you try to use it downstream.

**Comment by brianrobles204** [comment]
Also you should consider *why* you're using generics. It might also be possible to just extend PaginatedEvent and PaginatedState, instead of using the typedef thing I mentioned. If for example, your `PaginatedBloc` code makes no use of the generic parts of the event or state, that may be a sign that you can simply use inheritance instead of generics, which could make the code easier to read.

Tho either way, you might still need to do the second Provider thing I mentioned if you want your downstream widgets to work with any PaginatedBloc instead of a specific Bloc type.

**Comment by nghialm269** [comment]
@brianrobles204: Sorry for the late rely, I decided to provide the generic type directly since I think using a separate `PaginatedBlocProvider` makes the code harder to understand.

Thank you very much for helping me!
