### ISSUE TITLE
flutter_bloc

### ISSUE THREAD

**Issue by gooadd06** [felangel/bloc#2877]
I read documentation but I didn't manage to get an answer .
If I'm making movie app , and I have many actions in it .
(get popular movies , get trending movies , get top rated movies ... etc )
all of these actions return the same model but with different data . 
how do I manage my bloc  ? .
should I make 1 bloc for all actions and if I do , how to return different data but with same model in  a way that each screen hold its data that is different without conflict .
or I should make bloc per actions so that bloc state have different data ?

**Comment by marcossevilla** [comment]
hey @gooadd06! I suggest you analyze how you want to structure your app, I suggest you structure it as features, so you can have a movies feature and then subfeatures for each action/endpoint from your API. Would look like this:
```
├── lib
│   ├── movies
│   │   ├── popular
│   │   └── trending
│   │   └── top_rated
```
Then, you can provide your blocs with a MoviesRepository that will contain each call to the API, so that way each subfeature has a bloc that calls the correspondent method to get the exact data you need.

Another way can be to have a MoviesBloc and filter its data if you can to PopularMoviesBloc, TopRatedMoviesBloc... but that can be in case you have only one list that can be filtered. I guess the first approach is the better but let me know if that helps. 👍

**Comment by gooadd06** [comment]
thanks for your response , It helped a lot
