### ISSUE TITLE
How to inject the same Bloc into BlocProviderTree?

### ISSUE THREAD

**Issue by anticafe** [felangel/bloc#297]
**Is your feature request related to a problem? Please describe.**
In my application, there is 2 tabs: `Page1` and `Page2`, which shares the same logic (is handled by `BlocCalculator`. However each time update `Page1` in result of Bloc, I don't want `Page2` receive that update. Thus, I would like to inject 2 instances of `BlocCalculator` into `BlocProviderTree`, one for `Page1` and one for `Page2`. However it seems in `BlocProviderTree` we're allowed to inject only 1 instance of the same Bloc.

**Describe the solution you'd like**
I would like to inject multiple instances of Bloc into `BlocProviderTree`.

**Describe alternatives you've considered**
Could each instance of Bloc come with a unique key, so that we can retrieve it via (context + key) later?

**Comment by felangel** [comment]
Hi @anticafe 👋 
Thanks for opening an issue!

Regarding your question, I would recommend provided the two instances in the parts of the subtree that require them instead of at the root.

In this case, even if it were possible, you wouldn't get the result you want because when you do the lookup using `BlocProvider.of<BlocCalculator>(context)` you would always get the closest ancestor (whichever one is lower in the widget tree).

Hope that helps and great question 👍
