### ISSUE TITLE
[Question] About bloc state management 

### ISSUE THREAD

**Issue by marcqtan** [felangel/bloc#3007]
Hello @felangel, I am using bloc to create a Login Page and Home Page. I want to access and show the email of the user after logging in, in a different page (e.g Home Page or any other page). 

If i want to access the email variable in other Pages is it correct to put it under State Class? Is my structure below correct? :

 Here's the LoginState:

```
part of 'login_cubit.dart';

abstract class LoginState extends Equatable {
  final String? firstName;
  final String? lastName;
  final String? email;

  const LoginState({this.firstName, this.lastName, this.email});

  @override
  List<Object> get props => [];
}

class LoginInitial extends LoginState {}

class LoginLoading extends LoginState {}

class LoginError extends LoginState {
  final String errorMsg;
  const LoginError(this.errorMsg);

  @override
  List<Object> get props => [errorMsg];
}

class LoginAuthenticated extends LoginState {
  const LoginAuthenticated({firstName, lastName, email})
      : super(
          firstName: firstName,
          lastName: lastName,
          email: email,
        );
}

class LoginUnAuthenticate extends LoginState {}
```

Here's my cubit, I am emitting the state in login() method:

```
class LoginCubit extends Cubit<LoginState> {
  final AuthRepository repository;
  final RegisterCubit registerCubit;
  late final StreamSubscription blocSubscription;

  LoginCubit({required this.registerCubit, required this.repository})
      : super(LoginInitial()) {
    blocSubscription = registerCubit.stream.listen((state) {
      if (state is RegisterSuccess) {
        emit(LoginAuthenticated(
            firstName: state.firstName,
            lastName: state.lastName,
            email: state.email));
      }
    });
  }


  void login(String email, String password) async {
    emit(LoginLoading());
    AuthData data = await repository.login(email, password);
    if (!data.hasError) {
      UserProfile? user = await repository.currentUser();
      emit(
        LoginAuthenticated(
          firstName: user?.firstName,
          lastName: user?.lastName,
          email: user?.email,
        ),
      );
    } else {
      emit(LoginError(data.error));
    }
  }
```

and I'm accessing the state variable using the code below: 
HomePage.dart:
```
   child: Builder(builder: (context) {
                  final firstname = context.select((LoginCubit cubit) => cubit.state.firstName);
                  return Text(
                    'Welcome $firstname!',
                    style: const TextStyle(
                      fontSize: 25,
                      color: Colors.white,
                    ),
                  );
                }),
```

Thanks in advance!!

**Comment by marcqtan** [comment]
any updates on this? thanks!

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 It seems like you drew a lot of inspiration from the Firebase Login example. 

One thing to keep in mind here is that the `Login` feature is separate from the `App` state. Why is that? That's because the `Login` feature only holds state that is necessary for the act of logging in, whereas the `App` state holds all of the state that is necessary for the function of the app.

Take a look at the [App State](https://github.com/felangel/bloc/blob/3d87582a766ccc85d5382e93cb95600f2c338a6e/examples/flutter_firebase_login/lib/app/bloc/app_state.dart#L20) and you will find that that the User state data actually resides there ! 

This means that you can access the data that you'd like from the App Bloc state, just like how the home view accesses the avatar  here
```

  @override
  Widget build(BuildContext context) {
    final textTheme = Theme.of(context).textTheme;
// This is a pointer to the user model in the App Bloc State
    final user = context.select((AppBloc bloc) => bloc.state.user);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
        actions: <Widget>[
          IconButton(
            key: const Key('homePage_logout_iconButton'),
            icon: const Icon(Icons.exit_to_app),
            onPressed: () => context.read<AppBloc>().add(AppLogoutRequested()),
          )
        ],
      ),
      body: Align(
        alignment: const Alignment(0, -1 / 3),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
// and here we are accessing the user photo
            Avatar(photo: user.photo),
            const SizedBox(height: 4),
            Text(user.email ?? '', style: textTheme.headline6),
            const SizedBox(height: 4),
            Text(user.name ?? '', style: textTheme.headline5),
          ],
        ),
      ),
    );
  }
```

If you take a look at the[ user model](https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/packages/authentication_repository/lib/src/models/user.dart) (defined in the authentication repository) you will see that this model has 4 different properties you can access.

```
  const User({
    required this.id,
    this.email,
    this.name,
    this.photo,
  });
```

So, to round it all out, if you would like to access the email from the authenticated user, all you'd need to do is access the state of the app bloc below where it is provided, like this:

```dart
final user = context.select((AppBloc bloc) => bloc.state.user.email);
```

Note: You can also use `Context.read` or `Context.watch` depending on your use case

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍
