### ISSUE TITLE
style: remove the `part` directive

### ISSUE THREAD

**Issue by purplenoodlesoop** [felangel/bloc#3015]
Hello!

Currently, the official documentation on Creating Packages suggests not using the `part` directive when creating packages. It states: 
> [You may have heard of the part directive, which allows you to split a library into multiple Dart files. We recommend that you avoid using part and create mini libraries instead.](https://dart.dev/guides/libraries/create-library-packages#organizing-a-library-package). 

But the package `bloc` builds its exposing system only on the `part` directive. I will be more than happy to submit a PR that changes it to the `export` :)

**Comment by felangel** [comment]
Hi @purplenoodlesoop 👋 
Thanks for opening an issue

This was done intentionally in order to facilitate the separation of implementations while still maintaining private members and methods. If we revert to exports we’ll either have to make things public so they can be accessed across multiple files or have single files that contain lots of code.

The structure of the package is fairly similar to [dart:async](https://github.com/dart-lang/sdk/blob/4ac35a7ec8c598ba1fdd8a1835a7fd84c61d9221/sdk/lib/async/async.dart#L103 ) which uses parts to organize the various parts of the library.

**Comment by purplenoodlesoop** [comment]
Thanks for the response @felangel!

> If we revert to exports we’ll either have to make things public so they can be accessed across multiple files or have single files that contain lots of code.

There are also two other options:
1) Shared, but internal members of the package will be extracted to separate files that are not exported in the `lib/bloc.dart`.
2) The `lib/bloc.dart` will use the `show` directive to export only the needed members.

I am more inclined towards the first option.

**Comment by felangel** [comment]
> Thanks for the response @felangel!
> 
> > If we revert to exports we’ll either have to make things public so they can be accessed across multiple files or have single files that contain lots of code.
> 
> There are also two other options:
> 
> 1. Shared, but internal members of the package will be extracted to separate files that are not exported in the `lib/bloc.dart`.
> 2. The `lib/bloc.dart` will use the `show` directive to export only the needed members.
> 
> I am more inclined towards the first option.

The reason I'm not a fan of the first approach is because you tend to end up with files like `internal.dart` or `_bloc.dart` which introduces new problems:

1. Implementation details are scattered across multiple files
2. File naming conventions like `internal.dart` become a catch-all or naming conventions like `_bloc.dart` start to imply the file is private even though all files in the `src` directory are private unless exported by the library.

**Comment by purplenoodlesoop** [comment]
> File naming conventions like internal.dart become a catch-all or naming conventions like _bloc.dart start to imply the file is private even though all files in the src directory are private unless exported by the library.

I fully agree that such namings are not very meaningful and confusing! I propose either to separate the `src` folder into two – `internal` and `public`, or just add the `internal` folder to the `src`, while leaving all files that are meant to be exported in the root of the `src`, and there, files could be named with their own, meaningful names.

> Implementation details are scattered across multiple files

That could be a problem, so the second option could be used with the `show` directive if things scatter too much. 

> In addition, this does not account for private member variables. For example, BlocBase contains a private _blocObserver member which can be used in both Cubit and Bloc implementations. If we refactor to use exports, we'll have to either make _blocObserver public and protected or internal (which isn't ideal because it's still visible) or we'll need to combine BlocBase, Cubit, and Bloc class definitions into a single file.

That is also a very valid problem. Here, I think advice from the same *Creating packages* guide could be used: *In most cases, each class should be in its own mini library, unless you have a situation where two classes are tightly coupled.*. Those classes are highly coupled indeed, and we could use the `part` directive on them, but still use the `export` in the `lib/bloc.dart`. Similar to the `replay_bloc` packages, but on a higher scale.

**Comment by felangel** [comment]
@purplenoodlesoop I agree and opened #3017 use parts only for the tightly coupled aspects and maintain top level exports for the library. Let me know what you think, thanks!
