### ISSUE TITLE
feat: Automatic naming of folder

### ISSUE THREAD

**Issue by khalilkm01** [felangel/bloc#3046]
Usually, when creating a new bloc/cubit using the VSCode extension it just names the folder to bloc/cubit which is not really an issue but a small minor update can improve on that significantly.

A minor update could create the folder with the specific file name already as typed before with a config file to decide whether it follows the camel or pascal case for naming conventions.

**Comment by marcossevilla** [comment]
hi @khalilkm01, thanks for the suggestion! the extension formats your file's name as `snake_case` because that's the style guideline established on [Effective Dart](https://dart.dev/guides/language/effective-dart/style#do-name-libraries-and-source-files-using-lowercase_with_underscores).

I'm closing this issue for now but feel free to comment if you have any other doubt. 👍

**Comment by khalilkm01** [comment]
I was talking about folder name sorry
