### ISSUE TITLE
Dependency injection in repositories

### ISSUE THREAD

**Issue by stefangaller** [felangel/bloc#3109]
For me, it is unclear in the documentation how I'm supposed to inject data sources to a repository.

When looking at the following code, I think this cannot work, since there is no constructor setting the DataProviders:
```
class Repository {
    final DataProviderA dataProviderA;
    final DataProviderB dataProviderB;

    Future<Data> getAllDataThatMeetsRequirements() async {
        final RawDataA dataSetA = await dataProviderA.readData();
        final RawDataB dataSetB = await dataProviderB.readData();

        final Data filteredData = _filterData(dataSetA, dataSetB);
        return filteredData;
    }
}
```

Now, I probably have a `RepositoryProvider` that adds the DataProviders via the constructor – how should I handle shared dependencies in the DataProviders? (Such as `dio` when using the `retrofit` package – which then might have a dependency on `baseUrl`). There are often more layers of injection than provided via the BLoC package.

```
final baseUrl = 'https://myapi.com/';
final Dio dio = Dio(DefaultConfig(baseUrl: baseUrl));
final dataSource1 = DataSource1(dio);
final dataSource2 = DataSource2(dio);
...

MultiRepositoryProvider(
  providers: [
    RepositoryProvider(create: (context) => RepositoryA(dataSource1),
    RepositoryProvider(create: (context) => RepositoryB(dataSource1, dataSource2),
    RepositoryProvider(create: (context) => RepositoryC(dataSource2),
  ]
)

```

I could use `get_it` for handling these kinds of injection, but then I'm mixing concepts, which looks error-prone to me: Some components are provided using `InheritedWidgets` others via a service locator.

What is the recommended approach here? 

PS: Thank you for the great package :)

**Comment by chonghorizons** [comment]
In the discord, I've heard it recommended to not mix `get_it` with bloc, because it can make testing hard.

The v8 tutorial for `flutter_todos` is currently in pull request. (https://github.com/felangel/bloc/pull/2859#issuecomment-987233491). `git checkout` that branch and look at the structure they have there.

That example uses a few extra layers of abstraction as packages to deal with the actual cloud/datasource API calls implemented as 3 external packages. Within the app, it's just defining an interface (https://github.com/chonghorizons/bloc/blob/chong-preferred/docs/fluttertodostutorial.md#todos-repository). And the 3 external packages are the only ones that care about how the repository is implemented. (This section of my docs writeup might help: https://github.com/chonghorizons/bloc/blob/chong-preferred/docs/fluttertodostutorial.md#packages-1 or https://github.com/chonghorizons/bloc/blob/chong-preferred/docs/fluttertodostutorial.md#packages)

Putting dio in an external package would be analogous to how you are using dio, if I am understanding correctly.

**Comment by chonghorizons** [comment]
> When looking at the following code, I think this cannot work, since there is no constructor setting the DataProviders:

Yeah, you are right that the data connection has to happen before the repository injection. In the tutorial, they handle this with a `bootstrap` which acts like an initialization runner. See https://github.com/chonghorizons/bloc/blob/chong-preferred/docs/fluttertodostutorial.md#startup-bootstrapping. The `bootstrap` is what links things together when `main()` is called.

Let me know if this makes sense. 

And `git clone`ing and CTRL-clicking in your IDE will make a lot more sense than reading the code. Essentially, a lot of things are spread out into different files. This makes it harder to read the code altogether, but it makes it easier to test the code separately.

**Comment by stefangaller** [comment]
Thank you for your detailed answer. I will check out the new example.

For the bootstrapping approach, I still see the same problem: What happens with the `TodosApi` dependencies? They are injected in the main_xxx.dart. When creating an instance of `TodosApi` I might again have dependencies that I don't want to inject directly.

How would it look like, if `TodosApi` and `UserApi` would both be injected to bootstrap, and both depend on `Dio` which itself depends on `baseUrl`?

**Comment by chonghorizons** [comment]
> Thank you for your detailed answer. I will check out the new example.
> 
> For the bootstrapping approach, I still see the same problem: What happens with the `TodosApi` dependencies? They are injected in the main_xxx.dart. When creating an instance of `TodosApi` I might again have dependencies that I don't want to inject directly.

I'd have to understand your use case more clearly.
This is an architecture question, since it seems like there are at least 3 or 4 ways that will all work.

Each implementation may have plusses and minuses. It will depend on weighing factors. To me, it seems like the factors might include:
1) testing and modularity
2) not repeating yourself
3) delaying injection/connections to later, for example if something is computationally intensive
4) pre-loading so that UI is responsive


> 
> How would it look like, if `TodosApi` and `UserApi` would both be injected to bootstrap, and both depend on `Dio` which itself depends on `baseUrl`?

I don't see a problem with that. Just put both in bootstrap.

> 
> Edit: Another thing that comes to my mind: The repositories are created lazily when needed, but the data sources and their dependencies are created on app start, whether they are needed or not. This also seems not to be ideal.

It'll depend on use case. You might want preload at app start for snappy UI. (It can be done asynchronously, I think, and not block the UI). Or, if it expensive to make the data connection, you might want to delay it. In that case, you could put your repository further down in the widget tree, where it might get disposed of.

It might also be possible to have the repository delay connection by adding a connect method/function and calling it manually or as needed.

So, agree "not ideal" in all cases. But sometimes could be ideal.

Let me know what you think. I'm still learning patterns.

@stefangaller

**Comment by stefangaller** [comment]
Is this how you would do it?
```
void bootstrap(datasource1, datasource2){
  final repository1 = Repository(datasource1);
  final repository2 = Repository2(datasource2);
  runApp(App(repository1, repository2);
}
```
Then the main would need to look like this:
```
main(){
  final baseConfig config = BaseConfig(...);
  final dio = Dio(baseConfig);
  final dataSource1 = DataSource1(dio);
  final dataSource2 = DataSource2(dio);
  bootstrap(dataSource1, dataSource2);
}
```

If want to mock dio, I'd need to add another layer for bootstrapping:
```
  bootstrapRepositories(Dio dio){
     final dataSource1 = DataSource1(dio);
    final dataSource2 = DataSource2(dio);
    bootstrap(dataSource1, dataSource2);
  }
```
 and the main would become this:
```
main(){
  final baseConfig config = BaseConfig(...);
  final dio = Dio(baseConfig);
  bootstrapDio(dio);
}
```

And I could even add another layer if i want to mock `BaseConfig`.

**Comment by chonghorizons** [comment]
> Is this how you would do it?

@stefangaller looks pretty good and that it will work.
You definitely understand the tradeoffs and why. So that is the biggest thing.

In particular, does it meet the 4 factors I mentioned above? If so, then it works.



What do you think?

**Comment by chonghorizons** [comment]
You might add another layer so that bootstrapRepositories isn't coupled to dio. Like if you later want to use firebase or graphQL or another package or  ???. I actually have never used Dio.

 But you can always decouple later. And the important thing is you have one point where Dio is loaded and all UI interactions don't directly call Dio, they call the repository or they call blocs that call the repository.

**Comment by felangel** [comment]
Closing for now but feel free to either continue the conversation here or on [Discord](https://discord.gg/bloc) 👍
