### ISSUE TITLE
Question about events and data flow

### ISSUE THREAD

**Issue by nhwilly** [felangel/bloc#313]
When we last spoke, you outlined a simple rule for flows:

Event flow:
1. UI
2. Bloc
3. Repo
4. Provider
5. ApiClient

then Data flow back

1. ApiClient
2. Provider
3. Repo
4. Bloc
5. UI

That makes perfect sense.  But what happens when an event starts below the `bloc`?  The way I've crafted this, the UI is always listening to the `bloc`, and the `bloc` knows how to call on the lower level services, but those lower levels always responding to a call, not initiating one.

In my case, the `apiClient` might generate a change in data (access tokens) that need to flow back up to the provider and then to the repo and so on.

I know I can handle this with regular streams, but would it make sense to create a `repo` as a `bloc` that dispatches events to a `provider` (as another bloc) the dispatches events to the `apiClient`?

**Comment by nhwilly** [comment]
That seems kind of insane to do at the `apiClient` level for every call.  

Perhaps I'll just have a stream that the next `bloc` above that hears when the access tokens change and only then on a refresh.  That can bubble up to `provider` which can bubble up to `repo` which can bubble up to the `bloc` which can dispatch an event.

**Comment by felangel** [comment]
Hey @nhwilly 👋 

Can you please provide a bit more context regarding why you would want to notify of a changed access token? I don’t think the provider, repo, or bloc should have to know about the access token. It should be strictly scoped to the api client ideally since it’s an implementation detail of the network layer.

**Comment by nhwilly** [comment]
I think I can do this all with blocs, if I limit them to the proper scope and keep them small.

If an access token changes inside the `apiClient`, at the very least, I'll need to persist the new values in a key chain until the user logs out.  I originally didn't have the persistence logic in the `apiClient`, I had it in the `provider`.

In a nutshell, the `user` is in essence created from the content of the access token.  What I had set up was the provider getting the new access token and providing a `user` to the repo which provided a user to the bloc which provided a state change to the ui.

A user object or menu objects will have learn about the new access token in order to pick up changes in permissions and other pertinent data.

So that's how I ended up with events *starting* in the lowest layer (in this case the `apiClient`) and having them bubble up to the higher layers.

I'm going to fill this out today and see where I get cornered.  I think we have all the pieces, not the relationships between them.

**Comment by felangel** [comment]
I would add key chain storage as a dependency to the api client in that case.

Then, if you have a `UserBloc` you can have the bloc have a dependency on the `UserRepository` which can expose a `getUser` method. Hope that makes sense! 👍 

Closing this for now since it seems like you're on the right track but feel free to comment with additional questions and I'm more than happy to continue the conversation 😄
