### ISSUE TITLE
Flutter Bloc documentations for using Freezed Bloc examples.

### ISSUE THREAD

**Issue by BiswajitKrPaul** [felangel/bloc#3196]
The Documentation is really great with the examples given in site. Can you guys also include some good examples for using Bloc with Freezed package?

**Comment by yh-luo** [comment]
Hi, I created [freezed_weather](https://github.com/yh-luo/freezed_weather) as an example.
I recently learned to use [freezed](https://pub.dev/packages/freezed) and fell in love with its simplicity, hope it helps!

**Comment by mathiasgodwin** [comment]
@yh-luo Thank you for creating that! I've been looking for easy life all the way. My life has been a lot of boilerplate ever since, you know, I use Flutter bloc with clean code architecture and at least the time of code writing will be reduced learning to use freezed efficiently. I'll follow you for more of this.

**Comment by BiswajitKrPaul** [comment]
Thanks @yh-luo  for the example.

**Comment by sanchan** [comment]
Thanks @yh-luo, your example is exactly what I needed! Now everything is much clearer!
