### ISSUE TITLE
Seperated Loading for two different state

### ISSUE THREAD

**Issue by gvory** [felangel/bloc#3268]
I have a case.

Example:

`class XLoaded{
  final String a;
  final String b;

  XLoaded(this.a, this.b);
 //has copywith etc.
}`

And emit XLoaded first time, init a  and b fields.
So later I want to update only b(Future process) using copywith state and I want to put loading only where I call b.

What is the best way to do that?

**Comment by felangel** [comment]
Hi @gvory 👋 
Thanks for opening an issue!

It sounds like you want to manage the state of a and b independently. In that case, I'd recommend having a separate bloc/cubit to manage the state of a and b so that you can react to state changes independently to each of them rather than having a single monolithic bloc.

Hope that helps 👍
