### ISSUE TITLE
Global access vs Local access

### ISSUE THREAD

**Issue by CanGonulacar** [felangel/bloc#3272]
hello, is there any performance problem in defining BlocProvider as global and local? Can you write your preferences?

**Comment by varipov** [comment]
Hi @felangel 
My team has been working with flutter and BLoC not so long ago, so we don't know all the details yet. Since the beginning of the project, we have started to separate our Blocks by the functions they perform, but now we are still registering them globally in the main.dart

Tell me how do you prefer to initialize your local Blocks?

In the examples, I found two ways to initialize blocks:

1. Initialize in main.dart via MultipleBlocProvider. You have already described the disadvantages of this approach
2. Create an additional wrapper class SomePage -> SomeWidget
Page:
```
class CounterPage extends StatelessWidget {
  /// {@macro counter_page}
  const CounterPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => CounterCubit(),
      child: const CounterView(),
    );
  }
}
```
Widget
```
class CounterView extends StatelessWidget {
  /// {@macro counter_view}
  const CounterView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      ...
      body: Center(
        child: BlocBuilder<CounterCubit, int>(
          builder: (context, state) {
            ...
          },
        ),
      ),
      ...
    );
  }
}
```
3. We also discovered another way to initialize blocks, which allows you not to create additional files:
```
class CounterPage extends StatelessWidget {
  final CounterCubit _counterCubit = CounterCubit();

  const CounterView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      ...
      body: Center(
        child: BlocBuilder<CounterCubit, int>(
          bloc: _counterCubit,
          builder: (context, state) {
            ...
          },
        ),
      ),
      ...
    );
  }
}
```
Here we also don't lose the ability to pass the block down the widget tree:
```
class CounterPage extends StatelessWidget {
  final CounterCubit _counterCubit = CounterCubit();

  const CounterView({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => _counterCubit,
      child: Scaffold(
        ...
        body: Center(
          child: BlocBuilder<CounterCubit, int>(
            builder: (context, state) {
              ...
            },
          ),
        ),
        ...
      ),
    );
  }
}
```

How do you feel about the option I indicated?
Unfortunately, the documentation does not say anything about the strict need to use BlockProvider
