### ISSUE TITLE
refactor: Bloc templates

### ISSUE THREAD

**Issue by BartWesthoff** [felangel/bloc#3282]
I have followed the [firebase login example](https://bloclibrary.dev/#/flutterfirebaselogintutorial) and after I did install the bloc plugin for Android Studio. The plugin uses a different format for creating blocs. My proposal is to change the plugin slightly so it follows this tutorial. In general this approach is more readable and holds on to specifying the events which leads to general code quality. 

I already made a [pull request](https://github.com/felangel/bloc/pull/3281).

**Comment by felangel** [comment]
Hi @BartWesthoff 👋 
Thanks for opening an issue!

We discussed this as part of https://github.com/felangel/bloc/issues/2731 and decided to leave it as is in order to keep the snippet as simple and generic as possible. It's not always desirable to split your code into multiple event handlers because event handlers are run concurrently so I'd prefer to leave the snippets as they are.

Let me know what you think, thanks!

**Comment by BartWesthoff** [comment]
Hi @felangel 👋

I see the feedback from earlier. Is it still possible to change this for my development enviroment locally? Instead of making a new plugin from scratch?

**Comment by felangel** [comment]
> Hi @felangel 👋
> 
> I see the feedback from earlier. Is it still possible to change this for my development enviroment locally? Instead of making a new plugin from scratch?

Yup, you can [create your own VSCode Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets) or [edit the Live Templates on IntelliJ](https://www.jetbrains.com/help/idea/creating-and-editing-live-templates.html). Let me know if you have any questions about that and I'm happy to help 👍

**Comment by BartWesthoff** [comment]
> 

Hi Felangel,

Thank you alot! learned something new :)
