### ISSUE TITLE
refactor: blocTest.act -> blocTest.action

### ISSUE THREAD

**Issue by vandadnp** [felangel/bloc#3299]
Hi and thank you for Bloc and for blocTest in Flutter. I really appreciate all the work that has gone into creating this library which I personally love.

If we look at blocTest function's signature:

```dart
void blocTest<B extends BlocBase<State>, State>(
  String description, {
  FutureOr<void> Function()? setUp,
  required B Function() build,
  State Function()? seed,
  Function(B bloc)? act,
  Duration? wait,
  int skip = 0,
  dynamic Function()? expect,
  Function(B bloc)? verify,
  dynamic Function()? errors,
  FutureOr<void> Function()? tearDown,
  dynamic tags,
}) {
```

The parameter `act` sticks out in that it _probably_ means action but it's not spelled fully. It's nit picking but I'd really love for this parameter to be deprecated and become `action` instead unless of course you meant for it to say "act" as in "act" on something. But I personally prefer "action" as it's more explicit as to it wanting to perform an action on the bloc.

If that's the case and it should say "action", please let me know and I might be able to send a pull request.

Thank you again

**Comment by felangel** [comment]
Hi @vandadnp 👋 
Thanks for opening an issue!

The reason for the `act` naming is because the goal was to have the parameters read like distinct phases rather than descriptions. This was inspired in part by [arrange, act, assert](https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests). So in this context, act is not short for action -- it's the phase where you execute code that "acts" on (does something to) the subject under test.

Let me know if that helps and thanks again for opening the issue and supporting the library 💙

**Comment by vandadnp** [comment]
That explanation makes perfect sense @felangel , thanks for taking the time to reply to my issue. I will close this issue now that I know the reasoning behind this.

Thank you for Bloc again.
/v

**Comment by felangel** [comment]
> That explanation makes perfect sense @felangel , thanks for taking the time to reply to my issue. I will close this issue now that I know the reasoning behind this.
> 
> Thank you for Bloc again. /v

Thanks for all that you do for the community as well! 💙 🙏
