### ISSUE TITLE
Rebuild current state by a given stream event.

### ISSUE THREAD

**Issue by pabloserranof** [felangel/bloc#330]
Looking at the bloc with stream example:
https://github.com/felangel/bloc/blob/master/examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart

How to rebuild the current state rather than creating a new one as the stream example does? 

Let's say that I have a bloc with +10 different states and I don't really want a new state by a given stream event. I just want to rebuild the current state (with some new data coming from the stream event). This applies to any of the states of the bloc. Does it make sense?

Thanks for the great work! :)

**Comment by felangel** [comment]
Hi @pabloserranof 👋 
Thanks for opening an issue!

Regarding your question, the bloc library enforces immutable state so you must always yield a new instance of your state instead of mutating the `currentState`. For your use-case, I would recommend implementing a `copyWith` method for your state which would allow you to copy and update the `currentState` easily. You can check out the [infinite list tutorial](https://felangel.github.io/bloc/#/flutterinfinitelisttutorial?id=post-states) for an example.

Closing for now but feel free to comment with additional information/questions if that didn't help. 👍
