### ISSUE TITLE
docs: design questions

### ISSUE THREAD

**Issue by matanshukry** [felangel/bloc#3307]
I have multiple questions regarding design using bloc. I believe those questions, and the answers to them, can be either added to the FAQ or to different parts of the documentation and greatly help other people as well both use and design better systems using bloc.

The questions:

## Question 1
Looking at the todos_example , and specifically the api: https://github.com/felangel/bloc/blob/master/examples/flutter_todos/packages/todos_api/lib/src/todos_api.dart , it uses a stream (part of the signature). That stream acts a bit like a "memory storage" for the data, since it keeps the last list, can be accessed, and overwrite it when needed - which sounds like the job of the repository rather than the api. From what I can understand about the repository/api:
* The API should do basic operations, like the crud - fetch, get, etc. No caching or storing values of any kind.
* The repository should do the catching/storing/etc, if desired/needed.

## Question 2
The `AuthenticationRepository` uses `stream.map` method to return a user property, but inside that method it also adds caching: https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart#L184 . While that is working, it sounds like `map` isn't the ideal place to do that. Specifically, if no one listens to that `user` property, it means the cache won't ever be written. Right?

## Question 3
Looking at the `flutter_firebase_login`, I was thinking on how to expand it to include user data (e.g. "favorite movie"). Using firestore, I wanted to store a document-per-user (e.g. `/users/{userUid}`), controllable and viewable only by the user. I was thinking on how to design it:

A. Create a `user_info_api` package that can `fetchUserInfo` and `saveUserInfo`.
B. Create a `user_info_api_firestore` impl that uses firestore to fetch and save the data.
C. create a `user_info_repository` that uses `user_info_api`.

How can we then connect between this new `user_info` concept and our old (auth) user ? I can see multiple options:

A. `user_info_repository` can use the `authentication_repository` and listen for changes on the `user` object.  When that happens, it will write the user object to the cache with the id.It could then have `currentUserInfo` property, which will load data from the cache.
B. `AppBloc` can use `user_info_repository`, and create a lazy cached UserInfo property based on the current user.
C. another option?

I believe A is the preferred out of A & B, since it allows other repositories (non-bloc & non-widgets) usage of the UserInfo object.

## Question 4
Following the examples & above questions style, we can see we're going to have a lot of packages, even for a medium-app. That is, for each domain object we'll need at least 3 packages: `<obj>_api`, `<obj>_api_some_impl` and `<obj>_repository`. Is there a better way to organize the domains/packages, rather than have a huge list of packages under the `packages` directory?

**Comment by matanshukry** [comment]
1. I didn't see it, but I disagree with both limitations in there:
a.  sending full list - you can use CRUD operations for single item (saveTodo/loadTodo/deleteTodo etc), which means you don't have to send/receive the full list everything. It can be done on all layers - api,service,repository,etc.
b. `The app must contain logic to ask for updates periodically.` - perhaps it's just wording, but imagine a list where the user can refresh it by pulling the listview. I wouldn't call that periodically updating, and it's a valid (and sometimes the better way) of designing an application.

2. `... in case there's no connection, use [currentUser](...) to retrieve the last value Firebase emitted.`
a. `currentUser` will not return the last value Firebase emitted. It returns the last value we stored in the `_cache`.
b. If no one uses the `user` property, then the `map` method will not be called, and no one will call `_cache.write` - so the cache will always be empty.
c. That means with the current implementation, if no one uses the `user` property - `currentUser` will always return `User.empty`


3. I don't really follow you here. Even if you have small & new `favorite_movie_api` package - how would it query the data? how would one use it? how would it know to re-query the data when the user changes?

4. I agree with all that you said, although I don't want to have them on different repository either. Perhaps single directory named `<obj>`, and inside it `<obj>_api`, `<obj>_api_impl`, and `<obj>_repository`. Not sure if it's possible, but will try it.

**Comment by marcossevilla** [comment]
1. yeah, that's why later it says `In addition, todos can be created, deleted, or updated individually. For example, both deleting and saving a todo are done with only the todo as the argument. It's not necessary to provide the newly updated list of todos each time.` In this case, we just focus on updating the stream and that allows us to make a reactive list of streams, those are just implementation details. As for b, a pull to refresh is valid if you don't use a reactive approach, if you use it in this specific case it would force an update to the todos list but probably the state will not change as it's already using the latest values from the stream.
2. we do use the `currentUser` getter! check [here](https://github.com/felangel/bloc/blob/4b8e2f43be77f76684fb5b93c8581b5db1f08d6f/examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart#L16). It's used when the `AppBloc` is created to see if there was any value from a previous app execution, then we use the `user` getter to [subscribe](https://github.com/felangel/bloc/blob/4b8e2f43be77f76684fb5b93c8581b5db1f08d6f/examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart#L22) to any new updates on that user. `user` will always be listened to and `currentUser` is just to check for a previous state, that's why I said that it returns the last emitted value from Firebase.
3. well, it all comes down to how you structure data from your collections, I like to have an API for each one so if they interact with each other, I can define those interactions in a repository. You can have a `movies_api`, `favorite_movies_api`, and `user_api` if you want to relate that data. `user_api` would be tied to FirebaseAuth so you can have additional data from a user other than what Firebase allows you on their authentication service. The nice thing about Firebase is that it already exposes streams of data so all of your APIs can be reactive and give updates in real-time.
4. I suggest you group just declarations and implementations, for example, you can have a directory named `<obj>` where you have `<obj_api>` and `<obj_api_impl>`. But you should keep your repository separated from those other packages as it should not be coupled to implementations, even if it's just a folder that makes it more organized IMO.

**Comment by marcossevilla** [comment]
will close this issue but feel free to continue the conversation and I'm happy to help!
