### ISSUE TITLE
chore: How can i wait the bloc execution in testWidgets

### ISSUE THREAD

**Issue by PowerPaloma** [felangel/bloc#3316]
**Description**
I have the following scenario: 
screen button tap -> bloc event -> do a request -> bloc state -> navigate 

i want to test that if i tap the button i can navigate.. 

```dart
Future<void> pumpScreen(WidgetTester tester) async {
    await tester.pumpWidget(
      MultiProvider(
        providers: [
          Provider<Navigation>(create: (context) => navigation),
          Provider<Bloc>(create: (context) => bloc),
        ],
        child: const MaterialApp(
          home: Screen(),
        ),
      ),
    );
    await tester.pumpAndSettle();
}
```

```dart
testWidgets('', (tester) async {
  mockRepositorySucess();

  await pumpScreen(tester);
  await tester.tap(find.text('button'));
  await tester.pumpAndSettle();


  verifyRepositoryCall()
  verifyNavigation()
  },
);

```

The test is reaching the verification and the calls were not done yet. How can i wait for the bloc execution in testWidgets? Thanks

**Comment by marcossevilla** [comment]
hi, @PowerPaloma 👋  I'd suggest taking a look at this [test](https://github.com/felangel/bloc/blob/4b8e2f43be77f76684fb5b93c8581b5db1f08d6f/examples/flutter_firebase_login/test/login/view/login_form_test.dart#L225) from the flutter_firebase_login example.

otherwise, if you can share a minimal reproducible sample it would be great because I can't tell what your Navigation, Bloc, and Screen do 👍
