### ISSUE TITLE
Question: Base Bloc

### ISSUE THREAD

**Issue by code-282** [felangel/bloc#3336]
**Description**
I am trying to create `BaseBloc`, `BaseEvent` and `BaseState` classes which will be used in `BaseScreen` widget to handle common business logic in one location. These base classes will be extended by each feature class (example: `HomeBloc` will extend `BaseBloc`).

The issue is that when trying to build widget using `BlocBuilder` with feature bloc (i.e. `HomeBloc`), it fails because **'HomeBloc' doesn't conform to the bound 'StateStreamable<HomeState>' of the type parameter 'B'**

**Steps To Reproduce**

1. Create base classes
2. Create feature class which extends base classes
3. Build widget using BlocBuilder 

**Expected Behavior**
It is expected that `BlocBuilder` should accept Feature bloc (i.e. `HomeBloc`) as it extends `BaseBloc` which original extends `Bloc` class from library

**Screenshots**
<img width="929" alt="Screen Shot 2022-04-23 at 11 16 34 PM" src="https://user-images.githubusercontent.com/104275316/164945248-2f7d7f7d-1559-4055-b37e-ed52f7d9a67a.png">

**Additional Context**
You can find required files to reproduce issue in [https://github.com/code-282/base_bloc_sample_app](https://github.com/code-282/base_bloc_sample_app)

**Comment by deniskrr** [comment]
Hi @code-282 ,

The problem is that `HomeBloc` is essentially just a `Bloc<BaseEvent, BaseState>`—and not `Bloc<HomeEvent, HomeState>` as you would expect.

Although you use your `HomeState` and `HomeEvent` as the  `BlocBase`'s actual types, they are not passed further to the `Bloc`'s actual types (which the `BlocBuilder` would use eventually).
<img width="339" alt="image" src="https://user-images.githubusercontent.com/46903083/164983233-3b25c6b9-fe01-41db-a6c7-6fa8bcb70e0d.png">

**Comment by code-282** [comment]
Thanks for clarification, but in this case I am losing access for HomeState as the state in scope of building bloc will be BaseState.

```
child: BlocBuilder<HomeBloc, BaseState>(
            builder: (context, state) {
              //state is now BaseState so HomeState can't be used to build home widget 
              return Text("Home Screen");
            },
        )
```

**Comment by deniskrr** [comment]
With your current structure, this would be possible if you were to type-check the `state` inside the builder.
___

Alternatively—and I think this would be the better solution—you can define a single concrete (not abstract) `BaseClass` similarly to [this example](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/lib/edit_todo/bloc/edit_todo_state.dart).
This is needed to avoid multiple inheritance branches. Currently, `HomeState` is not a `PreprocessedBaseState` so you would need to use their common parent, i.e. `BaseState`.

After that, you can define the `BaseBloc` as:
```
class BaseBloc<Event extends BaseEvent, State extends BaseState> extends Bloc<Event, State> {
``` 

And now, your initial builder with `HomeState` should work because you'll eventually have a `Bloc<HomeEvent, HomeState` there.
