### ISSUE TITLE
buildWhen not triggered on initial render using Cubit

### ISSUE THREAD

**Issue by jannisnikoy** [felangel/bloc#3344]
**Description**
When using a BlocBuilder in combination with a Cubit, the buildWhen logic seems broken on the initial rendering of a widget. With the sample BlocBuilder code:

```
BlocBuilder<TestCubit, TestState>(
    bloc: context.read<TestCubit>()..getTestData(),
    buildWhen: (oldState, current) => current is TestLoaded,
    builder: (context, state) {
        if (state is TestLoaded) {
            return const Text('Loaded');
    }

    return Text('Other state: $state');
})
```

I would expect builder: to only be called when the Cubit emits state TestLoaded. However, on the first render of the widget, it gets triggered for both TestLoading and TestLoaded states, not calling buildWhen:. On any subsequent state changes in TestCubit, the buildWhen gets called and the behavior of the above code is as expected.

This issue seems explicitly in combination with cubits, if I were to replace TestCubit with a similar TestBloc, the issue described above does not occur.

For the sake of demonstrating the issue; I've created the following cubit:

```
abstract class TestState {}

class TestLoading extends TestState {}

class TestLoaded extends TestState {
  final String result;

  TestLoaded(this.result);
}

class TestCubit extends Cubit<TestState> {
  TestCubit() : super(TestLoading());

  void getTestData() async {
    emit(TestLoading());

    // do stuff

    Future.delayed(const Duration(milliseconds: 1500)).then(
      (value) {
        emit(TestLoaded('data'));
      },
    );
  }
}
```

This issue was previously reported as #3257 but was closed due to lack of reproducable code.

**Comment by felangel** [comment]
Hi @jannisnikoy 👋 
Thanks for opening an issue!

As mentioned in the API docs, `buildWhen` is purely for optimizations and does not guarantee that the `builder` won't get called. In this case, the initial build must occur otherwise `builder` would not be able to return a widget and we would end up rendering `null` which is not a valid widget. If you want to prevent unnecessary rebuilds you can use `context.select` or `BlocSelector` -- `buildWhen` should only be used as an optimization and you should assume `builder` will be called on each frame.

Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with any questions and I’m happy to continue the conversation 👍
