### ISSUE TITLE
docs: 

### ISSUE THREAD

**Issue by githubmonkey** [felangel/bloc#3399]
(https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/packages/form_inputs/lib/src/password.dart)
(https://bloclibrary.dev/#/flutterfirebaselogintutorial?id=password)

This is a minor issue but I think the Password regex in the tutorial is wrong. At least I can't get it to match anything.

I changed mine to `RegExp(r'^(?=.*?[A-Za-z]).{8,}$');` which would match letters only.

**Comment by ShakyaCsun** [comment]
The Regex used in tutorial enforces following rules:
1. Password only has letters/alphabets A-Z, a-z and numbers.
1. Password has at least one alphabet letter.
1. Password has at least one digit.
1. Password has at least 8 characters.

So `abcdefg1`, `ABCDEFG1`, `1234567a`, etc. are all valid passwords for the regex. But `@abcdefg1` is not valid because of rule 1.
It is kind of confusing that it doesn't allow any special characters or spaces, specially if you are not familiar with regex. Maybe we could add a comment or simplify the password validity checker to tackle this.

Also on a side note, the regex you changed to matches any combination of characters of length 8 or greater if they have at least one uppercase or lowercase letter i.e. it would match `@      A` but not `@123456!`. You can use sites like regex101.com to check the regex.

**Comment by githubmonkey** [comment]
Thanks for confirming that it works for you. I had dropped the sample code into my own example so maybe I'm using a different version of a core lib.
