### ISSUE TITLE
docs: Two contrary information between the documentation and the Todos example

### ISSUE THREAD

**Issue by makanddream** [felangel/bloc#3404]
Hello everyone, I come to you because there are two contrary information between the documentation and the Todos example. :monocle_face:

- In the [Architecture section](https://bloclibrary.dev/#/architecture?id=data-provider) of the documentation, you mention that the data provider should return the data in a generic way, like a string (RawData).

- However in the Todos example in the data provider (local_storage_todos_api) you return a list of Todo objects.

Isn't it up to the repository to create the stream and the Todo list?
Who enters documentation or example Todo is correct?

Feel free to correct me or explain me if I ever misunderstood something. :smile:

**Comment by huytc** [comment]
It's probably for the sake of simplicity. The tutorials emphasize on showcasing how to use the BLoC library, not how to write perfectly clean code. Just my two cents.

**Comment by felangel** [comment]
Hi @makanddream 👋 
Thanks for opening an issue!

> In the [Architecture section](https://bloclibrary.dev/#/architecture?id=data-provider) of the documentation, you mention that the data provider should return the data in a generic way, like a string (RawData).

What we meant by this is that the data provider returns data in its raw form (as close as possible to what it looks like in the source). The `local_storage_todos_api` still adheres to that because it's returning a Dart object that represents the todo entity as it is stored in local storage (it's just deserializing the json).

Hope that helps! Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍
