### ISSUE TITLE
refactor:  Remove provider as dependency

### ISSUE THREAD

**Issue by CodeDoctorDE** [felangel/bloc#3495]
**Description**

I heard provider will be deprecated https://twitter.com/remi_rousselet/status/1558722656400285696.
flutter_bloc uses it as dependency.

**Comment by felangel** [comment]
Hi @CodeDoctorDE
Thanks for opening an issue!

flutter_bloc didn’t anyways depend on provider but we added the dependency in an attempt to provide more consistency across flutter applications.

If provider is deprecated we can remove the dependency. it will be a breaking change because you will no longer be able to use BlocProvider in a MultiProvider.

**Comment by felangel** [comment]
Closing for now since there are no actionable next steps. We can revisit this if/when provider is officially deprecated 👍
