### ISSUE TITLE
fix: program halt on emit.onEach

### ISSUE THREAD

**Issue by ahmad-olu** [felangel/bloc#3513]
i have two diffrent stream from an api, with the emit.oneach from the new bloc package i am able to emit the streams but the code does not continue, it halts after the first stream and i also tried diffrent transformer maybe it would work but it didn't.

```on<ProfileEvent>(
      (event, emit) async {
        await event.map(
          loadUser: (e) async {
            emit(state.copyWith(status: ProfileStatus.loading));
            try {
              final user =
                  await _iUserRepository.getUserWithId(userId: e.userid)

               await emit.onEach(
                 _iPostRepository.getPostA(userId: e.userid),
                 onData: (QuerySnapshot<PostA> postA) {
                   add(ProfileEvent.updatePostA(postA.items));
                 },
               );
               await emit.onEach(
                 _iPostRepository.getPostB(userId: e.userid),
                 onData: (QuerySnapshot<PostB> postB) {
                   add(ProfileEvent.updatePostB(postB.items));
                 },
               );

              emit(
                state.copyWith(
                  user: user!,
                  status: ProfileStatus.loaded,
                ),
              );
            } on Failure catch (e) {
              emit(
                state.copyWith(
                  failure: Failure(message: e.message),
                  status: ProfileStatus.error,
                ),
              );
            }
          },
          updatePostA: (e) async {
            emit(state.copyWith(postA: e.postA));
          },
          updatePostB: (e) async {
            emit(state.copyWith(postB: e.postB));
          },
          ...,
          ...,
        );
      },
      //transformer: restartable(),
    );
```
> N.B: i also want to add that the reason why their is an await infront of my emit.onEach is because i keep getting error of a bad way of doing.
>> and  I also want to add that the normal way of streaming data worked which is
`
_postASubscription?.cancel();
              _postBSubscription = _iPostRepository
                  .getUserPostA(userId: e.userid)
                  .listen((posts) async {
                add(ProfileEvent.updatePostA(posts.items));
              });

              _postBSubscription?.cancel();
              _postBSubscription = _iPostRepository
                  .getUserPostB(userId: e.userid)
                  .listen((posts) async {
                add(ProfileEvent.updatePostB(posts.items));
              });
`
and you cancel with

```
Future<void> close() {
      _postASubscription?.cancel();
      _postBSubscription?.cancel();
      return super.close();
    } 
```

**Comment by c0pp1ce** [comment]
_A guess in the dark_

1. Without transformer : As long as the postA stream is not closed, your loadUser event wont progress any further since you  `await` the `emit.onEach`. The updatePostA event gets through because events are handled concurrently per default.

2. With `transformer: restartable()`  :  You seem to be using a single `EventHandler`. This leads to the loadUser event being canceled as soon as the first updatePostA event is added.

_Conclusion_

I would suggest changing how you handle the events. For example having one event handler + start/end events per stream and using the restartable transformer (to cancel the streams once you dont need them anymore).
You also could try to combine the streams and handle them as one to reduce the amount of code needed.
