### ISSUE TITLE
Question: Can I verify State changes on Stream Events inside blocTest?

### ISSUE THREAD

**Issue by svnbstn** [felangel/bloc#3573]
### Verify State Changes on Stream events Bloc test

As I mentioned above I'm currently learning how to test blocs properly and i stumbled over an "issue". 
Am I able to verify if the color inside my State is the color it should be? The code below only lets me know if my ColorBloc emits the states but I am not able to verify the colors inside the state. 

In the comments behind each state you can see the color inisde the state. 

```dart
blocTest<ColorBloc, ColorState>(
    'Color Bloc emits correct number of states on Stream events',
    build: () => ColorBloc(mockCounterBloc),
    setUp: () => whenListen<CounterRepoState>(
      mockCounterBloc,
      Stream.fromIterable(
        [
          const RepoCounterIncrementSuccessState(1),
          const RepoCounterIncrementSuccessState(3),
          const RepoCounterIncrementSuccessState(6),
          const RepoCounterIncrementErrorState(0),
        ],
      ),
    ),
    expect: () => [
      isA<ColorChangedState>(), // Colors.brown
      isA<ColorChangedState>(), // Colors.green
      isA<ColorChangedState>(), // Colors.orange
      isA<ColorChangedState>(), // Colors.red
    ],
  );
```

I know how to verify the last color emitted, but I wanted to know if there is a way to verify in the same way I can use the expect funtion. If that makes sense 😄 

Thanks for the help ☺️

**Comment by svnbstn** [comment]
I guess I found a solution but i do not know if this is best practice. 
Can someone please confirm that what I'm doing is right? 😂 

```dart
blocTest<ColorBloc, ColorState>(
    'Color Bloc emits correct number of states on Stream events',
    build: () => ColorBloc(mockCounterBloc),
    setUp: () => whenListen<CounterRepoState>(
      mockCounterBloc,
      Stream.fromIterable(
        [
          const RepoCounterIncrementSuccessState(1),
          const RepoCounterIncrementSuccessState(3),
          const RepoCounterIncrementSuccessState(6),
          const RepoCounterIncrementErrorState(0),
        ],
      ),
    ),
    expect: () => [
      isA<ColorChangedState>().having((e) => e.color, 'color', Colors.brown),
      isA<ColorChangedState>().having((e) => e.color, 'color', Colors.green),
      isA<ColorChangedState>().having((e) => e.color, 'color', Colors.orange),
      isA<ColorChangedState>().having((e) => e.color, 'color', Colors.red),
    ],
  );
```

**Comment by Luci3b** [comment]
_Disclaimer: I'm a new dev and I have been using this package for almost a year, any better answers or corrections are welcome._

> Am I able to verify if the color inside my State is the color it should be?

The answer is yes.

Let's say we have this code:

```dart
// color_event.dart
abstract class ColorEvent extends Equatable {
  @override
  List<Object> get props => [];
}

class ColorChanged extends ColorEvent {
  final Color color;

  ColorChanged({required this.color});

  @override
  List<Object> get props => [color];
}
```
```dart
// color_state.dart
enum ColorStatus { initial, loaded }

class ColorState extends Equatable {
  final ColorStatus status;
  final Color color;

  const ColorState({
    this.status = ColorStatus.initial,
    this.color = Colors.blue,
  });

  ColorState copyWith({
    ColorStatus? status,
    Color? color,
  }) {
    return ColorState(
      status: status ?? this.status,
      color: color ?? this.color,
    );
  }

  @override
  List<Object> get props => [status, color];
}
```
```dart
// color_bloc.dart
class ColorBloc extends Bloc<ColorEvent, ColorState> {
  ColorBloc() : super(const ColorState()) {
    on<ColorChanged>(_onChanged);
  }

  void _onChanged(ColorChanged event, Emitter<ColorState> emit) {
    final color = event.color;

    return emit(state.copyWith(status: ColorStatus.loaded, color: color));
  }
}
```

Then using the [bloc_test](https://pub.dev/packages/bloc_test) package:

```dart
// color_bloc_test.dart
void main() {
  test('Its initial state should be [ColorState()]', () {
    expect(ColorBloc().state, const ColorState());
  });

  blocTest(
    'Should emit correct state when a color is passed to ColorChanged',
    build: () => ColorBloc(),
    act: (bloc) => bloc.add(ColorChanged(color: Colors.green)),
    expect: () => const [
      ColorState(status: ColorStatus.loaded, color: Colors.green),
    ]
  );
}
```

Since _expect_ is an optional Function that returns a Matcher which the bloc under test is expected to **emit after act is executed** as said in the [pub.dev page](https://pub.dev/packages/bloc_test), we need to create only a test to verify if the `ColorBloc()` state instance is our initial state.

And about the color we can easily verify returning a list of expected states in our expect function.

I think using Bloc for controlling only Colors is a bit of overkill, consider using [Cubit](https://bloclibrary.dev/#/coreconcepts?id=cubit) or [ValueNotifier](https://api.flutter.dev/flutter/foundation/ValueNotifier-class.html).

Packages used:
- [bloc_test](https://pub.dev/packages/bloc_test) 9.1.0;
- [equatable](https://pub.dev/packages/equatable) 2.0.5;
- [flutter_bloc](https://pub.dev/packages/flutter_bloc) 8.1.1

Flutter version 3.3.3
Dart version 2.18.2

**Comment by svnbstn** [comment]
thank you for your effort! Your Concept of not using the `isA<ColorChangedState>()`and instead using `ColorChangedState(Colors.brown)` works excactly like my comment above and might be a bit easier to read. 

Thanks again for your example, it helped alot to understand ☺️
