### ISSUE TITLE
State mutable if Map is used

### ISSUE THREAD

**Issue by paqio** [felangel/bloc#366]
**Describe the bug**
I am not sure if this is a bug, as this is how dart works. But basically if the variable is a Map, because its values are actually references, its possible to alter the value from widget, so that the "immutable" state actual is changed.

**To Reproduce**
Create a state with Map. 
Alter its values anywhere.
No events triggered.

I believe this is quite obvious problem, how does one solve this?

**Comment by felangel** [comment]
Hi @paqio 👋 
Thanks for opening an issue!

This is working as expected and you must always return a new instance of state instead of mutating the current state. You can refer to the [core concepts](https://felangel.github.io/bloc/#/coreconcepts) for more details but you should never change the value of your state; instead you can implement a `copyWith` method for convenience or just manually yield a new state instance in `mapEventToState` in order to trigger state changes.

Hope that helps and let me know if you have additional questions 👍
