### ISSUE TITLE
feat: Add Widget BlocProsumer

### ISSUE THREAD

**Issue by guenth39** [felangel/bloc#3662]
**Description**

I would love to have a Widget that combines `BlocProvider` and `BlocBuilder` / `BlocConsumer` / `BlocSelector`. I have these widgets very often directly among each other.

**Comment by felangel** [comment]
Hi @guenth39 👋 
Thanks for opening an issue!

While I don't recommend this, you can already make such a widget yourself without any changes to the library.

I don't recommend combining those widgets for the following reasons:

- `BlocProvider` should ideally be decoupled from the others to allow for dependency injection/improved testability
- `BlocBuilder` and `BlocConsumer` are mutually exclusive because `BlocConsumer` includes `BlocBuilder`

Feel free to create custom widgets that fit your project's needs though 👍 

Let me know if that helps!

**Comment by guenth39** [comment]
Year okay. I already have such a widget, I just thought maybe it would be helpful for others as well. But it's not a must-have, so I will close this...
