### ISSUE TITLE
build: Dependency on test

### ISSUE THREAD

**Issue by JAOOOOO** [felangel/bloc#3664]
**Is it really necessary to depend on test ^1.16.0?**

This dependency tight dependency makes it very tough to work with other libraries, i.e auto_route_generator, mockito, etc

**Comment by felangel** [comment]
Hi @JAOOOOO 👋
Thanks for opening an issue!

The dependency constraint on package:test is actually very loose.

^1.16.0 means any version between 1.16.0 and 2.0.0 is allowed (>=1.16.0 <2.0.0). This range includes the latest version of package test so there shouldn’t be an issue due to the version of package:test. Hope that helps!

**Comment by JAOOOOO** [comment]
Thanks @felangel, 
I've been a big fan for a while. 
Yes I understand the range meant by ^1.16.0, yet this doesn't help with conflicting dependencies as lots of other libraries depend on older version of test.

**Comment by felangel** [comment]
> Thanks @felangel,
> I've been a big fan for a while.
> Yes I understand the range meant by ^1.16.0, yet this doesn't help with conflicting dependencies as lots of other libraries depend on older version of test.

Thanks for the support, I really appreciate it! Can you provide the libraries you are having trouble using due to this constraint?
