### ISSUE TITLE
fix: Stack overflow exception on IOS simulator

### ISSUE THREAD

**Issue by nikhith265** [felangel/bloc#3685]
**Description**
Stack overflow exception on Ios simulator debug mode if i add more number of providers on MultiBlocProvider

**step to Reproduce**
Add more number of providers to your multiBlocProvider or clone the project [https://github.com/nikhith265/widget_tree_limit_issue/tree/blocIssue](url)
and run on an IOS simulator

**Comment by felangel** [comment]
Hi @nikhith265 
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by nikhith265** [comment]
> Hi @nikhith265 👋 Thanks for opening an issue!
> 
> Can you please provide a link to a minimal reproduction sample? Thanks!

One way to reproduce issue was add more number of providers to the multiBlocProvider . I think we can't predict the exact number that causing the issue because it depend up on the particular device widget tree limitation that we are trying to run. In my case it is 62

**Comment by nikhith265** [comment]
here is the problem [https://github.com/nikhith265/widget_tree_limit_issue](url)

you can clone the project and try to run it on a Ios simulator

**Comment by tenhobi** [comment]
Hi, could you also attach a log of the exception you received?

**Comment by tenhobi** [comment]
Hi @nikhith265, from your sample, this is not an error related to Bloc, but rather to Provider or Nested packages. Try opening issue there. 🙏

**Comment by nikhith265** [comment]
no the same issue happened with Multiblocprovider too, when we initialized more bloc providers.
`════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4754 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
package:flutter/…/widgets/framework.dart:4754
The relevant error-causing widget was
BlocProvider<DirectAssessmentBloc>`

**Comment by nikhith265** [comment]
Please check this 
[https://github.com/nikhith265/widget_tree_limit_issue/tree/blocIssue](url)

**Comment by nikhith265** [comment]
> Hi @nikhith265, from your sample, this is not an error related to Bloc, but rather to Provider or Nested packages. Try opening issue there. 🙏

no the same issue happened with Multiblocprovider too, when we initialized more bloc providers.

try this [https://github.com/nikhith265/widget_tree_limit_issue/tree/blocIssue](url)

**Comment by tenhobi** [comment]
That might be true, but the point I am making is that no matter if that's `MultiProvider`, `ChangeNotifierProvider`, `BlocProvider`, `MultiBlocProvider`, if the issue is not only in `BlocProvider`, which is not based on your first example you showed where there is no `bloc` or `flutter_bloc` packages, the issue is most likely in the `provider` package itself, or in `nested` package that is used by the `provider`.

Just a note, `MultiBlocProvider` (from `flutter_bloc`) depends on `MultiProvider` (from `provider` package). As you can see here below. Therefore raise an issue in `provider` package and if that will be fixed, `MultiBlocProvider` will start to work automatically after it update its `provider` dependencies.

https://github.com/felangel/bloc/blob/e05b2c85a25dbcfb747e426a3d5b77be1411139d/packages/flutter_bloc/lib/src/multi_bloc_provider.dart#L50-L57

**Comment by felangel** [comment]
Closing this for now since as @tenhobi mentioned, it appears it's not due to `package:flutter_bloc` and should instead be raised in `package:provider`.
