### ISSUE TITLE
TextFormField is losing focus when typing

### ISSUE THREAD

**Issue by devfelipereis** [felangel/bloc#3702]
**Description**
TextFormField is losing focus when typing.

Building for macOS and Web.
Flutter 3.7.0

**Expected Behavior**
TextFormField should not lose focus when typing.

**Screenshots**
![image](https://user-images.githubusercontent.com/5348752/215787088-fd8534ca-536f-4444-a086-087035e2172e.png)

I already tried everything but the TextFormField will always lose focus after updating the state. I tried to set the caret position, request focus, remove BlocBuilder, etc. Nothing works.

The TextFormField will not lose focus if I remove the call to update the state.

Any help?

**Edit**

I managed to fix this using FocusNode + Debounce. You could remove that themeNameController and pass initialValue to initialize the text field (a unique key is required to update from external changes). 

![image](https://user-images.githubusercontent.com/5348752/215831453-d57286aa-85f9-43e5-b784-d57f90234558.png)

But what do you think? Is there another way to do this or am I doing something wrong?

**Comment by sed1ka** [comment]
That is not a bug on the bloc library. Your bug happened because you wrapped TextFormField with BlocBuilder, if you put the widget inside BlocBuilder that means the widget inside the BlocBuilder will continue to be rebuilt every time there is a change in the state. Also 'rebuilt' means it will return the condition of the TextFormField to its initial condition in the sense that the FocusNode will return to false.

Better if you ask on StackOverflow. put the code in the form of a text code, not a screenshot. So that other developers can help you quickly

**Comment by tenhobi** [comment]
Couldn't a `Key` help?

**Comment by devfelipereis** [comment]
I'm sorry guys. I found the issue.

I have a panel that displays an app preview; when I update the state, that panel was getting focused, removing focus from inputs.

I added ExcludeFocus to the preview tree and everything is working fine now.
