### ISSUE TITLE
fix: Generator Callbacks without yield or emit

### ISSUE THREAD

**Issue by codesculpture** [felangel/bloc#3731]
**Description**
on Event Callback at Bloc, there is a void callback which provided with event and emit. But if the callback is set to async generator (async* ) roughly if we emit state it not reflected since we are not yielded it. So as for newbies (like me) or interns that are mistakenly do this it is so hard to debug (there is no error or warning). I know its all about developer Mistake. But can we do something to Warn for which not yielded (i know its void) generator function? Just idk this is a valid bug or question.

**Screenshots**

![Screenshot (430)](https://user-images.githubusercontent.com/63452117/217574917-fad649c2-307e-48f7-814b-02a2f9480796.png)

**Comment by tenhobi** [comment]
It would be best if you corrected a lot of things in your example. First of all, you are not typing your arguments nor return value. As you probably don't even use strict linting, the IDE does not tell you that the inference of those things failed and is resolved as `dynamic`.

Aka the bare minimum to ensure inference safety is to use 

```yaml
# analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
``` 

And you should also research some linter rules Dart provides; for your case, https://dart-lang.github.io/linter/lints/always_declare_return_types.html would be handy. That enforces that you must declare that function return type as `void`, and if you try to do that with `async*`, it will warn you with a mistype. Of course, if you set `Stream<void>` as a return value of that function, it will not complain because it technically does not violate anything.

Your Bloc should look like

```dart
class TestBloc extends Bloc<TestEvent, TestState> {
  TestBloc() : super(TestInitial()) {
    on<TestEvent>(_handleEvent);
  }

  void _handleEvent(TestEvent event, Emitter<TestState> emit) {
    emit(TestInitial());
  }
}
```

If you do not want to invest in cherry-picking lints, use https://pub.dev/packages/lints, https://pub.dev/packages/flutter_lints, https://pub.dev/packages/very_good_analysis, or any other package that does it for you.

I also just posted one simple, small article that covers the basics of static analysis and linting in Flutter apps, so you can check it out or get inspired by our set of lints. https://www.netglade.cz/en/blog/fluter-apps-linter-dart-netglade_analysis

**Comment by codesculpture** [comment]
Okay, thanks a lot it would be enough. Yeah just it was a mistake that is done by developer.. we need to explicitly put void in handler.. that solves ok then i will close this issue.
