### ISSUE TITLE
Why Bloc need BuildContext?

### ISSUE THREAD

**Issue by anggaaryas** [felangel/bloc#3744]
**Description**

Why bloc  need  BuildContext? Although we can use manual dependency injection or using `injectable` library. Any cons if  we use without context? sorry if i ask in wrong place. but i hope the author can explain to me

**Comment by tenhobi** [comment]
Hey @anggaaryas, Bloc or Cubit don't need `BuildContext`. 

However `BlocBuilder`, `BlocListener`, `BlocConsumer`, etc. need a `BuildContext` because it uses [`provider`](https://pub.dev/packages/provider) under the hood. And provider works as a wrapper of `InheritedWidget`, which requires a `BuildContext`. Note that `BlocBuilder` is used to build a widget tree based on Bloc's states.

Dependency injection can be used if you, for example, set up creation functions singleton/factory in your DI for your Blocs. But mostly you benefit from creating Bloc using `BlocProvider` as close as the place where you use the bloc.
