### ISSUE TITLE
fix: ListFieldBloc don't trigger redraw after add an Item

### ISSUE THREAD

**Issue by fiurthorn** [felangel/bloc#3750]
**Description**
I have a `FormBloc` with a `ListFieldBloc` child to display a list of attachments. After added a new Child dynamicly i have to call
`setState` to get the new child displayed, or change the GUI size to trigger the update.

After the new child is displayed, the modfication and the deletion work as excepted.

```dart
final attachments = ListFieldBloc<AttachmentState, String>(name: "attachments");
final attachment = InputFieldBloc<FileAttachment, dynamic>(initialValue: value);
attachments.addFieldBloc(attachment);
```

```dart
ListView.builder(
    shrinkWrap: true,
    physics: const NeverScrollableScrollPhysics(),
    itemCount: formBloc.attachmentCount(),
    itemBuilder: attachmentItemBuilder(formBloc.attachments),
),
```

**Expected Behavior**
Update the State to trigger an update, after add children with `addFieldBloc`

**Comment by tenhobi** [comment]
Hi @fiurthorn, this is not a Bloc bug. However, what is `attachmentItemBuilder,` `formBloc,` etc.? And your issue is rather related to not using Keys, so flutter cannot recognize that you changed your data because the tree is the same. Take a look at https://www.youtube.com/watch?v=kn0EOS-ZiIc.

The standard flow is that you use BlocBuilder; inside that, you use ListView and use keys properly. I also don't know what `formBloc.attachmentCount()` should be, as you should use the state from BlocBuilder for that, not the bloc itself.

**Comment by fiurthorn** [comment]
Sorry about use the BUG flag, but theres no `question` type ;-).

![image](https://user-images.githubusercontent.com/13510039/220870862-653c9c9e-9f8b-459e-8e1f-0b6e6ec1f262.png)

I will try your solution, thank for it.
