### ISSUE TITLE
docs: Naming convention for bloc states and events

### ISSUE THREAD

**Issue by semin-park** [felangel/bloc#3770]
**Description**

Hi,

In the naming convention section of the [documentation](https://bloclibrary.dev/#/blocnamingconventions), it is recommended that events are named in past tense.

While this makes sense when the event is describing what happened to the UI, I feel that naming events in present tense makes more sense in most scenarios.

To elaborate, I think there are two possible perspectives for any given event. Assuming a simple counter application with a button that increments the counter, this shows how the button press event can be interpreted:

1. Event describes what happened to the UI. Then a class name like`class ButtonPressed` would make sense.
2. Event describes what bloc needs to do. In this case, `class CounterIncrement` would make more sense for the event name.

The current documentation for naming events suggest past tense, which corresponds to 1. But I think that 2 is a better way of naming events for the following reasons:

1. Bloc should only be responsible for business logic, and should be separate from the UI. Naming an event after what happened to the UI is leaking UI information to Bloc and should be discouraged.
2. Bloc can be thought of as a state machine, where each Event "triggers" a state transition that moves the bloc into a new state. Please note the present tense used in "triggers".
![image](https://user-images.githubusercontent.com/30904140/226091681-62786fa5-2214-4437-8e5f-55da7c9103d5.png)
As an example, for the diagram above, `login` and `logout` are present tense verbs and they sound much better than `loginButtonPressed` or `logoutButtonPressed`.
3. Conceptually, Bloc's event is equivalent to Cubit's method, and Cubit methods are already named in present tense (`void increment` for the counter [example](https://bloclibrary.dev/#/fluttercountertutorial?id=counter-cubit)). Naming Bloc events in present tense will remove this divergence between Bloc and Cubit.

But then real life intricacies crop up and there might be situations where we can't devise a clear name for a state transition (=event), and in this case, we could use `XxxButtonPressed` as a last resort. But even then, I think first trying to name the event as something that would fit in the pure state machine would still be better.

I'm curious what others think though. Please let me know any thoughts or comments. Thanks!

**Comment by tenhobi** [comment]
I disagree that Bloc events and Cubit methods are conceptually necessary equivalent.

But yea, your point makes sense to me. In talks about whether side effects are good/bad one point why not is the separation of Bloc and UI. And it's true that past sense like `CounterIncrementPressed` couples the Bloc with UI as well.

Yet I am not sure if an event should dictate a Bloc how it should process it. Because instead of Cubit, Bloc is conceptually designed to process events in different time differently, in my eyes.

**Comment by felangel** [comment]
Closing for now since there do not appear to be any actionable next steps. The naming conventions are a recommendation and you're encouraged to define your own conventions if you feel they aren't well suited for you and your team. Feel free to comment with any follow up questions/thoughts and I'm happy to continue the conversation 👍
