### ISSUE TITLE
[Proposal] Custom classes for `Cubit` scope

### ISSUE THREAD

**Issue by felipecastrosales** [felangel/bloc#3801]
I've been thinking about why there aren't custom classes for Cubit for a while now, as we have for Bloc. Just for naming pattern, e.g. 

An example that I see would make sense: 

```dart
1. BlocBuilder<CounterBloc, CounterState>(
2. BlocBuilder<CounterCubit, CounterState>(
```

See that in 1, it makes sense to have the prefix `Bloc` for the class because the main class has `Bloc` as suffix
But in 2, e.g, I see thaat it causes a little confusion, see that there is no directly relationship (which is directly perceived), in this reasoning that there is in 1.

What it could be - as I imagine - would be the possibility of `Cubit`s classes:

```dart
3. CubitBuilder<CounterCubit, CounterState>(
```

This applies to other classes as well, this is just an example. 

---

If there is already some explanation or guidance on this, we can clase the issue. But looking for references about it, I didn't find it. I think it would be interesting to have the possibility of flexible classes in the package, to follow the approach and "namings patterns".

**Comment by tenhobi** [comment]
While both Cubit and Bloc extends BlocBase, I feel like it's perfectly ok to have only one version of these functions/widgets like `BlocBuilder`.

We can probably do some typedefs or whatever but wouldn't it be even more confusing because now Cubits would work in both `BlocBuilder` and `CubitBuilder`? We could of course limit `BlocBuilder` to only work with blocs, but that's a breaking change and would limit users because now you can use Bloc and Cubit interchangeably.

**Comment by felipecastrosales** [comment]
Your explanation and counterargument was perfect. Thanks @tenhobi. I will be closing this issue.
