### ISSUE TITLE
bloc_test will always fail if state contains a list

### ISSUE THREAD

**Issue by danielRi** [felangel/bloc#3814]
**Description**

This may not be a bug, it´s maybe just support needed. Also I use bloc with `freezed` so let me know if it´s a `freezed` problem. I also use `Option` from `fpdart`, this seems to be the problem, but it also implements `==` and `hash`, so I dont know why it would fail. If I remove the list inside the Option, it also works. **The problem seems to be the combination of a `list` inside the `Some`(= Option) class**. 

I get the infamous error:

```
package:bloc_test/src/bloc_test.dart 236:9   testBloc.<fn>
===== asynchronous gap ===========================
dart:async                                   _CustomZone.registerUnaryCallback
package:bloc_test/src/bloc_test.dart 201:7   testBloc.<fn>
dart:async                                   runZonedGuarded
package:bloc_test/src/bloc_test.dart 199:9   testBloc
package:bloc_test/src/bloc_test.dart 156:13  blocTest.<fn>

Expected: [
            _$_Loaded:ElderGodsState.loaded(elderGodsVm: ElderGodsVm(godsList: Some([ElderGod(name: Shub Nigurath)])))
          ]
  Actual: [
            _$_Loaded:ElderGodsState.loaded(elderGodsVm: ElderGodsVm(godsList: Some([ElderGod(name: Shub Nigurath)])))
          ]
   Which: at location [0] is _$_Loaded:<ElderGodsState.loaded(elderGodsVm: ElderGodsVm(godsList: Some([ElderGod(name: Shub Nigurath)])))> instead of _$_Loaded:<ElderGodsState.loaded(elderGodsVm: ElderGodsVm(godsList: Some([ElderGod(name: Shub Nigurath)])))>

WARNING: Please ensure state instances extend Equatable, override == and hashCode, or implement Comparable.
Alternatively, consider using Matchers in the expect of the blocTest rather than concrete state instances.
```

**Steps To Reproduce**

I create some sample code to make the reproduction of the issue as simple as possible and to hide out noise that is not related to the issue.

This is my state:

```
@freezed
class ElderGodsState with _$ElderGodsState {
  const factory ElderGodsState.initial() = _Initial;

  const factory ElderGodsState.loaded({
    required ElderGodsVm elderGodsVm}
      ) = _Loaded;
}
```

Data objects:

```
@freezed
class ElderGodsVm with _$ElderGodsVm {
  const factory ElderGodsVm({
    required Some<List<ElderGod>> godsList, // <-- The Option I mentioned, if I remove the Some<>, it works, if I remove the list, it also works
  }) = _ElderGodsVm;
}

@freezed
class ElderGod with _$ElderGod {
  const factory ElderGod({
    required String name,
  }) = _ElderGod;
```

And my bloc which just emits a sample state:

```
class ElderGodsBloc extends Bloc<ElderGodsEvent, ElderGodsState> {
  ElderGodsBloc() : super(const ElderGodsState.initial()) {
    on<FetchList>((event, emit) {
      emit(
        ElderGodsState.loaded(
          elderGodsVm: ElderGodsVm(
            godsList: Some([ElderGod(name: "Shub Nigurath")]),
          ),
        ),
      );
    });
  }
}
```

And finally my unit test:
```
void main() {
  blocTest<ElderGodsBloc, ElderGodsState>("bla",
      build: () => ElderGodsBloc(),
      seed: () => const ElderGodsState.initial(),
      act: (bloc) => bloc.add(FetchList()),
      expect: () => [
            ElderGodsState.loaded(
                elderGodsVm: ElderGodsVm(
                    godsList: Some([ElderGod(name: "Shub Nigurath")])))
          ]);
}
```

**Expected Behavior**
The test succeeds, because all classes implement `==` and `hash` (also Some)

**Additional Context**
Next to `bloc_test`, I use `freezed` and `Option` from `fpdart`

**Comment by AlexanderFarkas** [comment]
Well, your code is incorrect. 
`[ElderGod(name: "Shub Nigurath")]` != `[ElderGod(name: "Shub Nigurath")]` if you `Some` doesn't use deep collection equality (I believe, it doesn't)

**Comment by danielRi** [comment]
I checked Some´s code, you are right. Thanks for pointing me in the right direction. Sorry for bothering you with stuff that is not your fault.

All the best,
Daniel

**Comment by dipu-polygontech** [comment]
0

I'm currently facing an issue with Flutter Bloc testing where I have a sequence of events: fetching items, then decrementing the item count. The problem is that the expected state after the decrement is not matching the actual state. It seems like the item count is being decremented from the initial state instead of the state after fetching the items.

When I call two events one after another, here I have called 'get items' then I have decremented the count of it. In my case, I am using a single state class using copyWith. Here, the state remains when not updating anything, but the decrement is working after getting data. After that, I am decrementing, but in the actual output, it shows the item count is decremented from the beginning.

Here's the relevant code snippet:

setUp: () {
  when(() => mockRepository.getCartItemList()).thenAnswer(
    (_) async => [
      ItemEntity(
        //--------
      ),
    ],
  );
  when(() => mockRepository.updateCartItem(any())).thenAnswer((_) async => true);
},

Expected: [
ItemState:ItemState(CallbackStatus.loading, null, 0.0),

        ItemState:ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 2}], 20.0),

        ItemState:ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 2}], 20.0),

        ItemState:ItemState(CallbackStatus.loading, [ItemEntity{id: 1, brandId: null, productName: Product 1, brandName: null, packingUnit: null, discountedPrice: 10.00, cartItemCount: 2}], 20.0),

        ItemState:ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 10.0)
      ]

Actual: [
ItemState:ItemState(CallbackStatus.loading, null, 0.0),

        ItemState:ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, productImage: null, productCategory: null, categoryId: null, cartItemCount: 1}], 20.0),
        ItemState:ItemState(CallbackStatus.initial, [ItemEntity{id: 1, brandId: null, productName: Product 1, brandName: null, packingUnit: null, sellingUnit: null, packSize: null, price: null, discountedPrice: 10.00, categoryId: null, cartItemCount: 1}], 20.0),
        ItemState:ItemState(CallbackStatus.loading, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 20.0),
        ItemState:ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 10.0)
      ]

Which: at location [1] is ItemState:<ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 20.0)> instead of ItemState:<ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 2}], 20.0)>

==== diff ========================================

[ItemState(CallbackStatus.loading, null, 0.0),
ItemState(CallbackStatus.success, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: [-2-]{+1+}}], 20.0),
ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: [-2-]{+1+}}], 20.0),
ItemState(CallbackStatus.loading, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: [-2-]{+1+}}], 20.0),
ItemState(CallbackStatus.initial, [ItemEntity{id: 1, productName: Product 1, discountedPrice: 10.00, cartItemCount: 1}], 10.0)]

==== end diff =================================================================
The issue is that the actual state after the second event shows the item count decremented from the initial state, but it should be from the state after fetching items.

I would appreciate any insights or suggestions on how to resolve this issue. Thanks in advance!
