### ISSUE TITLE
fix: when a add a field to  hydrated_bloc, the older persistence data will be lost , this is not good performance

### ISSUE THREAD

**Issue by bravekingzhang** [felangel/bloc#3818]
**Description**
when a add a field to  hydrated_bloc, the older persistence data will be lost , this is not good performance

**Steps To Reproduce**
 always

**Expected Behavior**
when add a new filed ,the older persistence data can still work.

**Screenshots**
do not need screenShot

**Additional Context**
nothing

**Comment by felangel** [comment]
Hi @bravekingzhang 👋 
Thanks for opening an issue!

You're in full control over this behavior because whatever you return from `toJson` is cached so you can include a version in the json and/or handle gracefully migrating to a new format whenever you change something. Hope that helps, if you're still stuck feel free to provide a link to a minimal reproduction sample and I'm happy to take a closer look and provide suggestions 👍
