### ISSUE TITLE
Importing barrels is whether redundant or not?

### ISSUE THREAD

**Issue by ThatPham2000** [felangel/bloc#3823]
**Description**

For many of your examples, you used importing barrels (it means you imported files containing export keywords inside).
A question here, I do not need to use all of components inside the barrels. It is redundant or not? And, does it affect application performance?

In the material package, they also exported to barrels so that many material apps can import it without other material components. I do not know any reasons why? Please let me know the reasons you choose this way.

Many thanks.

**Comment by felangel** [comment]
Hey 👋 

Barrels are a way to group related functionality so that you can import related public APIs with a single import. You can read a bit more about the benefits [here](https://basarat.gitbook.io/typescript/main-1/barrel). If you will not use all of the components then there's no reason to export them from the barrel.

Closing for now, hope that helps 👍
