### ISSUE TITLE
HydratedBloc.storage.clear() fails in official example

### ISSUE THREAD

**Issue by miguelangelflores1993** [felangel/bloc#3834]
I increase values, and decrease the same, up to there everything works excellent.

but when i run the delete data button HydratedBloc.storage.clear() doesn't get updated and does nothing.

I have to do a hot restart, or I have to go back or close the application and open it to load the reset state again.

It is critical for me because I use it for my official project as an offline shopping cart, addresses and payments. and the data is not cleared when the user finishes everything.

https://github.com/felangel/bloc/assets/116732288/5d5ffe67-bef3-4bab-bbcf-830f250b7543

**Comment by felangel** [comment]
Hi @miguelangelflores1993 👋 
Thanks for opening an issue!

This is working as expected because clearing the storage does not clear bloc state. Clearing the storage simply wipes out the data persisted on the device. If you would like to clear the bloc state then I recommend adding an event to the bloc and updating the state as you normally would. In general clearing the hydrated_storage should be used mainly for deleting cached data. Hope that helps!

**Comment by felangel** [comment]
Closing for now since this is working as expected. Feel free comment with any follow-up questions/thoughts and I'm happy to continue the conversation 👍
