### ISSUE TITLE
[Question] docs: question regarding the migration guide on bloclibrary.dev

### ISSUE THREAD

**Issue by MdeBruin93** [felangel/bloc#3851]
**Description**

Clearly describe what documentation you are looking to add or improve.

Just for clarification purposes: is the hydrated_bloc package the successor of the flutter_bloc package? Meaning developers should migrate to this new package? Or am I not understanding the migration guide correctly?

**Comment by felangel** [comment]
Hi @MdeBruin93 👋 
Thanks for opening an issue!

`hydrated_bloc` is not a successor of `flutter_bloc`. `hydrated_bloc` allows you to create blocs that persist and restore their states so that you can cache state across app launches -- you can use `hydrated_bloc` and `flutter_bloc` together. Hope that helps 👍
