### ISSUE TITLE
Question about handling error(s) in BLoC

### ISSUE THREAD

**Issue by dxGuan** [felangel/bloc#391]
While integrating bloc into my project, I found it's great to de-couple the presentation layer from business logic.

However, I am struggling of how can I handle some error(s) globally?

Let's say:

* I have a ```AuthPage``` which is dedicated to present all UI related components to  users for signing into the app.

* I have a ```AuthBloc``` which is dedicated to process all the business logic.

* I have a ```AuthRepo``` which is dedicated to fetch all the data asynchronously.

Here is my confusions:

#### Question 1:
* How can I handle the error which is thrown by the ```AuthRepo```?
  * Like network related error thrown by the gRPC client which is a part of my repo.

#### Question 2:
* To be more specifically, some error(s) are much more generalized and the others are highly related to a particular business component. How to separate them into different error handling logic in BLoC, because I think it will be a good catch to handle the former one in a global way and leaving the latter one to a business bloc.

#### Question 3:
* How to pass the global error to presentation layer and how to process it within in ```BlocListener``` because I just want to inform the user with some error message like a toast, a snackbar or a dialog, instead of rebuilding a widget.

**Comment by felangel** [comment]
Hi @dxGuan 👋 
Thanks for opening an issue!

Regarding your questions:
1. You should just wrap the gRPC client requests in a try/catch and transform the errors into meaningful errors in the repository. You can then yield different states in the bloc based on the repository error thrown.
2. All blocs are business logic components so the errors thrown should be specific to the bloc's responsibility/functionality. Can you provide an example of a generalized error vs a business logic error?
3. Like you said, you can just use BlocListener to listen for specific error states in the bloc and show a snackbar/dialog based on the error; BlocListener does not rebuild the widget.

Hope that helps! 👍

**Comment by dxGuan** [comment]
@felangel thx for your reply and I am clear about Question 1 while I still confuse about Q2 & 3:

Q2 & 3: If I wrap all gRPC client requests in try/catch and transform the errors into meaningful states, that's find and this is what you suggested in Q1. What I am confusing is, if some errors (like server unavailable, network unavailable, etc) which are not business related and transformed into specific error state. They should be handled globally and not in the BLoC from which is invoked. Otherwise, I had to deal with these non-biz error(s) in each BLoC(s) and each BlocListener in UI layer has to deal with these non-biz error state(s) by like showing a snackbar with an "ERROR MSG".

**Comment by felangel** [comment]
Hi @dxGuan no problem!

Your repository layer should not throw error bloc states. I would try to think of the different repositories as stand-alone packages that can be reused across different applications (as external dependencies). The repository can catch the `gRPC` client errors and throw errors like `NoNetwork`, `ServerUnavailable`, etc...

I would not recommend having a single `BlocListener` in the UI layer to deal with all of the repository errors because things like `SnackBars` etc are screen/context dependent. You need to have a Scaffold in the `BuildContext` in order to show a `SnackBar`. In addition, if you navigate away the `SnackBar` will not be persisted.

For something like global error handling, you might want to look into [overlays](https://api.flutter.dev/flutter/widgets/Overlay-class.html). You can have a `ConnectivityBloc` that listens to the network connectivity stream via a package like [connectivity](https://pub.dev/packages/connectivity) and yields different states depending on the connectivity of the device. Then you have manage showing/hiding an overlay globally using a `BlocListener` with the `ConnectivityBloc` at the root of your application.

Hope that helps and let me know if you have additional questions, thanks! 👍
