### ISSUE TITLE
feat:  Combine BlockProvider and BlockBuilder in a new WidgetBuilder

### ISSUE THREAD

**Issue by gigonzalezs** [felangel/bloc#3924]
**Description**

.I'm always frustrated when I need to create 2 widgets to use bloc: one for Provider and another one for BlockBuilder

**Desired Solution**

A new Widget that Combines BlockProvider and BlockBuilder in a new WidgetBuilder, receiving the block in constructor (useful for testing and mocking the bloc)

**Additional Context**

Proposed class:

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class BlocSelfProviderBuilder<B extends StateStreamableSource<S>, S> extends StatelessWidget {
  final B bloc;
  final BlocWidgetBuilder<S> builder;

  const BlocSelfProviderBuilder({
    super.key,
    required this.bloc,
    required this.builder
  });

  @override
  Widget build(BuildContext context) {
    return BlocProvider<B>(
        create: (_) => bloc,
        child: _BlocSelfProviderBuilderContent<B, S>(
            builder: builder
        )
    );
  }
}

class _BlocSelfProviderBuilderContent<B extends StateStreamableSource<S>, S> extends StatelessWidget {
  final BlocWidgetBuilder<S> builder;

  const _BlocSelfProviderBuilderContent({super.key, required this.builder});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<B, S>(
      builder: builder
    );
  }
}

**Comment by felangel** [comment]
Hi @gigonzalezs 👋 
Thanks for opening an issue I'm not sure I understand the problem. Most of the code you provided is crossed out so it's unclear what the problem and desired solution is. As this issue is quite old I'm going to close it since at the moment there is no actionable steps that I can take. If this is still an issue feel free to provide more context and I'm happy to continue the conversation, thanks!
