### ISSUE TITLE
Question: test bloc constructors body with bloc_test ?

### ISSUE THREAD

**Issue by thomasnti** [felangel/bloc#3944]
Hello, I am trying to figure out how to test the body of a constructor. Here is an example :

``` 
class MeetingsBloc extends Bloc<MeetingsEvent, MeetingsState> {
  final Mediator _mediator;
  MeetingsBloc(
    this._mediator,
  ) : super(const MeetingsState([])) {
    _registerEvents();
    add(LoadMeetingsEvent());
  }
}
```

How to test that the LoadMeetingsEvent is added when a new instance of MeetingsBloc is created ?

**Comment by felangel** [comment]
Hi @thomasnti 👋 
Thanks for opening an issue!

I highly recommend avoiding adding events in the bloc's constructor for this exact reason and instead add the events when the bloc is provided:

```dart
BlocProvider(
  create: (context) => MeetingsBloc()..add(LoadMettingsEvent()),
  child: MyWidget(),
);
```

This gives you granular control over when the event is added and makes testing easier and more predictable. In addition, it also makes the bloc more flexible and reusable.

Hope that helps 👍

**Comment by JohnWeidner** [comment]
@felangel In your example, it looks like "LoadMettingsEvent" is not named to describe something that has happened, but instead is named to indicate what you want the bloc to do.  To me this seems to go against the bloc naming convention of [naming events in the past tense because events are things that have already occurred from the bloc's perspective.](https://bloclibrary.dev/naming-conventions/#event-conventions)

I've seen code where after a bloc is created, several events get added to get the bloc to listen to different streams. These events aren't named to describe what has happened, but instead are named to indicate what they need the bloc to do. Instead of doing that, I've proposed the following pattern. This keeps the responsibility of determining what should be done to initialize the bloc with the bloc. What are your thoughts?

----- my_bloc_event.dart ------------------

```
enum BlocCreationSteps { subscribeToStream1, subscribeToStream2 }

class BlocCreated  {
  const BlocCreated({
   @visibleForTesting
    this.steps = const [
      BlocCreationSteps.subscribeToStream1,
      BlocCreationSteps.subscribeToStream2,
    ],
  });
  final List<BlocCreationSteps> steps;
  @override
  List<Object?> get props => [steps];
}
```
----- my_bloc.dart ----------------------

```
  Future<void> _onBlocCreated(
    BlocCreated event,
    Emitter<MyBlocState> emit,
  ) async {
    await Future.wait([
      if (event.steps.contains(BlocCreationSteps.subscribeToStream1))
        _subscribeToStream1(emit),
      if (event.steps.contains(Head2HeadCreationSteps.processRaceFlagStream))
        _subscribeToStream2(emit),
    ]);
  }
```
---- my_bloc_test.dart ----------------
```
        act:
          (bloc) => bloc.add(
            const BlocCreated(
              steps: [BlocCreationSteps.subscribeToStream1],
            ),
          ),
```
