### ISSUE TITLE
fix: Logout issue with firebase when using flutter_bloc

### ISSUE THREAD

**Issue by alisabry22** [felangel/bloc#3945]
**Description**

Hello All,
i have an issue in my app which is a big app with different blocs and each bloc can have different streams from firebase firestore but once i try to logout my app craches i know this is because somehow my blocs still listens from firestore but i don't know how can i properly close these listeners before logout when iam emitting streams with (await emit.forEach()) .

**Expected Behavior**
iam expecting to close all attached listeners before logout to prevent these crashes while iam having the rules for firestore is (if request.auth!=null).

* remember that i have more than 7 streams in different blocs.whether to change my way for emitting states or using stream subscription and how please.

**Screenshots**

![streams](https://github.com/felangel/bloc/assets/52348575/e639e2fb-e725-4c09-869e-3956a0bfeab5)

**Comment by felangel** [comment]
Hi @alisabry22 👋 
Thanks for opening an issue!

I suspect the issue stems from the fact that your blocs are provided too high up in the widget tree and are never disposed. Generally I recommend scoping your blocs as low as possible in the widget tree to avoid such issues because when the user logs out, the BlocProviders should be unmounted and the corresponding blocs should be automatically disposed.

Hope that helps 👍 

Closing for now but if you have additional comments/questions feel free to reply and I'm happy to continue the conversation!
