### ISSUE TITLE
[Proposal] Allow for multiple bloc's in BlocBuilder

### ISSUE THREAD

**Issue by toiletspider** [felangel/bloc#396]
**Proposal**
Allow for multiple blocs in BlocBuilder. 

**Example:**
```
    BlocBuilder(
        bloc: MergeBloc.combine2(livestockBloc, dataBloc),
        builder: (context, MergedState state) {
          LivestockState livestockState = state.mergedStates[0];
          DataState dataState = state.mergedStates[1];
          ...
```

With #108 it was recommended that we use nested BlocBuilder's.  Although nested blocs will work, refactoring can become ugly.  It was also recommended  that "you can have a new bloc which composes the states from the two blocs into a new state". My problem with the last statement is that by having blocs in blocs that this causes unnecessary complexity and also binds bloc's together. I would rather have separated blocs with a single responsibility (eg. ApiBloc, AuthBloc, MainPageBloc ...).

The code I have attached here is my current solution to provide the functionality, it is a bit nasty in it's current form because it is not part of the BlocBuilder. 

I would like extend the BlocBuilder to allow it to take 2 or more blocs.  Thoughts on this?

```
import 'package:bloc/bloc.dart';
import 'package:rxdart/rxdart.dart';

class MergedEvent {
  List<Object> mergedStates;
  MergedEvent(this.mergedStates);
}

class MergedState {
  List<Object> mergedStates;
  MergedState(this.mergedStates);
}

class MergeBloc extends Bloc<MergedEvent, MergedState> {
  @override
  MergedState get initialState => MergedState([]);

  MergeBloc.combine2(Bloc bloc1, Bloc bloc2) {
    Observable.combineLatest2(bloc1.state, bloc2.state, (b1, b2) => [b1, b2])
        .listen((states) => this.dispatch(MergedEvent(states)));
  }

  MergeBloc.combine3(Bloc bloc1, Bloc bloc2, Bloc bloc3) {
    Observable.combineLatest3(
            bloc1.state, bloc2.state, bloc3.state, (b1, b2, b3) => [b1, b2, b3])
        .listen((states) => this.dispatch(MergedEvent(states)));
  }

  MergeBloc.combine4(Bloc bloc1, Bloc bloc2, Bloc bloc3, Bloc bloc4) {
    Observable.combineLatest4(bloc1.state, bloc2.state, bloc3.state,
            bloc4.state, (b1, b2, b3, b4) => [b1, b2, b3, b4])
        .listen((states) => this.dispatch(MergedEvent(states)));
  }

  @override
  Stream<MergedState> mapEventToState(
      MergedState currentState, MergedEvent event) async* {
    yield MergedState(event.mergedStates);
  }
}

```

**Comment by felangel** [comment]
Hey @toiletspider 👋 
Thanks for opening an issue!

Can you please provide a concrete example of when you would need this functionality? Usually a bloc should drive a single feature and if you find yourself merging blocs like this, it might be a sign that you are either putting BlocBuilder too high in your widget tree or your blocs aren't split up optimally.

Thanks!

**Comment by toiletspider** [comment]
@felangel sure :-)

We currently have global Blocs, and a bloc per page.
**Global**:
AuthBloc: Logging and store user data it's state.
ApiBloc: All api request are done here and stored in it's state, it is to prevent multiple calls been made for the same data from different places.

**Page**:
HomePageBloc
... every page has it's own bloc to manage it's state. 

Example would be the HomePage, it requires the ApiBloc to get the feed for the user, the AuthBloc to show the users avatar and the HomePageBloc which stores the page current state and handles the page events. This would require multiple blocs for this 1 page.

I prefer to have a single point of entry (BlocBuilder) for my state. This makes the presentation layer simple because all widgets are simply giving immutable data to display. In short, no stream/future builders in the pres layer and all data that are to be be displayed are from a single entry point.

> a bloc should drive a single feature

I agree with this, and this is what I set out to accomplish, but could be wrong in the way I approached it.

**Comment by felangel** [comment]
@toiletspider thanks for the additional details!

The global `AuthBloc` makes sense to me 👍 
The `ApiBloc`, however, seems like it's doing too much. I would recommend having a bloc per feature and not per API. You can create different API clients (to make the api requests) and inject them into the repositories that need them (check out the [bloc architecture](https://felangel.github.io/bloc/#/architecture?id=repository) docs for more details). Then you can have a bloc per feature and add the required repositories as dependencies to the feature blocs.

Instead of having to use the `ApiBloc`, `AuthBloc`, and `HomePageBloc` just to render the HomePage, I would recommend refactoring so just the `HomeBloc` is necessary.

You can check out the [bloc to bloc communication](https://felangel.github.io/bloc/#/architecture?id=bloc-to-bloc-communication) section for an example of how to have blocs depend on other blocs which should further reduce the need to have nested `BlocBuilders`.

I am also planning on releasing a series of architecture articles and updates that will focus on explaining the recommended architecture when using the bloc library and it should address some of the topics brought up here.

Let me know if that helps and I'm more than happy to move this conversation to [gitter](https://gitter.im/bloc_package/Lobby) if you'd like. 👍

**Comment by toiletspider** [comment]
@felangel thank you, that did help.

The reason for `ApiBloc` is because of Firebase and to prevent code duplication. I have a service layer where I wrapped the FireBase in. Since it returns a Streams, it is listened to in the `ApiBloc` and creates events from it. I'm currently using get_it (IoC container), I could create a Singleton which contains the different Streams and have each bloc that depends on that data subscribe to it and cancel when it is done. The reason I did not go this route was because of code duplication, multiple pages sometimes require the same data. Have all of the api data in 1 state made sense.

I have done the bloc in a bloc injection, but like I said this caused a dependency of a bloc on another. One scenario that I see if A depends -> B and B -> C. What happens when Bloc B is no longer needed or moved, or when another bloc D also depends on B, the complexity increases exponentially. I have worked on similar systems that a service depends on another service, everything is fine when you start, but scaling becomes very difficult.

I agree that bloc per feature is the correct approach, but from what I can see the bloc in a bloc goes against this.

I look forward to your architecture articles to see how to handle these types of scenario's.

**Comment by felangel** [comment]
Hey @toiletspider I don't think there should be any issue with blocs depending on other blocs where it makes sense. You can checkout the [todos example](https://github.com/felangel/bloc/tree/master/examples/flutter_todos) as the FilteredTodosBloc and StatsBloc have a dependency on the TodosBloc and react to changes accordingly.

This allows us to have a single bloc with a single BlocBuilder for the relevant features. If in the future your requirements change, then you can simply remove the dependency and it should not be a significant refactor because you can use BlocProvider to provide the blocs.

Closing for now but feel free to comment with additional questions and I'm more than happy to continue the conversation 👍
