### ISSUE TITLE
question: Immutable concept counterintuitive?

### ISSUE THREAD

**Issue by JimPanse2k19** [felangel/bloc#3982]
I am quite new to flutter/dart. From other programming languages i am used to simply modify the "payload" objects, since there was no need to for thread safety etc ... 

I understand the advantages of immutability and it absolutely makes sense for states. But I am now at a point where my states are getting more and more complex and advanced. It includes for example lists  that holds several hundreds objects. These objects also holding properties/links to other objects etc. 

When having everything immutable with the final keyword, it seems to me very complicated to change single aspects of the states.

The more objects a state includes, the more performance issues seems to be present.

At all it feels very counterintuitive to apply a "final" concept for something that changes actually every time.

Also to change just some properties that changes often from final to non-final also seems to me also more hacky than clean. 

My question: Do i miss something here from the key concept? Are there any "helper" that makes at least the code more clean? At the moment it feels like the code is bloating with functions that is just for assembling/disassembling objects.
What are your experiences with this? Any tipps?

**Comment by felangel** [comment]
Hi @JimPanse2k19 👋 
Thanks for opening an issue!

If you have cases where immutable states are not desirable such as extremely long lists with complex objects you can opt out of this by overriding `==` on your state and having it always evaluate to distinct. The only thing blocs check is that when you emit a new state, that the newly emitted state does not equal the current state. Since you're in full control over the implementation of the state you should be able to do something like:

```dart
import 'package:bloc/bloc.dart';

mixin Distinct on Object {
  @override
  bool operator ==(Object other) => false;
}

class MyState with Distinct {
  MyState({required this.list});
  final List<int> list;

  @override
  String toString() {
    return '{list: ${list}}';
  }
}

class MyCubit extends Cubit<MyState> {
  MyCubit() : super(MyState(list: []));

  @override
  void onChange(Change<MyState> change) {
    super.onChange(change);
    print('onChange: $change');
  }

  void addValue(int value) {
    state.list.add(value);
    emit(state);
  }
}

void main() {
  final cubit = MyCubit();
  for (var i = 0; i < 10; i++) {
    cubit.addValue(i);
  }
}
```

Notice how in this example, I'm directly mutating the list in the state and the cubit still emits the new states. Hope this sheds some light on how you can opt out of immutability if you really need to. It might also be worthwhile asking whether the bloc should be managing a really long list of complex states as well and whether that can be restructured/simplified.

Hope that helps! Closing for now but feel free to comment with any follow up questions/thoughts and I'm happy to continue the conversation 👍

**Comment by JimPanse2k19** [comment]
Hello,
thanks for your answer. I'll give it a try in next iteration and see how it works :). 

For the second suggestion: Yes, i also wondering if my bloc, respectively the state, should be used in that way i do. In my scenario, i try to manage a table view, where every single row can be edited. So there is a need for different states like "inEditMode" for every column and every row ... or "rowIsSelected" or "orderedBy" etc ... also they can have grouped child elements which are attached to any of the data rows, they can be also selected, sorted etc. 

So i don't see how to simplify this at the moment ... in the end, also its not 100% clear to me, if my bloc just "model" the frontend elements and its states or if there should be more or other than this. The states of my bloc evolved over time to be now a nearly 1:1 representation of everything that i can see and use on the certain screen, which actually won't involve any "business logic" as the "bloc" name suggests. Its more or less a "state changer" of the UI.  Its just something like "DataTable dataTable" with for example a "List<DataTableRow> rows" in it. The real business logic for the data happens inside use cases in my case.

**Comment by alexkmbk** [comment]
> ```dart
>   final List<int> list;
> ```
Thanks for your answer! But why do we need to make the list final and the whole state class immutable?
