### ISSUE TITLE
BlocListener no longer observes first state 

### ISSUE THREAD

**Issue by dustin-graham** [felangel/bloc#404]
**Describe the bug**
#370 packages/flutter_bloc/lib/src/bloc_listener.dart line adds a `skip(1)` operator to the bloc listener. The commit indicates this is intentional so as to only respond to state _updates_. This ended up breaking one of my widget tests where I mock the provided bloc to provide the state update my app needs to react to as the first event in its stream. To fix my test I had to add an arbitrary "1st" event which works, but seems a bit contrived. It seems to me that the first state should count as a state change as the stream changes from no events to one event. 

Given #370, this appears to be new expected behavior. However, based on #213, observing the first event was previously intended. Is there a reason why the first state needs to be skipped by the bloc observer?

**Expected behavior**
The BlocListener observes the first state

**Comment by basketball-ico** [comment]
@dustin-graham Hi
Please check this https://github.com/felangel/bloc/issues/368

**Comment by dustin-graham** [comment]
I just found #368. I get the case where you are trying to only call this function when state changes and the situation we avoid by the skip is confusing the consequence of the listener subscription with actual state updates. 

Could we perhaps use BehaviorSubject's hasValue function to determine if we should drop the initial event?

**Comment by dustin-graham** [comment]
I think there should be a way to keep the fix made in #368 and still include the very first state.

**Comment by felangel** [comment]
Hey @dustin-graham 👋 
Thanks for opening an issue!

Regarding your request, by definition BlocListener should be called once for each state change and I don't think the initialState is considered a state change since the bloc defines it's own initialState.

As a result, I think it's unnecessary to have BlocListener be triggered on initialState and it also introduces lots of undesired behavior such as being re-triggered on initialization of widgets even though no state has occurred (as described in #368).

Using the BehaviorSubject's `hasValue` is also not viable because the BehaviorSubject is seeded with `initialState` so `hasValue` will always evaluate to true.

I would love to hear more about why you think this is necessary because instead of

```dart
BlocListener(
  bloc: myBloc,
  listener: (context, state) {
    if (state is InitialState) {
      doStuff();
    }
  },
  child: MyChild(),
)
```

you can just do:

```dart
BlocProvider(
  builder: (context) {
    final myBloc = MyBloc();
    doStuff();
    return myBloc;
  },
  child: MyChild(),
)
```

Let me know if that helps 👍

**Comment by dustin-graham** [comment]
@felangel , I appreciate the response. I gave this some thought and I think this all makes sense to me now. I appreciate the explanation.

**Comment by danielborges93** [comment]
The BlocListener is not listening the first state change.

My states:
```dart
enum DisplayOptionsState { waiting, success, failure }
```

My initial state is:
```dart
@override
DisplayOptionsState get initialState => DisplayOptionsState.waiting;
```

My `mapEventToState`:
```dart
  @override
  Stream<DisplayOptionsState> mapEventToState(SetDisplayTypeEvent event) async* {
    try {
      await api.setDisplayState(event.type);
      yield DisplayOptionsState.success;
    } catch (e) {
      yield DisplayOptionsState.failure;
    }
    yield DisplayOptionsState.waiting;
  }
```

My listener function:
```dart
      listener: (context, state) {
        switch (state) {
          case DisplayOptionsState.success:
            _scaffoldKey.currentState.showSnackBar(SnackBar(
              content: Text('Success'),
            ));
            break;
          case DisplayOptionsState.failure:
            _scaffoldKey.currentState.showSnackBar(SnackBar(
              content: Text('Error!'),
              backgroundColor: Colors.red,
            ));
            break;
          default:
            break;
        }
      },
```

The idea is after a api call, show a snackBar with success or error message. When I dispatch events two times, the listener responds only to the second. Is this the correct behavior?

**Comment by felangel** [comment]
Hey @danielborges93 👋 

Can you provide a link to a sample app that illustrates the problem you're having? Alternatively, have you checked out the [SnackBar Recipe](https://felangel.github.io/bloc/#/recipesfluttershowsnackbar)?

`BlocListener` should be triggered once for each state change 👍

**Comment by danielborges93** [comment]
Hi @felangel! Thanks for your response!

I have checked the SnackBar Recipe before ;-)
I tried your `mapEventToState` change suggestion, but the behavior was the same.

The app that I am developping is https://gitlab.com/openlp/openlp-mobile-remote (**branch api_base**). The widget and bloc are in `lib/src/widgets/display_options_dialog.dart` and `lib/src/bloc/display_options_dialog_bloc.dart`.

**Comment by otto-dev** [comment]
So is [the solution](https://github.com/felangel/bloc/issues/404#issuecomment-511093263) really to put the business logic for the initial state in the `BlocBuilder` rather than the `BlocListener`? I was considering that, felt it was a hack, googled, and came here.

**Comment by otto-dev** [comment]
I just ended up here again via google. As I understand now, the issue is actually more general.

The issue is that the `listener` is not called with the state of the `Bloc` when the `BlocListener` is created - no matter if that's the initial state, or a subsequent state. So then you have to refactor out the listener logic and work around it with a StatefulWidget.

**Comment by DIRRHUB** [comment]
> > The issue arises when you've already fetched all your Bloc data from another service, and you wish to listen for it in another component.
> > ### Example
> > 
> > * **Route A**: Initializes user data fetch. Once fetched, it redirects to **Route B**.
> > * **Route B**: Listens to that Bloc and displays a "hello user" snackbar.
> > 
> > This scenario is just one use case; there could be others. I believe introducing a `listenFirst` flag could be a good idea to trigger at Bloc listener initialization. This flag would help in managing the flow of data between components more efficiently, especially in scenarios where the data is fetched before the component starts listening to the Bloc as the state does not change.
> 
> The only workaround I've found is to use `Future.delayed(Duration.zero, () { showUserDialog(); })`, at the top of the builder of BlocConsumer but I don't find this to be very clean. It would have been better to place it in the listener, in my opinion.

We can use WidgetsBinding.instance.addPostFrameCallback in the initState and call an event there.

**Comment by takenoto** [comment]
I know this is an old thread, but a flag such as `listenFirst ` as suggested by @valas69 would be very nice.

I have a bunch of stateful widgets that are just wrappers around BlocListener because I need to do something everytime the condition is met, even if it is the first state.

Example of application:
- I want to show a dialog if the user profile permission status is "pending" (it has {`pending, rejected and approved`} states)
- This needs to check at initialization because, it the user is rejected, I want to show a modal telling them the reason
- This also needs to be checked everytime a user is updated because he may have become "rejected" by the system
- This is NOT a global listener, means it only does this check inside one screen.

There are plenty of cases like this in the app I'm working on right now. 

* I understand the ones that think "the initial state doesn't count anyway" but then my only option would be to make all of them top level listeners and many of them are (and actually need to be) nested inside some screens.

---
Example:


```dart
enum UserPermissionStatus{ approved, rejected, pending}

class UserPermissionsListener extends StatelessWidget{
  const UserPermissionsListener({required this.child});
  final Widget child;

  @override
  Widget build(BuildContext context){

 return BlocListener<UserSessionCubit, UserSessionState>(
      listenOnCreation: true
      listenWhen: (previous, current) => previous.state.userPermissions != current.state.userPermissions,
      listener: (BuildContext context, UserSessionState state) {
        showDialogAboutUserPermissions();
        },
        child:child
    );
  }
}
```

This way I could listen to user permission changes and display something related only inside the profile page, for example, and allowing the other pages to not care about it instead of having to declare the listener at the top of my app so it could see the change from initialState to the first loaded state.

Note that in my example I named the option `listenOnCreation` instead of `listenFirst` but the idea remains the same.
