### ISSUE TITLE
Help:add a event but state not change

### ISSUE THREAD

**Issue by caibimiaokong** [felangel/bloc#4045]
I asked a question on Discord, but the pictures tend to be cluttered together, which is not good for  present question.

The first case, I set the mapbloc's default state to init state,I add [LocationRequested ](https://github.com/caibimiaokong/test2/blob/5d1f032576f99c8d0466f8d79fdf4745e476aa64/lib/bloc/location_bloc.dart#L17)event  to [MapBloc  ](https://github.com/caibimiaokong/test2/blob/5d1f032576f99c8d0466f8d79fdf4745e476aa64/lib/bloc/location_bloc.dart#L11)when I provier it  to [widget tree](https://github.com/caibimiaokong/test2/blob/5d1f032576f99c8d0466f8d79fdf4745e476aa64/lib/main.dart#L45), state not change ,it logs like this:
![image](https://github.com/felangel/bloc/assets/90626136/fffc71e8-765d-481f-b764-cc5cb1febe0a)
![image](https://github.com/felangel/bloc/assets/90626136/47523474-8311-4a1e-8232-36fef414f9f1)

the second case , I provider a [user-location button](https://github.com/caibimiaokong/test2/blob/5d1f032576f99c8d0466f8d79fdf4745e476aa64/lib/main.dart#L126) in MapUI  but Use the same event as above,when I tap it . state still not change ,the log like this:
![image](https://github.com/felangel/bloc/assets/90626136/bc13a63e-d980-405f-9f0a-8ffb7cbfe344)

code is [here](https://github.com/caibimiaokong/test2/tree/main)
😕

**Comment by codesculpture** [comment]
There seems some error occuring thats what preventing the state to be updated, 
`determineLocation` is where the error occuring, you can comment that and pass with dummy lat and lang to `state` and u can make sure.

**Comment by elianortega** [comment]
Hello @caibimiaokong, from a quick overview on what you mentioned I can point out 2 things:

1. When adding the event to the `Bloc` prefer using `context.read` so in [here](https://github.com/caibimiaokong/test2/blob/5d1f032576f99c8d0466f8d79fdf4745e476aa64/lib/main.dart#L131) you should do:
```dart
 context.read<MapBloc>().add(LocationRequested());
```

2. When mapping the event to the function [here](https://github.com/caibimiaokong/test2/blob/5d1f032576f99c8d0466f8d79fdf4745e476aa64/lib/bloc/location_bloc.dart#L18) the function is not called as it is missing the parenthesis at the end `_onLocationRequested();`. Also you should fix the callback function to receive the event and the emitter just as you do for `_onChangeMapType`.

Finally, I highly recommend on checking the documentation on getting started at https://bloclibrary.dev so that you get all the best practices correct.

**Comment by felangel** [comment]
Closing for now since there aren't any actionable next steps. If you're still stuck feel free to reach out on [discord](https://discord.gg/bloc).
