### ISSUE TITLE
question: [flutter_todos] why don't close StreamController? 

### ISSUE THREAD

**Issue by manuelperez96** [felangel/bloc#4154]
**Description**

Hi, I'm learning about bloc-to-bloc communication through domain layer using streams. I was looking the example flutter_todos and I realised that local_storage_todos_api use an StreamController, but this is never closed.

This is not a bad practice? Is there some motive to not close this Stream Controller?

Thank you.

**Comment by felangel** [comment]
Hi @manuelperez96 👋 
Thanks for opening an issue!

In this case, the lifecycle of the `LocalStorageTodosApi` is tied to the application (e.g. the `LocalStorageTodosApi` is active the entire time the application is running) so it's okay that the underlying controller isn't closed. I opened #4157 to add a `close` API to the `TodosApi` in order to encourage cleaning up internal resources in general since in some cases the `TodosApi` might be created/destroyed multiple times throughout the lifetime of the app.

Hope that clears things up and thanks for raising this issue! 👍
