### ISSUE TITLE
Blocprovider child is not returning the childs

### ISSUE THREAD

**Issue by rajeshjeshar** [felangel/bloc#419]
Everything was working fine until i update to the following versions
```
bloc: ^0.14.4
flutter_bloc: ^0.19.1
```
Warning:
This function has a return type of 'Widget', but doesn't end with a return statement.
Try adding a return statement, or changing the return type to 'void'.dart(missing_return)
![Untitled-1 copy](https://user-images.githubusercontent.com/39165538/61516903-9ca2c100-aa23-11e9-8aeb-21addb33966e.jpg)

Examples are not updated to know how to figure out!

**Comment by felangel** [comment]
Hi @rajeshjeshar 👋 
Thanks for opening an issue!

I believe you're seeing this because you've likely upgraded flutter which has more strict analyzer rules. In general, all build methods must return a widget but before you did not get a warning if you returned null.

In any case, you need to make sure you have a fallback if the state is for some reason not `OtpSentState`, `AuthTimeOutState`, `AuthErrorState`, or `ExceptionState`.

You can either structure your code like:

```dart
if (state is OtpState) {
  return ...
} else if (state is AuthTimeOutState) {
  return ...
} else {
   // assume error if no other states are matched
  return ErrorPage(...)
}
```

or you can just have a return at the bottom like so:
```dart
if (state is OtpState) {
  return ...
}
if (state is AuthTimeOutState) {
  return ...
} 
// assume error if no other states are matched
return ErrorPage(...)
```

Hope that helps 👍
