### ISSUE TITLE
[help] Best Practice for Sharing Events and States Across Multiple Blocs, Bloc to Bloc communications

### ISSUE THREAD

**Issue by dipu0** [felangel/bloc#4196]
Hi,

I'm working on a Flutter project using the Bloc pattern to manage the state for multiple screens. Each screen has its bloc: suppose BlocA, BlocB, and BlocC. Each of these blocs performs API calls and data manipulation.

I have encountered a challenge where I need to handle a similar event across all three blocs. Here's a detailed description of the scenarios:

Scenario 1: When I navigate from ScreenA to ScreenB, I can pass data using an event, so I don't need to re-write the same logic in both blocs.
Scenario 2: When I'm already on ScreenB and the data changes (triggered by an event in BlocA, BlocB, or any), I need to update BlocB's state. This means I might duplicate the same event-handling code in multiple blocs.
Issues
Code Duplication: Duplicating event handling code in all three blocs.
State Synchronization: When data changes in one bloc (e.g., BlocA), I need to propagate this change to another bloc (e.g., BlocB).
To give a specific example: I need profile info in multiple places, and the profile can be updated from multiple places as well. Each time I need profile info, I create an event in the corresponding screen bloc. Is there any way I can call another screen bloc from one bloc, get the result, and pass the data in the state according to my needs?

Request
Could you please provide guidance or best practices for:

Sharing events and handling them across multiple blocs without duplicating code.
Keeping states in sync across different blocs when a shared event occurs.
Is there a pattern or approach within the Flutter bloc package that I can leverage to handle this more efficiently?

Thank you for your help!

**Comment by FarisArmoush** [comment]
There is no need to duplicate code, since in your module every bloc is responsible for one screen, but the data on any screen can be mutated by a different bloc, then every bloc is a source of truth of a specific piece of data, so you can update the data of a BlocA in ScreenB or any of your scenarios. For instance, BlocA's state has a String name, BlocB's state has a String email, and BlocC's state has a String imagePath, if ScreenB updates the name that exists in BlocA and ScreenA, update the name from the widget itself, by doing so you eliminate coupling the blocs with each other, and you have one singular source of truth for every piece of data. I hope I answered your question.

**Comment by dipu0** [comment]
> There is no need to duplicate code, since in your module every bloc is responsible for one screen, but the data on any screen can be mutated by a different bloc, then every bloc is a source of truth of a specific piece of data, so you can update the data of a BlocA in ScreenB or any of your scenarios. For instance, BlocA's state has a String name, BlocB's state has a String email, and BlocC's state has a String imagePath, if ScreenB updates the name that exists in BlocA and ScreenA, update the name from the widget itself, by doing so you eliminate coupling the blocs with each other, and you have one singular source of truth for every piece of data. I hope I answered your question.

Every screen has its bloc and state I need Bloc A name which might update or not, but I need that to show all names, emails, and photo, all this info came from the same API, in screen B name, email, photo showing from blocB 's state. 

I am not getting your point, can you provide more details so that I can understand, it will be a great help for me, 

thank you for replying!

**Comment by FarisArmoush** [comment]
I've worked on a feature once to create a real estate advertisement, and there were a lot of data in that 7 steps form, many of which were connected and changing based on other pieces of data, my solution was that i created a bloc for each step, each bloc handles one step, and if something is supposed to change in ScreenB because of data that changed in ScreenA / BlocA, i would update BlocB in ScreenA , what i mean by that is BlocA and BlocB, know nothing about each other, they don't communicate with one another. I truly believe communication between two blocs in the bloc class is a huge mistake, by doing so you would introduce coupling between them, which would lead to a missy situation.

To explain the source of truth concept even further, let me walk you through a situation, lets say you have a book on a table in front of you, and you know its a book because you've looked at it, you've touched it, and you've maybe read something from it, but another person walks into the room and says this isn't a book, and you're 100% sure that this object in front of you is a book, who would you believe? surely your own eyes. I've used this example to explain further why you shouldn't duplicate state/bloc code, you wouldn't be 100% sure which bloc/state to trust to have the correct piece of data, and it is also much messier.

I hope I answered your question, let me know if there was anything unclear.

**Comment by dipu0** [comment]
I'm trying to understand how to properly communicate between Blocs according to the Bloc documentation. If I have 20 components on my screen, do I need to create a separate Bloc for each one?

In my case, I need to change data within a Bloc. For example, if a button should be hidden or shown based on the user's status, but I'm on a product details page and don't have the profile details, how should I handle this? Should I call an API from the product details page, or should I somehow pass the profile information to that screen?, cant use profile details blocbuilder because that btn already listening from product details page also,

i think i am not able to describe my point, sorry for that :)

**Comment by dipu0** [comment]
Builder(
  builder: (context) {
    final stateA = context.watch<BlocA>().state;
    final stateB = context.watch<BlocB>().state;
    final stateC = context.watch<BlocC>().state;

    // return a Widget which depends on the state of BlocA, BlocB, and BlocC
  }
);

or 

Widget build(BuildContext context) {
  final name = context.select((ProfileBloc bloc) => bloc.state.name);
  return Text(name);
}


does this

**Comment by jttuboi** [comment]
> In my case, I need to change data within a Bloc. For example, if a button should be hidden or shown based on the user's status, but I'm on a product details page and don't have the profile details, how should I handle this? Should I call an API from the product details page, or should I somehow pass the profile information to that screen?, cant use profile details blocbuilder because that btn already listening from product details page also,

Hum, If I understand your problem, I had similar problem and I remember to solve this way (I don't use anymore, look at the end why). I can shared my experience, maybe you can have some ideas based on this code.
First you need know when you are authenticated in an app, you need a user or profile at the moment of all "login state". Usually people only store a boolean if it's logged or not, but you can store on `AuthenticationCubit` or `AuthenticationBloc` to represent the "login state". 

Example:
```dart
class AuthenticationCubit ... {
   ...
   Profile get profile => state.profileLogged;
   bool get isLogged => profileLogged != null; // if null, it's not logged, otherwise is logged

   void login() {}
   void logout() {}
}
abstract class AuthenticationState ... {
  ...
  final Profile? profileLogged;
}
```
```dart
class MainApp {
  void build(ctx) {
    // you can decide if it uses in or out of MaterialApp.
    // In this example, if authentication cubit is updated, all MaterialApp will recreate.
    return BlocProvider(
       create: (_) => AuthenticationCubit(),
       child: MaterialApp(
         ...
      ),
    );
  }
}
```

Now in the page where you can get profile data.

```dart
// remember to use Page1Cubit outside of the Page1Screen.build()
class Page1Screen {
 void build(ctx) {
    return Scaffold(
      body: Column(children:[
        Text('${context.read<AuthenticationCubit>().profileLogged.name}'), [1]
        BlocSelector<Page1Cubit, ...>(
           select: ....
           builder: (_,a, __) {
              return  Text('a');
           }
        ),
      ]),
    );
 }
}

class Page1Cubit ... {}
```

Remember if you need refresh the profile data, you need use `context.read<AuthenticationCubit>().refreshProfile()` (or any name you want to use).

[1] in this point, I don't remember why I hadn't used `watch` instead `read`. Maybe cause some complain when you execute... well try it.

These days my project I use ChangeNotifier to AuthenticationController and cubits for screens. I changed to this because ChangeNotifier has less complexity of states and how it works. But both can work if properly added, you need understand what is better for your project.
Of course, I'm only showing my experience, maybe it cannot be the correct solution, but this can give to you some ideas how to solve your problem.

**Comment by dipu0** [comment]
Thanka for your reply.

context.watch is nothing but BlocBuilder,
So context.read should solve my problem initially.
Read just read value it doesn't rebuild anything.
But i can only read from ui not in the other bloc logical layer, ( is that
correct?)

Want to know more about ChangNotifier,  i have used change notifier in
provider but never in bloc pattern.

Can you share some code base ? Or any repo!

Thanks in advance!

**Comment by dipu0** [comment]
> > In my case, I need to change data within a Bloc. For example, if a button should be hidden or shown based on the user's status, but I'm on a product details page and don't have the profile details, how should I handle this? Should I call an API from the product details page, or should I somehow pass the profile information to that screen?, cant use profile details blocbuilder because that btn already listening from product details page also,
> 
> Hum, If I understand your problem, I had similar problem and I remember to solve this way (I don't use anymore, look at the end why). I can shared my experience, maybe you can have some ideas based on this code.
> First you need know when you are authenticated in an app, you need a user or profile at the moment of all "login state". Usually people only store a boolean if it's logged or not, but you can store on `AuthenticationCubit` or `AuthenticationBloc` to represent the "login state". 
> 
> Example:
> ```dart
> class AuthenticationCubit ... {
>    ...
>    Profile get profile => state.profileLogged;
>    bool get isLogged => profileLogged != null; // if null, it's not logged, otherwise is logged
> 
>    void login() {}
>    void logout() {}
> }
> abstract class AuthenticationState ... {
>   ...
>   final Profile? profileLogged;
> }
> ```
> ```dart
> class MainApp {
>   void build(ctx) {
>     // you can decide if it uses in or out of MaterialApp.
>     // In this example, if authentication cubit is updated, all MaterialApp will recreate.
>     return BlocProvider(
>        create: (_) => AuthenticationCubit(),
>        child: MaterialApp(
>          ...
>       ),
>     );
>   }
> }
> ```
> 
> Now in the page where you can get profile data.
> 
> ```dart
> // remember to use Page1Cubit outside of the Page1Screen.build()
> class Page1Screen {
>  void build(ctx) {
>     return Scaffold(
>       body: Column(children:[
>         Text('${context.read<AuthenticationCubit>().profileLogged.name}'), [1]
>         BlocSelector<Page1Cubit, ...>(
>            select: ....
>            builder: (_,a, __) {
>               return  Text('a');
>            }
>         ),
>       ]),
>     );
>  }
> }
> 
> class Page1Cubit ... {}
> ```
> 
> Remember if you need refresh the profile data, you need use `context.read<AuthenticationCubit>().refreshProfile()` (or any name you want to use).
> 
> [1] in this point, I don't remember why I hadn't used `watch` instead `read`. Maybe cause some complain when you execute... well try it.
> 
> These days my project I use ChangeNotifier to AuthenticationController and cubits for screens. I changed to this because ChangeNotifier has less complexity of states and how it works. But both can work if properly added, you need understand what is better for your project.
> Of course, I'm only showing my experience, maybe it cannot be the correct solution, but this can give to you some ideas how to solve your problem.
> 
> 

Thanka for your reply.

context.watch is nothing but BlocBuilder,
So context.read should solve my problem initially.
Read just read value it doesn't rebuild anything.
But i can only read from ui not in the other bloc logical layer, ( is that correct?)

Want to know more about ChangNotifier,  i have used change notifier in provider but never in bloc pattern.

Can you share some code base ? Or any repo!

Thanks in advance!

**Comment by jttuboi** [comment]
> But i can only read from ui not in the other bloc logical layer, ( is that correct?)

In this example I showed to you, yes. But you can add data in constructor. I did this sometimes. Not specifically for userLogged data, but data you pass via routes. Example, an id or some data for page details.
```dart
class PageDetailsScreen ... {
  const PageDetailsScreen(this.id);
  final String id;
  ... 
  BlocProvider(
    create:(_)=> PageCubit(user: context.read...userLogged, id: id),
  )
}
```

You can use `get_it` package. Some people said Service Locator it's a anti-pattern, but maybe works for you.
```dart
void main() {
  // it's singleton because must be unique for all app
  GetIt.registerSingleton<AuthenticationCubit>(AuthenticationCubit());
  runApp(MainApp());
}
class Page1Cubit extends Cubit {
  Page1Cubit({AuthenticationCubit? authenticationCubit}) :
     _authenticationCubit = authenticationCubit ?? GetIt.get<AuthenticationCubit>();

  final AuthenticationCubit _authenticationCubit;

  void bla() { 
    print(_authenticationCubit.userLogged);
  }
}
```
I made this way, because you can add mock authentication cubit in constructor
```dart
// you want test page1Cubit
final page1Cubit = Page1Cubit(authenticationCubit: MockAuthenticationCubit());
```
or you can use `get_it` to test too.
```dart
GetIt.registerSingleton<AuthenticationCubit>(MockAuthenticationCubit());
final page1Cubit = Page1Cubit();
```

Extra: Ah, one think I remember, but doesn't work to solve your problem, but It's nice to know about this. You can connect blocs: https://bloclibrary.dev/architecture/#bloc-to-bloc-communication

<br>
<br>

> Want to know more about ChangNotifier, i have used change notifier in provider but never in bloc pattern.

For authentication controller, I use ChangeNotifier + ListenableBuilder + `get_it`.

ChangeNofifier+ListenableBuilder allows to refresh the flutter tree when something of authentication controller changes. GetIt allows to get the controller wherever you want. But remember what I said above about this package. 
The example:

```dart
void main() {
  // it's singleton because must be unique for all app
  GetIt.registerSingleton<AuthenticationCubit>(AuthenticationCubit());
  runApp(MainApp());
}

```dart
class MainApp ... StatelessWIdget {
  void build() { // allows to refresh the flutter tree
       return ListenableBuilder(
          listenable: _authenticationController,
          builder: (_, __) {
             return MaterialApp();
          };
    );
  }
}
```

```dart
class LoginCubit ... {
  LoginCubit({AuthenticationController? authenticationController}) :
     _authenticationController = authenticationController ?? GetIt.get<AuthenticationController>();

  final AuthenticationController _authenticationController;
  final UserRepository _userRepository; // similar _authenticationController

  void login() {
    final user  = _userRepository.getUser(); // get from server via API inside of repository
    _authenticationController.login(user); // this will refresh the userLogged variable and update all tree
  }
}
```

```dart
class AuthenticationController extends ChangeNotifier {
  ...
  User? userLogged;
  
  bool get isUserLogged => userLogged != null;

  void login(User user) {
     userLogged = user;
     notifyListeners();
  }
}
```

Ah, and remember, all of these is what works for me. Maybe it's not the best/correct solution, consider as alternative to help you to understand more about flutter. Sometimes you need to find solutions by yourself whats fit more for your project as I did.
There are an official tutorial of authentication https://bloclibrary.dev/tutorials/flutter-login/, but doesn't fit for me, because my authentication is more complex and bloc was hard to maintain, but as I show to you, bloc works perfectly in my project to keep controlling of state of the screens.

<br>
<br>

> Can you share some code base ? Or any repo!

Sorry I can't, I only wrote in the company code, it's private repository.

And sorry if I simplified the code, I'm tired at the moment I typed this post, ahahah. But I think you can understand how to complete it.
