### ISSUE TITLE
How to inspect bloc in Flutter Inspector?

### ISSUE THREAD

**Issue by vietstone-ng** [felangel/bloc#4198]
Hello,
My question as in the title. I know this is for issue, but I don't know how to ask questions, so I ask here.

The bloc is working well, but I just want to inspect the current state of bloc using Flutter Inspector. I can inspect with BlocBuilder, but it seems not quite right. The BlocProvider can exist without any BlocBuilder. So is there any way to inspect the current state/bloc with BlocProvider?

Thank you very much.

**Comment by felangel** [comment]
Hi @vietstone-ng 👋 
Thanks for opening an issue!

I'm working on an official [DevTools Extension](https://github.com/felangel/bloc/issues/2748) but it was put on pause due to higher priority items for a bit. I plan to resume in the next week or so. In the meantime, since `BlocProvider` extends `Provider` you should be able to get the basics using the Provider DevTools extension.

Hope that helps!
