### ISSUE TITLE
test: Right way to test bloc ? Seed vs adding events in act.

### ISSUE THREAD

**Issue by khanjasir90** [felangel/bloc#4220]
There are two ways by which you can initialise state when testing bloc i.e either use seed method or add the chained events that set that particular state inside the act method.

1. Using Seed - 
blocTest(
  'CounterBloc emits [10] when seeded with 9',
  build: () => CounterBloc(),
  seed: () => 9,
  act: (bloc) => bloc.add(CounterEvent.increment),
  expect: () => [10],
);

2. Using Act:
blocTest<MyBloc, MyBlocState>(
  'emits [MyBlocState] when SearchItemEvent is added',
  build: () => MyBloc(),
  act: (bloc) {
    bloc.add(ListItemsEvent()); // Start with loading the list
    bloc.add(SearchItemEvent(item: 'Apple')); // Start searching loaded list
  },
  skip: 2, // Skip emissions for intermediate states if not needed
  expect: () => [
    MyBlocState(filteredList: ['Green Apple', 'Red Apple'])
  ],
);

Both are doing the same thing, but... which should be the right way to do it

@felangel @zepfietje @tenhobi @alisson-suzigan @Abhishek01039 @hkuczynski

**Comment by GiancarloCante** [comment]
Hello @khanjasir90,

You should use a seed.

The idea is to focus on testing this event/case. You set all the conditions in the seed instead of depending on previous events that set this state. Think of it as mocking the previous state, similar to how you would mock a repository.

In the seed, you set the expected initial state for this event. For example:
* A seed state with some items to search, and expect to find some items.
* A seed state where the search should be forbidden, such as during loading or initialization, in these case, you would expect the event to be ignored and not emit new states or to emit a forbidden state.
