### ISSUE TITLE
Connecting Blocs through Domain : If  multiple blocs wants the result of one stream, each bloc is creating one stream .

### ISSUE THREAD

**Issue by xzghx** [felangel/bloc#4249]
I want to connect three blocs through domain layer and there is an api service that this service result is needed in three blocs. and like the documents example I have created repository stream method like this code:
 
```
 Stream<UserInfo> getUserInfo(
  {required String userKey, required String caller}) async* {
print("Repo Caller is $caller");

  UserInforesponse =
      await provider.getUserInfo(
    patientKey: patientKey,
  );

  yield response;
  }
```
And in blocs that need this method's result I am doing like this:

```
await emit.forEach(
      repo.getUserInfo(userKey: userKey,caller:"bloc1"),
      onData: (UserInfo response) {
        print("bloc1 got data");
        return state.copyWith( ...  );
      },
    );
```
And the same method in bloc 2 ,3 ...:

```
await emit.forEach(
      repo.getUserInfo(userKey: userKey,caller:"bloc2"),
      onData: (UserInfo response) {
        print("bloc2 got data");
        return state.copyWith(  ...  );
         
      },
    );
```
But the Problem is that these blocs are not listening to one Stream. each bloc is creating it's own individual stream. So as the result this is printed in the output:

```
 Repo Caller is bloc1
 Repo Caller is bloc2
```
So the api service is call twice and if I need this api result in 5 blocs, it will get called 5 times not one time. How can I achieve the expected behavior?

**Comment by felangel** [comment]
Hi @xzghx 👋 
Thanks for opening an issue!

To prevent making multiple requests, you can use a [BehaviorSubject](https://pub.dev/documentation/rxdart/latest/rx/BehaviorSubject-class.html) in the repository so that new listeners will automatically receive the latest value. You can also implement this functionality fairly easily by just having an optional cached value that you emit right away if it's not null.

Hope that helps! If you're still having trouble feel free to leave a comment or follow up on [Discord](https://discord.gg/bloc), thanks! 🙏
