### ISSUE TITLE
In flutter_login, logout not working on a new page 

### ISSUE THREAD

**Issue by 2000calories** [felangel/bloc#432]
The logout function is not working on a new page I created. When I click the logout button it did not redirect to login page. 
I check this similar issue but cannot solve it. https://github.com/felangel/bloc/issues/122#issue-416581697
Here is the code: https://github.com/2000calories/flutter_login_test.git
Thanks in advance.
![Screenshot_20190724-115802](https://user-images.githubusercontent.com/25191098/61764115-9721ee00-ae0a-11e9-88b4-dbfef31775d2.jpg)

**Comment by felangel** [comment]
Hi @2000calories 👋 
Thanks for opening an issue!

The issue is you’re pushing settings on top of the map app when you use Navigator.push so when you dispatch the Logout event you need to also call Navigator.of(context).pop() in order to remove the settings widget from the top of the navigation stack. 

Hope that helps!

**Comment by 2000calories** [comment]
Thanks. It works now.
