### ISSUE TITLE
Unable to re-login after logout in flutter_login

### ISSUE THREAD

**Issue by 2000calories** [felangel/bloc#438]
Sorry to bother you again. I cannot re-login after logout. I checked this similar issue https://github.com/felangel/bloc/issues/322#issue-449725258, but still don't know how to solve it.
Here is the code: https://github.com/2000calories/flutter_login_test.git

**Comment by cemanganas** [comment]
In your setting,dart file,
I think you need to change 

Navigator.push(
            context,
            MaterialPageRoute(builder: (_) => LoginPage(userRepository: userRepository)),
          );

To

Navigator.pushNamedAndRemoveUntil(context, '/', (_) => false);

**Comment by felangel** [comment]
Hi @2000calories 👋 
Thanks for opening an issue!

As @cemanganas pointed out you are pushing a new `LoginPage` to the navigations stack instead of popping the current one off of the stack so you're basically building up a stack multiple widgets deep which covers up the root widget.

Hope that helps!

**Comment by erfanh3h** [comment]
in similar case i use phoenix package and wrap app with it and its fix my issue.
link is  : [](https://pub.dev/packages/flutter_phoenix)
