### ISSUE TITLE
Expose bloc as paremeter in the builder

### ISSUE THREAD

**Issue by guitcastro** [felangel/bloc#447]
**Is your feature request related to a problem? Please describe.**
As in #415, we don't need to create an instance variable in order to dispose of the bloc, although we almost always have to create the bloc variable in order to dispatch events to it. 

**Describe the solution you'd like**
Change `Widget Function(BuildContext context, S state);` to : `Widget Function(BuildContext context, S state, Bloc<S, dynamic>);`

**Describe alternatives you've considered**
We are currently creating the bloc as a local variable, and passing as a parameter to the bloc provider.

**Comment by felangel** [comment]
Hi @guitcastro 👋 
Thanks for opening an issue!

What are your thoughts on exposing a dispatch function in the builder instead like:
```dart
BlocBuilder<Bloc, State, Event>(
  builder: (context, state, dispatch) {
    // do stuff
  }
)
```

**Comment by guitcastro** [comment]
We usually don't expose the dispatch function. Example:

Bloc code:
```
  void onInitial() => dispatch(
        Initial(),
      );
```

Although I', not if this is or not a good practice.

**Comment by felangel** [comment]
@guitcastro that's good to know. I think it comes down to personal preference but I do think it would be a bit weird if the `BlocBuilder` widget (which requires a bloc) returns a bloc. Also, I'm not completely sold on this idea personally because there will still be cases where you want to dispatch from outside of BlocBuilder and I don't want to encourage developers to nest unnecessary widgets within BlocBuilder just so they can dispatch conveniently 😛

**Comment by guitcastro** [comment]
Exposing dispatch fix our issue. 

Cutting down the number of variable in code is always a good pratice you will have the dispatcher available in a small scope, and maybe this constraint can be expanded to make dispatcher safer to use (making it private in bloc). Thus avoiding errors like dispatching an event from a disposed bloc.

However, this constraint will be a massive breaking change.

**Comment by CurrySenpai** [comment]
@guitcastro 

> This constraint can be expanded to make dispatcher safer to use (decreasing his visibility to private in bloc). This way, we can avoid errors like dispatching an event from a disposed bloc.

Hello, Also if dispatch is private (I don't like, in addition to promoting more boilerplate code), if you have 

```dart
  void onInitial() => dispatch(
        Initial(),
      );
```
you can call this event even if the bloc is disposed.

or maybe I did not understand well.

@felangel 
I don't like the idea to add more `Types` to BlocBuilder, many of my widget do not need to dispatch events to the pad.

If it is necessary to dispatch events to the bloc, I do not see any problem in using
```
BlocProvider<BlocA>(context).dispatch(Event);

BlocProvider<BlocA>(context).event();

final blocA = BlocProvider<BlocA>(context);

blocA.dispatch(Event);

blocA.event();
```

**Comment by felangel** [comment]
@CurrySenpai thanks for the feedback! I agree with the points you've made which is why I've been reluctant to make the changes thus far. After discussing this with many people and considering the implications, I am going to leave this out for now.

The main reasons why I don't want to make this change are:

- There will still be cases where you want to dispatch from outside of `BlocBuilder` and I don't want to encourage developers to nest unnecessary widgets within `BlocBuilder` just so they can `dispatch` conveniently
- I'd like to avoid adding extra types to `BlocBuilder` unless there is a really compelling reason.
- Accessing a bloc via `BlocProvider` and dispatching an event can all be done in a single line of code so we're not really gaining much in my opinion.

As always, I'm happy to discuss this and other alternatives so feel free to chime in with any input! Thanks everyone 👍
