### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by Sandesh-Solabannavar** [felangel/bloc#448]
Can any one help me to get an idea to implement the shopping cart in flutter using flutter_bloc.

**Comment by felangel** [comment]
Hi @Sandesh-Solabannavar 👋 
Thanks for opening an issue!

Do you have any specific questions or problems you're running into? It would likely end up being very similar to the [todos example](https://felangel.github.io/bloc/#/fluttertodostutorial) except instead of todos you'd be working with a shopping cart and items.

Let me know if that helps!

**Comment by Sandesh-Solabannavar** [comment]
Hi,
Im using FireStore as database i am not able to find a way to send data to store it in firetore using bloc.

**Comment by felangel** [comment]
In that case you can check out the [firestore todos](https://github.com/felangel/bloc/tree/master/examples/flutter_firestore_todos) example app. It should be very similar 👍

**Comment by Sandesh-Solabannavar** [comment]
Thanks for help..
If I am struck any where I'll come back.

**Comment by felangel** [comment]
@Sandesh-Solabannavar sounds good! You can also join the community on [gitter](https://gitter.im/bloc_package/Lobby) if you have any quick questions as you go through it.

Closing this for now 👍
