### ISSUE TITLE
Should representing different state using sum types

### ISSUE THREAD

**Issue by thezjy** [felangel/bloc#45]
**Is your feature request related to a problem? Please describe.**
In the Login Tutorial, `AuthenticationState` is represented by three finals: `isInitializing`, `isLoading` and `isAuthenticated`. This seems a bad idea because they can be combined in many illegal combinations, like `isLoading = true` && `isAuthenticated = true`.

**Describe the solution you'd like**
We should always represent discrete states using sum types. Since Dart doesn't have it yet, we can simulate using classes like this (taken from official examples of rxdart):
```dart
class SearchState {}

class SearchLoading extends SearchState {}

class SearchError extends SearchState {}

class SearchNoTerm extends SearchState {}

class SearchPopulated extends SearchState {
  final SearchResult result;

  SearchPopulated(this.result);
}

class SearchEmpty extends SearchState {}
```

**Additional context**
I'm sorry if this may sound like a rant. But the lack of sum types is just so disappointing when it comes to state management. While the same ideas can be coded both more secure and more expressive in modern languages like TypeScript and Swift, in Dart we have to make do.

**Comment by felangel** [comment]
@thezjy thanks for raising this issue.

In the case of `AuthenticationState` I intentionally expressed it in that way because you actually can have `isLoading` be true and `isAuthenticated` be true at the same time.
That’s only true because of the way I’ve implemented the LoginFlow (isLoading is true when persisting the token or deleting the token from keystone/keychain). So when you press logout the first state is actually `isLoading: true, isAuthenticated: true, isInitializing: true`. 

I understand your point though and think that in many cases you can follow the approach you described or even use enums to represent the different states. 👍

Thoughts?

**Comment by thezjy** [comment]
Your reply totally makes sense. :) What about something like this:
```dart
abstract class AuthenticationState {}

class AuthenticationUinitialized extends AuthenticationState {}

class AuthenticationInitialized extends AuthenticationState {
  final bool isLoading;
  final bool isAuthenticated;

  AuthenticationInitialized({
    this.isLoading,
    this.isAuthenticated,
  });
}
```

The point is to make clear the **and** and *or* of state.

The problem of Enum is that in Dart Enum doesn't have associated value.

**Comment by felangel** [comment]
Great suggestion! I’ll make the change shortly 👍
