### ISSUE TITLE
[Question] How to inject service instead of using UserRepository ?

### ISSUE THREAD

**Issue by sestegra** [felangel/bloc#47]
In flutter_login exemple, `UserRepository` creation is into `AppState` class.

If you need to use network service for authentication (e.g. firebase_auth), when writing tests, there is no easy way to mock `UserRepository` in the current implementation.

How to inject `UserRepository` in the current implementation ? with another Bloc ?

Let's assume the replacement of `UserRepository` by Firebase Authentication.
Then, how to share currentUser after login ? with another Bloc ?

**Comment by felangel** [comment]
@sestegra I have updated the `flutter_login` example and documentation in order to make it possible to inject the `UserRepository`.

Please check out https://github.com/felangel/bloc/commit/62c9b6b3599d5d2755a3ca4556ef0f13cefeea24

Also, if you want to share the currentUser after login you can make your `FirebaseAuthentication` layer available throughout your entire application by creating a Provider (`InheritedWidget`) for it and wrapping `MaterialApp` with the `FirebaseAuthenticationProvider` similar to how we make the `AuthenticationBloc` available to the entire widget tree.

Please let me know if that answers you question.

**Comment by sestegra** [comment]
@felangel Thank you for your prompt answer.
it sounds good to me.
