### ISSUE TITLE
Widgets cannot be rebuild after a new route

### ISSUE THREAD

**Issue by MonNguyen2502** [felangel/bloc#493]
Hi. I am having some trouble, please help me

**Describe the bug**
I took the new state and returned the new MaterialApp, but the pages behind the new router were not rebuilt

**Expected behavior**
DemoPage will be rebuilt when I click the "change language" button.

```
class MyApp extends StatelessWidget {
  Locale _locale;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<MainBloc, MainState>(
      bloc: BlocProvider.of<MainBloc>(context),
      builder: (context, state) {
        if (state is ChangeLanguageState) {
          _locale = state.locate;
        }

        return MaterialApp(
          title: '',
          locale: _locale ?? allTranslations.locale,
          localizationsDelegates: [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: allTranslations.supportedLocales(),
          debugShowCheckedModeBanner: false,
          home: HomePage(),
        );
      },
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          RaisedButton(
              child: Text('onPress'),
              onPressed: () =>
                  Navigator.of(context)
                      .push(MaterialPageRoute(builder: (context) => DemoPage()))
          )
        ],
      ),
    )
  }
}

class DemoPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //This function is not called again when myApp has a new state

    MainBloc _bloc = BlocProvider.of<MainBloc>(context);
    return Scaffold(
      body: RaisedButton(
          child: Text('Change language'),
          onPressed: () => _bloc.dispatch(ChangeLanguageEvent(locale: Locale('vn')))
      )
      ,
    );
  }
}

```

**Comment by felangel** [comment]
Hi @MonNguyen2502 👋 
Thanks for opening an issue!

Regarding your question, I would not recommend rebuilding the entire MaterialApp when you want to change the language. The problem is as you mentioned the routes will not be rebuild because they are independent of the base MaterialApp widget.

I would recommend overriding the `LocalizationDelegate` when the bloc state changes instead of changing the `locale`. 

You can do something like:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocBuilder<MainBloc, MainState>(
      bloc: BlocProvider.of<MainBloc>(context),
      builder: (context, state) {      
        return MaterialApp(
          title: '',          
          localizationsDelegates: [
            SpecificLocalizationDelegate(state.locale),
            const TranslationsDelegate(),
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: allTranslations.supportedLocales(),
          debugShowCheckedModeBanner: false,
          home: HomePage(),
        );
      },
    );
  }
}

class TranslationsDelegate extends LocalizationsDelegate<Translations> {
  const TranslationsDelegate();

  @override
  bool isSupported(Locale locale) => applic.supportedLanguages.contains(locale.languageCode);

  @override
  Future<Translations> load(Locale locale) => Translations.load(locale);

  @override
  bool shouldReload(TranslationsDelegate old) => false;
}

class SpecificLocalizationDelegate extends LocalizationsDelegate<Translations> {
  final Locale overriddenLocale;

  const SpecificLocalizationDelegate(this.overriddenLocale);

  @override
  bool isSupported(Locale locale) => overriddenLocale != null;

  @override
  Future<Translations> load(Locale locale) => Translations.load(overriddenLocale);

  @override
  bool shouldReload(LocalizationsDelegate<Translations> old) => true;
}
```

Sources
- https://www.didierboelens.com/2018/04/internationalization---make-an-flutter-application-multi-lingual/
- https://www.didierboelens.com/2018/04/internationalization---language-selector-widget-with-auto-collapse/

**Comment by MonNguyen2502** [comment]
@felangel The above solution is outdated, and I don't want to use context to get data. Apart from the suggestions you give, is there any way to rebuild the entire app?

**Comment by MonNguyen2502** [comment]
class MyApp extends StatelessWidget {
  Locale _locale;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<MainBloc, MainState>(
      bloc: BlocProvider.of<MainBloc>(context),
      builder: (context, state) {
        if (state is ChangeLanguageState) {
          _locale = state.locate;
        }

        return MaterialApp(
          title: '',
          locale: _locale ?? allTranslations.locale,
          localizationsDelegates: [
            S.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          supportedLocales: S.delegate.supportedLocales,
          debugShowCheckedModeBanner: false,
          home: HomePage(),
        );
      },
    );
  }
}


If I use the jetbrains i18n library, after changing the language, the whole application will be rebuilt. Therefore, comparing this code to the above code, which factors prevented the application from rebuilding.

**https://plugins.jetbrains.com/plugin/10128-flutter-i18n**

**Comment by felangel** [comment]
@MonNguyen2502 What part of it is outdated? I would strongly recommend using the standard localization implementation/strategy.

This issue doesn't have anything to do with bloc because when you use `BlocBuilder` it is equivalent to calling `setState` and rebuilding that widget. The problem you are facing is routes will not get notified if `MaterialApp` gets rebuilt and that is the intended behavior in Flutter. Routes are not descendants of other widgets; when you push a route you are pushing a widget that is disconnected from the existing widget tree.
