### ISSUE TITLE
Need help for dispatching the BlocListener (NetworkBloc) events when using the repository to handle the http calls

### ISSUE THREAD

**Issue by sanketwarule** [felangel/bloc#504]
Hello @felangel , sorry to disturb you again, As per your suggestion in #492 ,  I have added a repository between the Api(NetworkHandler) and Blocs(LoginBloc) i.e LoggedInUserRepository, Now my doubt is From where I can dispatch the Network events so that I could able to navigate to the Home Page or show the snackbar...

You can run the code as it is...
I have wrote the doubts in the Login Page(inside pages directory)
You can modify my code so that I can understand(Hint will also be helpful)

Below is the link of my project
https://github.com/sanketwarule/account_opening_app

**Comment by felangel** [comment]
Hi @sanketwarule 👋 
Thanks for opening an issue!

Have you gone through the [login tutorial](https://felangel.github.io/bloc/#/flutterlogintutorial)? If not, I would highly recommend it. I would recommend having a `UserRepository` or `AuthenticationRepository` instead of a `LoggedInUserRepository` and exposing methods like `login`, `logout`, etc...

Then you can have an `AuthenticationBloc` which you use at the root of your app to dispatch an `AppStarted` event. The `AuthenticationBloc` would then use the `UserRepository` to determine if the state should be `Authenticated` or `Unauthenticated`. If the state is `Authenticated` you can show the `HomePage` otherwise you can show the `LoginPage`.

The relevant code can be found [here](https://felangel.github.io/bloc/#/flutterlogintutorial?id=putting-it-all-together)

```dart
void main() {
  BlocSupervisor.delegate = SimpleBlocDelegate();
  final userRepository = UserRepository();
  runApp(
    BlocProvider<AuthenticationBloc>(
      builder: (context) {
        return AuthenticationBloc(userRepository: userRepository)
          ..dispatch(AppStarted());
      },
      child: App(userRepository: userRepository),
    ),
  );
}
```

Hope that helps 👍
