### ISSUE TITLE
flutter_weather is NOT updated to day?

### ISSUE THREAD

**Issue by KexiHe** [felangel/bloc#532]
**Describe the bug**
I think source code which showed in the document is not consist with code in github.
By the way, I like the new version, it is so flexible.

**To Reproduce**
Document
https://felangel.github.io/bloc/#/flutterweathertutorial?id=weather

github Source
https://github.com/felangel/bloc/blob/master/examples/flutter_weather/lib/widgets/weather.dart
Line: 59~77

**Comment by felangel** [comment]
Hi @KexiHe 👋 
Thanks for opening an issue and for the positive feedback!

Regarding your question, I’m not sure I understand what’s outdated in the documentation. I believe the BlocListener code you’re referring to on lines 59-77 is included in the [Dynamic Theming](https://felangel.github.io/bloc/#/flutterweathertutorial?id=dynamic-theming) section of the documentation (you’ll have to scroll down a bit to where BlocListener is introduced). Let me know if that helps or if I misunderstood your question. Thanks!

**Comment by KexiHe** [comment]
Thank you for your speedy response!

I mean the content of class Weather is different.
I realized that they are two different implementation. In the tutorial, class Weather extends StatelessWidget, in github, class Weather extends StatefulWidget. Maybe they get the same result.

**Comment by felangel** [comment]
@KexiHe no problem! Did you go through the entire tutorial? The `Weather` class only starts of extending `StatelessWidget` initially. Towards the end of the tutorial when it goes into [pull to refresh](https://felangel.github.io/bloc/#/flutterweathertutorial?id=pull-to-refresh), the `Weather` class gets refactored into a `StatefulWidget` in order to manage the `Completer`. Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍
