### ISSUE TITLE
Access BLoc without specify bloc field in BlocBuilder() after 0.20.0

### ISSUE THREAD

**Issue by imaffe** [felangel/bloc#542]
I noticed after upgrading 0.20.0 , we can use BlocBuilder without specify `bloc` field, and use it directly like this :

```
BlocBuilder<BlocA, BlocAState>(
  builder:(context, state) {
  }
)
```
But how do we get a reference to the bloc object if we want to `dispatch` a new event like this : 
```
BlocBuilder<BlocA, BlocAState>(
  builder:(context, state) {
     bloc.dispatch(BlocAStateChangedEvent);
     return Widget(...);
  }
)
```
Do I use `BlocProvider.of<BlocA>(context))` ? Is there any way to expose this field like `currentState` with the builder? Wondering how to do this. 

Thanks so much Felix, maybe I can help you answer some of the questions after learning a bit more about bloc !

**Comment by felangel** [comment]
Hi @imaffe 👋 
Thanks for opening an issue!

As you mentioned, `BlocBuilder` automatically handles looking up the bloc internally but if you want to dispatch events, you still have to get your own reference to the bloc via `BlocProvider.of<BlocA>(context)`.

We have discussed the possibility of including the dispatch in the builder but have decided not to mainly because it would make things a bit more verbose (you'd have to provide the type of the event) and because it adding dispatch to the builder would encourage developers to nest more widgets in a builder just for the convenience of having a dispatch.

Hope that helps! 👍
