### ISSUE TITLE
Chaining actions after dispatch

### ISSUE THREAD

**Issue by vitor-gyant** [felangel/bloc#547]
I've several situations where I want to chain some action after a given event is actually processed. Since dispatch does not return a future my workaround is to send completion callbacks on each event.

IMO, allowing dispatch to return a future which is completed when mapEventToState returns could be a good design.

Anyone with similar needs ? thanks.

**Comment by felangel** [comment]
Hi @vitor-gyant 👋 
Thanks for opening an issue!

Unfortunately, I don't think this is possible because there isn't a good way to know when a dispatch has "finished". Bloc streams are constantly open and emitting new states and for a given event multiple states can be emitted. This means that internally a bloc can't tell if it's done processing an event because it can't make the assumption that once a state is yielded the event has been processed.

Example:
```dart
mapEventToState(event) {
  if (event is MyEvent) {
    yield Loading();
    try {
      final result = await _repository.someAsyncOperation();
      yield Success(result);
    } catch (_) {
      yield Failure();
    }
  }
}
```

For the flow above, the bloc can't assume that when `MyEvent` has been dispatched and `Loading` has been emitted that the bloc is "done". There is still one more state that needs to be emitted later on (either `Failure` or `Success`). Hopefully that helps clarify things a bit 👍 

I am open to suggestions but I don't see any clean way to accomplish this in the current state.
