### ISSUE TITLE
Issues while upgrading to latest version

### ISSUE THREAD

**Issue by chethanprabhakar** [felangel/bloc#631]
Hello,

I am using these versions for quite some time now

- bloc: ^0.14.0
- flutter_bloc: ^0.15.0
- equatable: ^0.2.0

Seeing errors all over the place when I change the version to the latest.

Whats is the best way to upgrade?

Thanks,
Chethan

**Comment by lingster** [comment]
I would recommend reading the change log file here :+1:
https://github.com/felangel/bloc/blob/master/packages/bloc/CHANGELOG.md

I just upgraded myself so youll have to do some search and replace. Ie change `currentstate` to `state` and `dispose` to `close` etc.

**Comment by mhadaily** [comment]
I have also simply managed to upgrade our codebase which is quite a big and uses flutter_bloc quite heavily. most important is what @lingster said. 
You can check this article by @felangel https://medium.com/flutter-community/bloc-library-v1-0-0-is-here-1f64bd6d3518 

technically: 
in your `Bloc`

from 
```
@override
  void dispose() {
    // Your clean up codes
    super.dispose();
  }
```
to 
```
@override
  void close() {
    // Your clean up codes
    super.close();
  }
```

and in bloc again 

from 
``` 
currentState 
//or 
state
```

when you need to manipulate your state by add/dispatch an event
from 
```
 BlocProvider.of<AnyBloc>(context).dispatch(YourEvent());
```
to 

```
 BlocProvider.of<AnyBloc>(context).add(YourEvent());
```


or if you are in Bloc itself 

from 
```
dispatch(YourEvent());
```

to 
```
add(YourEvent());
```

these changes should make your code compatible.

**Comment by felangel** [comment]
Hey @chethanprabhakar 👋 
Thanks for opening an issue!

As others have already mentioned you can refer to the changelogs (each package has one e.g [bloc](https://github.com/felangel/bloc/blob/master/packages/bloc/CHANGELOG.md)) and all of the [tutorials](https://bloclibrary.dev/#/fluttercountertutorial) and [examples](https://github.com/felangel/bloc/tree/master/examples) in the documentation are always kept up to date. You can also refer the [v1.0.0 announcement article](https://link.medium.com/ZMsXN3Bxe1) or @mhadaily‘s [awesome upgrade guide](https://dev.to/mhadaily/upgrade-to-bloc-library-v1-0-0-for-flutter-and-angular-dart-2np0). If you have more specific questions you can also post on [gitter](https://gitter.im/bloc_package/Lobby). 

I would also recommend upgrading equatable independently of the bloc packages so that you limit the amount of changes being made at once. 

Hope that helps! 👍

**Comment by chethanprabhakar** [comment]
thanks @lingster @mhadaily @felangel
