### ISSUE TITLE
Send state directly, without event mapping

### ISSUE THREAD

**Issue by rmnbod** [felangel/bloc#634]
Hello @felangel 
How can I send states directly to the view, without mapping from events, in one way flow?
Say, for instance, if there is an open socket connection and we need to display changes in UI.

**Comment by bigworld12** [comment]
since events and blocs can be any type, you can simply do 
```dart
Bloc<StateType,StateType>
```

**Comment by tenhobi** [comment]
Because Bloc should have only one way in and one way out, you should also `add` an `Event`, for example, `SocketUpdate`, which would send the appropriate state.

That means you can still update the state in reaction to user events and also your API events.

**Comment by felangel** [comment]
Hi @rmnbod 👋 
Thanks for opening an issue!

If you don't want to map events to states then you probably don't need a bloc. Can you please elaborate on your use-case?

Generally, I'd recommend the approach @tenhobi described when working with a socket because you will likely want to process the data received in some way before exposing it to the presentation layer.

**Comment by rmnbod** [comment]
I've had thoughts about approach described by @tenhobi but was curious if one could send state directly. 
Seems I would settle with socket event in this case.
Much appreciate your attention guys, thanks!
