### ISSUE TITLE
Error while resolving dependency 

### ISSUE THREAD

**Issue by KonradDos** [felangel/bloc#665]
**Describe the bug**
I am getting following error when project name is **bloc**
`[bloc] flutter packages get`
`Running "flutter pub get" in bloc...`                            
`Because bloc depends on flutter_bloc ^2.0.0 which depends on bloc ^2.0.0, bloc ^2.0.0 is required.`

`So, because bloc is 1.0.0+1, version solving failed.`
`pub get failed (1)`
`exit code 1`

**To Reproduce**
1. Create new project with name **bloc** 
2. Add `flutter_bloc ^2.0.0` dependency
3. Try to resolve dependencies

**Expected behavior**
Downloaded package

**Comment by felangel** [comment]
Hi @KonradDos 👋 
Thanks for opening an issue!

The problem is your package cannot also be called 'bloc'. `flutter_bloc` has a dependency on the core `bloc` package so it is unable to resolve because there is a naming conflict between your package and the published `bloc` package. You need to rename your project to something else.

Hope that helps 👍

**Comment by karthikayansde** [comment]
thank you bro
