### ISSUE TITLE
Any good guide about how to design bloc and repository?

### ISSUE THREAD

**Issue by wyxcoder** [felangel/bloc#681]
It seems the Repository is mixed with Bloc, I wonder what is right way to lay them out in a project.

**Comment by felangel** [comment]
Hi @wyxcoder 👋 
Thanks for opening an issue!

Can you provide more context? A bloc should depend on one or more repositories in order to fetch the required data to trigger a state change. You can refer to the [bloc architecture documentation](https://bloclibrary.dev/#/architecture) for more details. Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions/information and I'm happy to continue the conversation 👍
