### ISSUE TITLE
BlocBuilder nest hell

### ISSUE THREAD

**Issue by ffpetrovic** [felangel/bloc#714]
**Is your feature request related to a problem? Please describe.**
bloclibrary.dev shows that we are supposed to properly separate concerns by having a single bloc for different parts of the app. Consider blocs `Bloc1` `Bloc2` `Bloc3` `Bloc4` `Bloc5`, and a `build` method. Like bloclibrary.dev shows, a common pattern is to have a `...Loading` `...Loaded` etc... Specifically the `BlocXLoadingState`. If in the root of my build method I want to check whether ANY of these blocs are in "loading" state, how would I go about it? Not having to nest 2 spaces (or even 4) for *every* Bloc (because, honestly, I feel like wanting to listen to even 8 blocs for loading state seems like a totally valid use case for me), would be really appreciated. Sorry if this is a dupe. ❤

**Describe alternatives you've considered**
Nesting BlocBuilders in the root of the build method.

**Comment by tenhobi** [comment]
You can probably use `MultiBlocListener` https://bloclibrary.dev/#/flutterbloccoreconcepts?id=multibloclistener

**Comment by ffpetrovic** [comment]
Thanks for the response! This means that I have to store the value inside the widget state which kind of destroys the whole purpose of the bloc. No?

**Comment by tenhobi** [comment]
Oh, I see. You probably want to, for example, display a widget with "Some of the Blocs are Loading", right?

Well, at the moment, there is no `MultiBlocBuilder`. The Dart language does not provide some ADT to help with this, so we would have to create `BlocBuilder*` for * in 1..10, which is not a nice solution, because, in most of the cases, you don't need it. See https://github.com/felangel/bloc/issues/538

For now, for your issue, it might be possible to create a separate bloc which would take a list of blocs, it would listen to them (only the ones which are not closed yet) and process the number of Loading states and fire a State with that number, or maybe even names. That should be kinda trivial to make.

I know, it's probably not the best solution, but I don't think so you would find something better at the moment. :/

**Comment by felangel** [comment]
Hi @ffpetrovic 👋 
Thanks for opening an issue!

As @tenhobi mentioned you can use combine the blocs into a single bloc. I would recommend potentially using `combineLatest` on the individual bloc states and yielding a new state based on the individual bloc states.

Hope that helps 👍

**Comment by ffpetrovic** [comment]
Closing this means that you think this isn't a common use case and/or doesn't deserve a more graceful solution?

**Comment by felangel** [comment]
@ffpetrovic can you provide more detail/provide a sample app which illustrates the problem you're having and provide a bit more context regarding why you feel combineLatest is not a valid solution? I think in most cases this problem is a sign that maybe the blocs haven't been structured properly (they are too granular/data driven and not use case driven). I'm happy to reopen this but I would need to better understand the problem you're having. Thanks! 👍

**Comment by ffpetrovic** [comment]
Any example of this somewhere? How will that look in the final UI widget?
