### ISSUE TITLE
How can I ignore a state in BlocBuilder?

### ISSUE THREAD

**Issue by taoyimin** [felangel/bloc#717]
```
BlocListener<UploadBloc, UploadState>(
            listener: (context, state) {
              if (state is UploadSuccess) {
                //todo something
              }
            },
            child: BlocBuilder<UploadBloc, UploadState>(
              builder: (context, state) {
                if (state is DataLoaded) {
                  return _buildPageLoaded(state.data);
                }
              },
            ),
          ),
```
The above code will throw an exception(A build function returned null).
I want to do something when listen to UploadSuccess state. But I want to keep the page instead of return a widget.

**Comment by felangel** [comment]
Hi @taoyimin 👋 
Thanks for opening an issue!

Regarding your question, `BlocBuilder` must always return a widget so it's up to you to tell it what to return for each possible state. Based on you example, I would recommend splitting your `UploadBloc` into two blocs because it is currently dealing with both uploading as well as downloading data (multiple responsibilities). If you refactored your code to use two blocs it would look something like:

```dart
BlocListener<UploadBloc, UploadState>(
  listener: (context, state) {
    if (state is UploadSuccess) {...}
  },
  child: BlocBuilder<DownloadBloc, DownloadState>(
    builder: (context, state) {
      if (state is DataLoadSuccess) { ... }
      if (state is DataLoadFailure) { ... }
      return CircularProgressIndicator();
    },
  ),
)
``` 

Hope that helps 👍

**Comment by taoyimin** [comment]
Thank you for your reply. This is very helpful for me.:+1:
