### ISSUE TITLE
yield* broadcast streams

### ISSUE THREAD

**Issue by larssn** [felangel/bloc#725]
**Describe the bug**
Not sure if this is deliberately not supported, but if I `yield*` a broadcast stream (hot observable), the bloc seems to freeze and not accept any more events, or produce any more output.

**To Reproduce**

```
Observable<BuiltList<Order>> search(String searchTerm) {
    final orderNumber = _orderRepo.collectionRef.where('orderNumber', isEqualTo: searchTerm).limit(1).snapshots();
    final name = _orderRepo.collectionRef.where('name', isEqualTo: searchTerm).limit(25).snapshots();

    return Observable.merge([orderNumber, name])
        .map((q) => BuiltList.of(q.documents.map((d) => Order.fromSnapshot(d.data, d.documentID))))
        .distinct()
        .asBroadcastStream();
}

Stream<MyState> test(String searchTerm) async* {
   yield* search(searchTerm); // <-- Seems to emit once, and then never again, problably because the internals in bloc waits for it to complete, which it doesn't.
}
```

**Expected behavior**
Are we even allowed to attempt this? :)

(Apologies if this is documented somewhere)

**Comment by felangel** [comment]
Hi @larssn 👋
Thanks for opening an issue!

Your assumption is correct. This won't work because the stream never completes. I would recommend subscribing to the stream within the bloc and adding a new event when data is received. You can check out [this](https://github.com/felangel/bloc/blob/b5db7064da8825f5f496c54e0f026e10516ec5cb/examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart#L19) example. 

Closing for now but feel free to comment if you have additional questions or comments and I'm happy to continue the conversation 👍
