### ISSUE TITLE
ListView was rerender when inifinite scroll

### ISSUE THREAD

**Issue by danbeo95** [felangel/bloc#735]
Hey gui.I implements examaple https://bloclibrary.dev/#/flutterinfinitelisttutorial with Infinite scroll.But i found that my ListView was rerender after PostLoaded was update with new posts.Please help me.Thanks so much.Here is my code
```dart
 body: BlocBuilder<PostBloc, PostState>(
        builder: (context, state) {
          if (state is PostLoading) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
          if (state is PostLoaded) {
            if (state.posts.isEmpty) {
              return Center(child: Text('No post'));
            }
            return ListView.builder(
              itemBuilder: (context, i) {
                return PostWidget(post: state.posts[i]);
              },
              itemCount: state.posts.length,
            );
          }
          return Text('Something wrong');
        },
      ),
```

**Comment by hahai96** [comment]
Yes, listview will rebuild the item being displayed on the screen, not all

**Comment by felangel** [comment]
Hi @danbeo95 👋
Thanks for opening an issue!

As @hahai96 mentioned this is expected behavior and ListView.builder only renders the items in view so it should not be a problem. Hope that answers your question. Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
