### ISSUE TITLE
[Question] mapEventToState is getting called just the first time

### ISSUE THREAD

**Issue by Diecar** [felangel/bloc#739]
Hi,
I've been trying to do an app assigned to me using the bloc pattern, I followed the [flutter_bloc infinite list tutorial](https://bloclibrary.dev/#/flutterinfinitelisttutorial) and everything works fine except for one thing.
I use two blocs for two different infinite list and the second one is supposed to load data based on the row that you selected in the first one, the thing is It just loads the data from the first row selected in the app. When you select another one It still shows the data from the first one. I've debugged the code and it runs throught the .add call everytime but mapEventToState just gets called the first time.
I've checked the code and I'm pretty sure I haven't called the dispose function manually so I don't know where the issue is coming from.
The source code for the app is [here](https://github.com/Diecar/flutterProgram) but It loads the data from a local database using mongo so you won't be able to run it properly without the database. (I've included the dump files for the database in addition to a .mp4 demo of the app to see how its working).

**Comment by felangel** [comment]
Hi @Diecar 👋 
Thanks for opening an issue!

I took a look at your app and was unable to run it locally because it requires a local MongoDB instance. I did however notice several things that I would not recommend:

1. I didn't understand the purpose of your `Blocs` class. You should have different classes which extend Bloc rather than a single `Blocs` which you subclass.
2. The way you setup the callback function in `HomePageState` was confusing to me and I'm not sure I understand why you have have workouts or exercises rather than a dedicated `WorkoutsBloc` and a dedicated `ExercisesBloc` (if they are considered different).

In general, I am unable to help because I cannot run the application locally (due to the MongoDB requirement) and I am also confused by the code organization. I would highly recommend removing your `Blocs` class and working with the two blocs independently as well as cleaning up some of the callback code you have (there's no need for callbacks in this case you can simply call BlocProvider.of<WorkoutsBloc>(context) from the subtree to access it).

Hope that helps and closing for now as I feel there's not much more I can do to help without additional input.
