### ISSUE TITLE
Wrong link on pub.dev example tab

### ISSUE THREAD

**Issue by basilex** [felangel/bloc#819]
**Describe the bug**

Hello!
example link on https://pub.dev/packages/flutter_bloc#-example-tab-

**example/lib/main.dart** is points to

_https://github.com/felangel/bloc/blob/master/example/lib/main.dart_

but it's wrong and it should be changed to

_https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/example/lib/main.dart_

**To Reproduce**
1. Go to 'https://pub.dev/packages/flutter_bloc#-example-tab-'
2. Click on 'example/lib/main.dart'
3. See 404 error

**Comment by felangel** [comment]
Hi @basilex 👋 
Thanks for opening an issue!

Unfortunately, I believe this is an issue with pub.dev because I don't think I have any control over that link 😞. I would recommend opening an issue [pub.dev](https://github.com/dart-lang/pub-dev/issues/new?body=URL%3A+https%3A%2F%2Fpub.dev%2F%0A%0A%3CDescribe+your+issue+or+suggestion+here%3E&title=%3CSummarize+your+issues+here%3E&labels=Area%3A+site+feedback). Thanks! 👍

**Comment by basilex** [comment]
Done!
Your can check this issue here
https://github.com/dart-lang/pub-dev/issues/3288
Hope this helps!

**Comment by felangel** [comment]
Will be included in the next release 👍
