### ISSUE TITLE
[Question] Why did you change from StatefullWidget to InheritedWidget?

### ISSUE THREAD

**Issue by programadorthi** [felangel/bloc#84]
Hi, I saw that you have changed from StatefulWidget to InheritedWidget because you haven't implemented the dispose method. [#57](https://github.com/felangel/bloc/pull/57)

Why did you change from stateful to inherited if you could implement dispose method as the Didier version?
https://www.didierboelens.com/2018/12/reactive-programming---streams---bloc---practical-use-cases/

The Didier approach is good because we don't need to create StatefulWidget to use the dispose method only.

**Comment by felangel** [comment]
@programadorthi I changed to InheritedWidget because it's more performant. `ancestorWidgetOfExactType` is O(n) vs `ancestorInheritedElementForWidgetOfExactType` which is O(1).

In addition, I don't think it makes sense to automatically dispose the bloc for you because it would be making lots of assumptions about whether or not the bloc is being used in other parts of the application. I wanted the developers using the library to have full control over when a bloc is disposed.

Let me know if that helps!

**Comment by programadorthi** [comment]
Yes, his new version in the link has changed to use `ancestorInheritedElementForWidgetOfExactType` too. I agree with you about full control over the Blocs, but in general and using Bloc pattern, we dispose blocs using dispose method in the StatefulWidget State. And when we use a global bloc its dispose is not called until the whole app or parent page is removed from navigation.

So, IMHO and following the Didier pattern, I think that should be the default flutter bloc behavior.

Again, thanks for the awesome library.

**Comment by felangel** [comment]
Yes that's true for a global bloc but using a BlocProvider does not make the bloc global. It's only global if the BlocProvider is an ancestor of `MaterialApp`.

Hope that makes sense and thanks for the positive feedback! 👍
