### ISSUE TITLE
Right way to dispose the bloc

### ISSUE THREAD

**Issue by basnetjiten** [felangel/bloc#875]
I believe the widget which creates or uses the bloc should close/dispose  it. But when I pass the same bloc down the tree do I have to close it in that particular widget ? 
If I do so then the bloc would not be reusable in some other widget which might keep on requiring it after the later widget uses it because it would have already disposed it. 
Can you please help me with effectively using bloc without having to close in other child or descendant widget.

**Comment by felangel** [comment]
Hi @basnetjiten 👋 
Thanks for opening an issue!

The recommended approach is to use `BlocProvider(create: (context) => MyBloc(), child: MyChild())` to create and provide the bloc at the nearest common ancestor of all widgets which need access to the bloc. You should not be manually closing the bloc because `BlocProvider` automatically handles closing for you when `BlocProvider` is removed from the widget tree 👍 

Hope that helps!

**Comment by basnetjiten** [comment]
Hi @felangel. what if I don't want to dispose the bloc automatically by the providers? because I want the same bloc to be reusable in another widget as well?

**Comment by basnetjiten** [comment]
I figured it out. :D  I think I need to pass it from the root of the app MaterialApp. Anyway thank you!

**Comment by felangel** [comment]
In cases where you want multiple widgets to have access to the same bloc you can just provide the bloc at the nearest common ancestor. MultiBlocProvider doesn’t close by default it just allows you to have multiple providers and it’s up to the individual BlocProviders to handle closing blocs automatically. Does that help clarify things?
