### ISSUE TITLE
Example of working with complex State objects in angular_bloc

### ISSUE THREAD

**Issue by eloypastor** [felangel/bloc#93]
Hi! Can you show me how to bind the state object in HTML file? In the `angular_counter_example` the state is a simple `int` and you bind this state to view like this:

```dart
<h2>Current Count: {{ counterBloc | bloc }}</h2>
```

If my state seems like this:

```dart
class MyState {
   num foo;
   num bar;
}
```

How can I work with this state in HTML view? Is necesary to use the BlocPipe?

Thanks!

**Comment by felangel** [comment]
Have you taken a look at the GithubSearch example. In that one, we have blocs that are shared between flutter and angular. 

Check out https://felangel.github.io/bloc/#/flutterangulargithubsearch

I think it is exactly what you’re looking for because it shows how to implement the same components using the same blocs in flutter vs angular. 

Let me know if that helps!

**Comment by eloypastor** [comment]
Yes! This example helps me!

```
<github-search-body [state]="githubSearchBloc | bloc"></github-search-body>
```

This is what i'm looking for.

Thanks!

**Comment by felangel** [comment]
No problem 👍
Glad I was able to help!
