### ISSUE TITLE
BlocProvider.of<BlocA>(context) does not work in showModalBottomSheet

### ISSUE THREAD

**Issue by snj07** [felangel/bloc#942]
**Is your feature request related to a problem? Please describe.**
`BlocProvider.of<BlocA>(context)` does not work in `showModalBottomSheet`

**Describe the solution you'd like**
It should work in `showModalBottomSheet` also.

**Comment by sterrenburg** [comment]
This happened to me because of multiple contexts. 

`showModalBottomSheet` has its own `context` field, and also exposes one via `builder`.

Check out this [gist that creates a `Scaffold` and provides its `MyBloc` `showModalBottomSheet`](https://gist.github.com/sterrenburg/75c7f5e6fb43dceb2db9a33e7c405107).

The gist assumes that there is a `BlocProvider<MyBloc>` in the Widget tree.

**Comment by warriorCoder** [comment]
If you look at the widget tree you'll see that the bottomSheet, which is a modal, is directly underneath the app (iirc) thus you need to make sure to either load the bloc before popping the modal and then passing it in, or move the bloc declaration above the modal so it can be pulled from the modal's context.

**Comment by snj07** [comment]
Yes, I knew this part. But I was thinking if somehow we can make the bloc available to bottom sheet without passing it as a parameter
