### ISSUE TITLE
How to use bloc library with google_maps_flutter?

### ISSUE THREAD

**Issue by Nyanny** [felangel/bloc#947]
I want to use this library with the Google map(google_maps_flutter package).
There should be a map where markers should be placed from RESP API, and also some actions with onTap on this markers. (Perhaps this info will be usefull).
With markers I can imagine what should I do(another BLOC for markers) or will think about this later.
But I cant recognize how to create MapBloc.
Which event should be input and which should be output?
For example
```
class MapBloc extends Bloc<MapEvent, MapState>{

  Location location = Location();

  @override
  // TODO: implement initialState
  get initialState => null;

  @override
  Stream mapEventToState(MapEvent event) {
    // TODO: implement mapEventToState
    return null;
  }


}
```
What MapEvent should(or can) be and what MapState should(or can) be?

**Comment by felangel** [comment]
Hi @Nyanny 👋 
Thanks for opening an issue!

It's tough to answer your question because it depends highly on your feature. You probably need a `MapStarted` event which prompts your bloc to make the request and transform the data into a set of Marker.

I'm more than happy to discuss this on the [discord server](https://discord.gg/Hc5KD3g) 👍
