### ISSUE TITLE
Named BlocProvider to use the same Bloc implementation multiple times in the same widget

### ISSUE THREAD

**Issue by SandroMaglione** [felangel/bloc#955]
I implemented a `TimerBloc` class that must be used by two different widgets inside the same parent widget. Basically, I have a 'global' timer that counts the time from when the widget is initialized to when it is disposed, and another 'local' timer that counts the time as requested by the user input. 

I would like to use the same implementation of `TimerBloc` for both timers since they work the same way. The problem is that I cannot provide two different `BlocProvider` with the same `TimerBloc` since they are recognized as the same one.
```dart
// Same TimerBloc for two child widgets
MultiBlocProvider(
   BlocProvider<TimerBloc>(
      create: (context) => getIt<TimerBloc>(),
    ),
   BlocProvider<TimerBloc>(
      create: (context) => getIt<TimerBloc>(),
    ),
]
```

Is it possible to assign a name to the `BlocProvider` to use the same `TimerBloc` multiple times in the same widget? Is there another simpler solution that I am not aware of?
```dart
// Would this make sense?
MultiBlocProvider(
   BlocProvider<TimerBloc>(
      name: "globalTimer",
      create: (context) => getIt<TimerBloc>(),
    ),
   BlocProvider<TimerBloc>(
      name: "localTimer",
      create: (context) => getIt<TimerBloc>(),
    ),
]
...
BlocBuilder<TimerBloc, TimerState>(
      name: "globalTimer",
      ...
)
```

**Comment by felangel** [comment]
Hi @SandroMaglione 👋 
Thanks for opening an issue!

If you need to provide different instances of the same bloc to the same part of the widget tree you can use mixins to distinguish the two types like so:

```dart
import 'package:flutter/material.dart';

import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

mixin GlobalCounter on Bloc<CounterEvent, int> {}

mixin LocalCounter on Bloc<CounterEvent, int> {}

enum CounterEvent { increment }

class CounterBloc extends Bloc<CounterEvent, int>
    with GlobalCounter, LocalCounter {
  @override
  int get initialState => 0;

  @override
  Stream<int> mapEventToState(
    CounterEvent event,
  ) async* {
    switch (event) {
      case CounterEvent.increment:
        yield state + 1;
        break;
    }
  }
}

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider<GlobalCounter>(
      create: (_) => CounterBloc(),
      child: MaterialApp(
        home: HomeScreen(),
      ),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Home')),
      body: ListView(
        children: <Widget>[
          ListTile(
            title: const Text('Global Counter'),
            trailing: const Icon(Icons.chevron_right),
            onTap: () =>
                Navigator.of(context).push(GlobalCounterScreen.route()),
          ),
          ListTile(
            title: const Text('Local Counter'),
            trailing: const Icon(Icons.chevron_right),
            onTap: () => Navigator.of(context).push(LocalCounterScreen.route()),
          )
        ],
      ),
    );
  }
}

class GlobalCounterScreen extends StatelessWidget {
  static Route route() {
    return MaterialPageRoute(
      builder: (_) => const GlobalCounterScreen._(),
    );
  }

  const GlobalCounterScreen._({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Global Counter'),
      ),
      body: Center(
        child: BlocBuilder<GlobalCounter, int>(
          builder: (context, state) {
            return Text('Global Count: $state');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () =>
            context.bloc<GlobalCounter>().add(CounterEvent.increment),
      ),
    );
  }
}

class LocalCounterScreen extends StatelessWidget {
  static Route route() {
    return MaterialPageRoute(
      builder: (_) => BlocProvider<LocalCounter>(
        create: (_) => CounterBloc(),
        child: const LocalCounterScreen._(),
      ),
    );
  }

  const LocalCounterScreen._({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Local Counter'),
      ),
      body: Center(
        child: BlocBuilder<LocalCounter, int>(
          builder: (context, state) {
            return Text('Local Count: $state');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () =>
            context.bloc<LocalCounter>().add(CounterEvent.increment),
      ),
    );
  }
}
```

Hope that helps 👍

**Comment by marcoprado17** [comment]
Hi @felangel , thanks for the lib it`s awelsome.

I am facing similar issue, but on my case I have to deal with a dynamic number (from 1 to n) of bloc instances from the same Bloc class. In that case, how can we proceed? Of Course we can create the Blocs without the BlocProvider, but there is a solution with the BlocProvider?

Thanks,

Marco

**Comment by felangel** [comment]
Hi @marcoprado17 👋 
Thanks for the positive feedback!

I would recommend wrapping the only widgets that need the bloc in their own `BlocProvider` for example:

```dart
ListView.builder(
  itemBuilder: (context, index) {
    return BlocProvider(create: (_) => MyBloc(), child: MyChild());
  },
);
```

**Comment by hyiip** [comment]
hi @felangel, the mixin approach is awesome, I can create multiple blocs with less code.

From the example you gave, I notice that
```
    return Scaffold(
      appBar: AppBar(
        title: const Text('Global Counter'),
      ),
      body: Center(
        child: BlocBuilder<GlobalCounter, int>(
          builder: (context, state) {
            return Text('Global Count: $state');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () =>
            context.bloc<GlobalCounter>().add(CounterEvent.increment),
      ),
    );
  }
```
you have used same code twice but only changing `GlobalCounter` to `LocalCounter`. 

Suppose I want to create 3 pages with the 3 timer counter bloc, is there any way I can create a reuseable widget which accepts a title string, then I can use something like `TimerLayout<LocalCounter>(title: "local")` or `TimerLayout(title: "local", bloc: //some bloc)` to create one of the pages? I don't know how to create a BlocBuilder with generic type.

**Comment by DFelten** [comment]
In our case the mixin solution wasn't possible because the bloc is a part of an other package. 

The solution we found is to create a new class which extends from the desired BloC:
```dart
class ContestBloc extends PostBloc {
  ContestBloc({@required PostRepository postRepository}) : super(postRepository: postRepository);
}
```

**Comment by felangel** [comment]
@hyiip you can create a reusable widget using generics like:

```dart
class TimerLayout<T extends Bloc<CounterEvent, int>> extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Global Counter'),
      ),
      body: Center(
        child: BlocBuilder<T, int>(
          builder: (context, state) {
            return Text('Global Count: $state');
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.add),
        onPressed: () =>
            context.bloc<T>().add(CounterEvent.increment),
      ),
    );
  }
}
```

Hope that helps 👍

**Comment by GsProjects** [comment]
Hi @felangel ,

I'm trying to use flutter bloc to allow a user select an employee name from a dropdown menu and then populate the form fields on the same screen based on the selected employee. These fields could then be edited. I have looked at the flutter todos example which is the closest functionality to what I want to do but its not exactly the same.

Currently I can get the dropdown button to show and select the employee object (JSON) but I cant get the form fields to populate based on this selection. I can access the employee object and its attributes via state but when I supply the variable to the initialValue attribute of a TextFormField it never shows anything even though printing the variable through the console shows its there.

If I navigate away from the page and back to it I can see the form field has now populated with the desired value. I use blocProvider to provide the bloc to a specific route.

I have been trying to do this with one bloc for the entire screen but I'm wondering now if its only possible to do this functionality with one bloc for the dropdown button and another bloc for the form. Ideally I would like to keep it to one bloc for the entire page.

Each component on the page is its own widget similar to your flutter login tutorial. I am able to print out the desired variable in the widget build function using :

`final state = context.watch<UpdateEmployeeBloc>().state;
  print(state.employee?.fname);`

but supplying state.employee?.fname to the initialValue property of a TextFormField will not display the name until I navigate away from the page and back again its like it hasn't rebuilt the widget.

Any assistance would be great.

Gar

**Comment by praveengitsit** [comment]
@felangel 

I could use the mixin as you suggested to have two different instances of the bloc in the same widget tree.
```
import 'package:flutter/material.dart';

import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

mixin GlobalCounter on Bloc<CounterEvent, int> {}

mixin LocalCounter on Bloc<CounterEvent, int> {}
```

But if I also want to specify which specific bloc it is referencing to, what should I do? 

Instead of 
**Bloc**<CounterEvent, int>, 
having a 
**CounterBloc**<CounterEvent, int>

```
mixin GlobalCounter on CounterBloc<CounterEvent, int> {}

mixin LocalCounter on CounterBloc<CounterEvent, int> {}
```


What if this specific bloc also has some arguments in it? Like one would usually have with the repository provider instances being passed on initialization. How can I send these arguments when the case mostly is that the arguments don't come outside the class but inside it?

For single instances, we usually do it like this:

```
  BlocProvider(
            create: (context) => CounterBloc(
              RepositoryProvider.of<CounterService>(context),
            ),
          ),
```
The above is _inside_ the scope of a class.

Instead of 

mixin GlobalCounter on CounterBloc<CounterEvent, int>{}
mixin GlobalCounter on CounterBloc<CounterEvent, int>**(_counterService)** {}

```
mixin GlobalCounter on CounterBloc<CounterEvent, int>(_counterService) {}

mixin LocalCounter on CounterBloc<CounterEvent, int>(_counterService) {}
```

**Comment by praveengitsit** [comment]
Been using Bloc in my Flutter production app for a year or more, and this has been a major element in how I now think of state management. But I am still unclear on how we can use the different instances of a bloc within the same widget tree. The solution to use mixin to distinguish between the two types of bloc does not really fit in with the use case, or if it does, simply is not as intuitive and neat as it should be.

Let me cite @felangel 's example above:

```
mixin GlobalCounter on Bloc<CounterEvent, int> {}

mixin LocalCounter on Bloc<CounterEvent, int> {}

enum CounterEvent { increment }

class CounterBloc extends Bloc<CounterEvent, int>
    with GlobalCounter, LocalCounter {...}
```

Here, let's assume for some reason I have ten counters in a page. (For an example of "counters", this may not seem at all practical but there are tons of instances where a similar widget using a bloc need to implemented multiple times within the widget tree)

For every counter that there is, having to include it in the class definition like

```
class CounterBloc extends Bloc<CounterEvent, int>
    with CounterOne, CounterTwo, CounterThree, CounterFour, CounterFive, CounterSix, CounterSeven.....
```
Why should the CounterBloc in its class definition contain any information for a case of however many times it is used within the application? This looks like an unnecessary coupling to me, personally. 

Another solution was to put the BlocProvider wherever it is needed within the widget tree. But this again does not fulfill most use cases. Let's suppose all ten of the counter bloc instances have some kind of a functionality to have an "initial value" (from some last saved value) from some API endpoint, where a single API endpoint provides the last saved value for all the counters. One would likely have this initial value fetched higher up in the widget tree, since values for all are fetched at once, and not individually.

But having it higher up in the widget tree would mean you no longer have access to the individual counters' BlocProvider scope and cannot call an event for the individual counters from higher up in the widget tree from where the value is fetched and received.

A simple way to distinguish between separate instances of the same bloc within the same widget tree would be of tremendous help here. I love that BlocProviders create and dispose of the bloc instances and would like to keep it as such, without having to manually create and dispose of blocs. Let me know if you need a reproducible use-case to clear this point any further.

**Comment by andersonmendesdev** [comment]
I have a similar problem, where I need to instantiate up to N blocks of the same type for a pageview.

**Comment by lionyouko** [comment]
I did not know this was an issue up to the need of using it. 

I thought that, since get it has namedInstance, bloc would be able to have something similar. 

Is still an lacking feature going on?

Again, what is the scalable way to have multiple BLoCs of the same class in a page?

Thank You

**Comment by alirezat66** [comment]
@felangel your mixin approach was wonderful, but it just work in the case we have specific and limit types, what is the best approach for something like fetching products in a tabview with category tabs. I know we can using Map<categyId, List<Product>> but do we have better solution?
