### ISSUE TITLE
bloc:how update one item in gridview? 

### ISSUE THREAD

**Issue by FetFrumos** [felangel/bloc#972]
I use GridView in my Flutter's app. Size my GridView is 30x4(with different widgets). I need to update one widget in my gridView. I have two solutions and I need to choose the best.

1.Update all GridView. It is easy but I think this is not optimal (rebuild the entire grid for one change).
2.Update one widget. it is more complicated. But I don't now how use it with bloc. I saw example [complex_list](https://github.com/felangel/bloc/tree/master/examples/flutter_complex_list).  
but you are using the update of the whole list.

What do you advise?

**Comment by felangel** [comment]
Hi @FetFrumos 👋 
Thanks for opening an issue!

If you're using `GridView.builder` I wouldn't worry about rebuilding the entire grid because it's optimized to only rebuild the visible items. If you really wanted to optimize you could have a bloc per grid item but I personally think that's unnecessary in most cases. Hope that helps 👍
